#!/usr/bin/env node
/**
 * OH-31 Precinct Data Builder
 *
 * WORKFLOW:
 *   1. Drop ohio_hd31_precinct_results.csv into data-entry/
 *   2. Run: node data-entry/build-oh31.js
 *   3. Done — data/oh31PrecinctData.ts is updated
 *
 * Reads:  data-entry/ohio_hd31_precinct_results.csv
 * Writes: data/oh31PrecinctData.ts
 */

const fs   = require("fs");
const path = require("path");

const SHEET_DIR = __dirname;
const DATA_DIR  = path.join(__dirname, "../data");

// ── CSV Parser ────────────────────────────────────────────────────────────────

function parseCSV(filename) {
  const full = path.join(SHEET_DIR, filename);
  if (!fs.existsSync(full)) {
    console.error(`ERROR: Missing file: ${full}`);
    process.exit(1);
  }
  const content = fs.readFileSync(full, "utf8").trim();
  const lines   = content.split(/\r?\n/);
  const headers = lines[0].split(",").map(h => h.trim());
  return lines.slice(1)
    .filter(l => l.trim())
    .map(line => {
      const values = line.split(",");
      const row = {};
      headers.forEach((h, i) => { row[h] = (values[i] ?? "").trim(); });
      return row;
    });
}

const num = (v) => { const n = parseFloat(v); return isNaN(n) ? 0 : n; };
const int = (v) => { const n = parseInt(v);   return isNaN(n) ? 0 : n; };

// ── Build ─────────────────────────────────────────────────────────────────────

const rows = parseCSV("ohio_hd31_precinct_results.csv");

const precincts = rows.map(r => ({
  precinct:       r.precinct,
  ballotsCast:    int(r.ballots_cast),
  regVoters:      int(r.reg_voters),

  pres: {
    dName:  r.pres_D_name,
    rName:  r.pres_R_name,
    dVotes: int(r.pres_D_votes),
    rVotes: int(r.pres_R_votes),
    total:  int(r.pres_total_votes),
    dPct:   num(r.pres_D_pct),
    rPct:   num(r.pres_R_pct),
  },

  senate: {
    dName:  r.senate_D_name,
    rName:  r.senate_R_name,
    dVotes: int(r.senate_D_votes),
    rVotes: int(r.senate_R_votes),
    total:  int(r.senate_total_votes),
    dPct:   num(r.senate_D_pct),
    rPct:   num(r.senate_R_pct),
  },

  uSHouse: {
    dName:  r.house_D_name,
    rName:  r.house_R_name,
    dVotes: int(r.house_D_votes),
    rVotes: int(r.house_R_votes),
    total:  int(r.house_total_votes),
    dPct:   num(r.house_D_pct),
    rPct:   num(r.house_R_pct),
  },

  stRep: {
    dName:  r.st_rep_D_name,
    rName:  r.st_rep_R_name,
    dVotes: int(r.st_rep_D_votes),
    rVotes: int(r.st_rep_R_votes),
    total:  int(r.st_rep_total_votes),
    dPct:   num(r.st_rep_D_pct),
    rPct:   num(r.st_rep_R_pct),
  },
}));

// ── Write TypeScript ──────────────────────────────────────────────────────────

const ts = `// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/ohio_hd31_precinct_results.csv

export interface OH31RaceResult {
  dName:  string;
  rName:  string;
  dVotes: number;
  rVotes: number;
  total:  number;
  dPct:   number;
  rPct:   number;
}

export interface OH31Precinct {
  precinct:    string;
  ballotsCast: number;
  regVoters:   number;
  pres:        OH31RaceResult;
  senate:      OH31RaceResult;
  uSHouse:     OH31RaceResult;
  stRep:       OH31RaceResult;
}

export const oh31PrecinctData: OH31Precinct[] = ${JSON.stringify(precincts, null, 2)};

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData.map(p => [p.precinct, p]));
`;

const outPath = path.join(DATA_DIR, "oh31PrecinctData.ts");
fs.writeFileSync(outPath, ts, "utf8");
console.log(`✓ Wrote ${precincts.length} precincts → ${outPath}`);
