#!/usr/bin/env node
/**
 * OH-31 Precinct Data Builder
 *
 * WORKFLOW:
 *   1. Drop CSVs into data-entry/
 *   2. Run: node data-entry/build-oh31.js
 *   3. Done — data/oh31PrecinctData.ts, data/oh31PrecinctData2022.ts,
 *             and data/oh31PrecinctData2020.ts are updated
 *
 * Reads:  data-entry/hd31_2024.csv                                           → 2024 results
 *         data-entry/hd31_2022.csv                                           → 2022 results
 *         data-entry/hd31_2020.csv                                           → 2020 results
 *         data-entry/hd31_2018.csv                                           → 2018 results
 *         data-entry/hd31_2016.csv                                           → 2016 results
 * Writes: data/oh31PrecinctData.ts
 *         data/oh31PrecinctData2022.ts
 *         data/oh31PrecinctData2020.ts
 *         data/oh31PrecinctData2018.ts
 *         data/oh31PrecinctData2016.ts
 */

const fs   = require("fs");
const path = require("path");

const SHEET_DIR = __dirname;
const DATA_DIR  = path.join(__dirname, "../data");

// ── CSV Parser ────────────────────────────────────────────────────────────────

function parseCSV(filename) {
  const full = path.join(SHEET_DIR, filename);
  if (!fs.existsSync(full)) {
    console.error(`ERROR: Missing file: ${full}`);
    process.exit(1);
  }
  const content = fs.readFileSync(full, "utf8").trim();
  const lines   = content.split(/\r?\n/);
  const headers = lines[0].split(",").map(h => h.trim());
  return lines.slice(1)
    .filter(l => l.trim())
    .map(line => {
      const values = line.split(",");
      const row = {};
      headers.forEach((h, i) => { row[h] = (values[i] ?? "").trim(); });
      return row;
    });
}

const num = (v) => { const n = parseFloat(v); return isNaN(n) ? 0 : n; };
const int = (v) => { const n = parseInt(v);   return isNaN(n) ? 0 : n; };

// Normalize township names to canonical values that match TownshipFilter option labels.
// Handles inconsistencies between 2024 and 2022 CSV exports.
function normalizeTownship(csvTownship, precinctName) {
  const t = csvTownship.toLowerCase().trim();
  if (t === "bath" || t === "bath twp")                         return "Bath";
  if (t === "boston twp" || t === "boston township")            return "Boston Twp";
  if (t === "peninsula" || t === "peninsula village")           return "Peninsula";
  if (t === "richfield" || t === "richfield township") {
    return precinctName.startsWith("RICHFIELD VILL")
      ? "Richfield Village"
      : "Richfield Township";
  }
  if (t === "richfield village")                                return "Richfield Village";
  return csvTownship.trim(); // Barberton, Boston Heights, Copley, Cuyahoga Falls, Norton
}

// ── Build ─────────────────────────────────────────────────────────────────────

const rows = parseCSV("hd31_2024.csv");

const precincts = rows.map(r => ({
  precinct:       r.precinct,
  township:       normalizeTownship(r.township, r.precinct),
  ballotsCast:    int(r.ballots_cast),
  regVoters:      int(r.reg_voters),

  pres: {
    dName:  "",
    rName:  "",
    dVotes: int(r.pres_d),
    rVotes: int(r.pres_r),
    total:  int(r.pres_total),
    dPct:   num(r.pres_d_pct),
    rPct:   num(r.pres_r_pct),
  },

  senate: {
    dName:  "",
    rName:  "",
    dVotes: int(r.sen_d),
    rVotes: int(r.sen_r),
    total:  int(r.sen_total),
    dPct:   num(r.sen_d_pct),
    rPct:   num(r.sen_r_pct),
  },

  uSHouse: {
    dName:  "",
    rName:  "",
    dVotes: int(r.house_d),
    rVotes: int(r.house_r),
    total:  int(r.house_total),
    dPct:   num(r.house_d_pct),
    rPct:   num(r.house_r_pct),
  },

  stRep: {
    dName:  "",
    rName:  "",
    dVotes: int(r.srep_d),
    rVotes: int(r.srep_r),
    total:  int(r.srep_total),
    dPct:   num(r.srep_d_pct),
    rPct:   num(r.srep_r_pct),
  },
}));

// ── Write TypeScript ──────────────────────────────────────────────────────────

const ts = `// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/ohio_hd31_precinct_results.csv

export interface OH31RaceResult {
  dName:  string;
  rName:  string;
  dVotes: number;
  rVotes: number;
  total:  number;
  dPct:   number;
  rPct:   number;
}

export interface OH31Precinct {
  precinct:    string;
  township:    string;
  ballotsCast: number;
  regVoters:   number;
  pres:        OH31RaceResult;
  senate:      OH31RaceResult;
  uSHouse:     OH31RaceResult;
  stRep:       OH31RaceResult;
}

export const oh31PrecinctData: OH31Precinct[] = ${JSON.stringify(precincts, null, 2)};

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData.map(p => [p.precinct, p]));
`;

const outPath = path.join(DATA_DIR, "oh31PrecinctData.ts");
fs.writeFileSync(outPath, ts, "utf8");
console.log(`✓ Wrote ${precincts.length} precincts (2024) → ${outPath}`);

// ── 2022 Build ────────────────────────────────────────────────────────────────
// In 2022, "pres" stores Governor results (Whaley vs DeWine).
// No candidate name columns in source CSV — dName/rName left as empty strings.

const rows22 = parseCSV("hd31_2022.csv");

// Build GeoJSON code → human-readable name lookup by matching on governor vote totals.
// gov_d + gov_r is unique across all 97 precincts (verified at build time).
const geoJsonPath22 = path.join(__dirname, "../public/oh31_2022_precincts.geojson");
const geoJson22 = JSON.parse(fs.readFileSync(geoJsonPath22, "utf8"));
const csvLookup22 = {};
rows22.forEach(r => { csvLookup22[`${r.gov_d}|${r.gov_r}`] = r.precinct; });
const precinctCodeToName22 = {};
geoJson22.features.forEach(f => {
  const p = f.properties;
  const key = `${p.G22GOVDWHA}|${p.G22GOVRDEW}`;
  const name = csvLookup22[key];
  if (name) precinctCodeToName22[p.PRECINCT] = name;
});

const precincts22 = rows22.map(r => ({
  precinct:    r.precinct,
  township:    normalizeTownship(r.township, r.precinct),
  ballotsCast: int(r.ballots),
  regVoters:   int(r.reg_voters),

  pres: {
    dName:  "",
    rName:  "",
    dVotes: int(r.gov_d),
    rVotes: int(r.gov_r),
    total:  int(r.gov_total),
    dPct:   num(r.gov_d_pct),
    rPct:   num(r.gov_r_pct),
  },

  senate: {
    dName:  "",
    rName:  "",
    dVotes: int(r.sen_d),
    rVotes: int(r.sen_r),
    total:  int(r.sen_total),
    dPct:   num(r.sen_d_pct),
    rPct:   num(r.sen_r_pct),
  },

  uSHouse: {
    dName:  "",
    rName:  "",
    dVotes: int(r.house_d),
    rVotes: int(r.house_r),
    total:  int(r.house_total),
    dPct:   num(r.house_d_pct),
    rPct:   num(r.house_r_pct),
  },

  stRep: {
    dName:  "",
    rName:  "",
    dVotes: int(r.srep_d),
    rVotes: int(r.srep_r),
    total:  int(r.srep_total),
    dPct:   num(r.srep_d_pct),
    rPct:   num(r.srep_r_pct),
  },
}));

const ts22 = `// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/summit_10_townships_results_22.csv
// NOTE: "pres" field stores 2022 Governor results (Whaley vs DeWine).

import type { OH31Precinct } from "@/data/oh31PrecinctData";

export const oh31PrecinctData2022: OH31Precinct[] = ${JSON.stringify(precincts22, null, 2)};

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct2022: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData2022.map(p => [p.precinct, p]));

/** Maps GeoJSON PRECINCT code (e.g. "ANO") → human-readable name (e.g. "NORTON A") */
export const oh31PrecinctCodeToName2022: Record<string, string> = ${JSON.stringify(precinctCodeToName22, null, 2)};
`;

const outPath22 = path.join(DATA_DIR, "oh31PrecinctData2022.ts");
fs.writeFileSync(outPath22, ts22, "utf8");
console.log(`✓ Wrote ${precincts22.length} precincts (2022) → ${outPath22}`);

// ── 2020 Build ────────────────────────────────────────────────────────────────
// "pres" stores 2020 President results (Biden vs Trump).
// No Ohio U.S. Senate race in 2020 — senate field zeroed out.
// GeoJSON uses NAME20 property which matches CSV precinct names directly.

const rows20 = parseCSV("hd31_2020.csv");

const ZERO_RACE = { dName: "", rName: "", dVotes: 0, rVotes: 0, total: 0, dPct: 0, rPct: 0 };

const precincts20 = rows20.map(r => ({
  precinct:    r.precinct,
  township:    normalizeTownship(r.township, r.precinct),
  ballotsCast: int(r.ballots),
  regVoters:   int(r.reg_voters),

  pres: {
    dName:  "Biden",
    rName:  "Trump",
    dVotes: int(r.pres_d),
    rVotes: int(r.pres_r),
    total:  int(r.pres_total),
    dPct:   num(r.pres_d_pct),
    rPct:   num(r.pres_r_pct),
  },

  // No Ohio U.S. Senate race in 2020
  senate: ZERO_RACE,

  uSHouse: {
    dName:  "",
    rName:  "",
    dVotes: int(r.house_d),
    rVotes: int(r.house_r),
    total:  int(r.house_total),
    dPct:   num(r.house_d_pct),
    rPct:   num(r.house_r_pct),
  },

  stRep: {
    dName:  "",
    rName:  "",
    dVotes: int(r.srep_d),
    rVotes: int(r.srep_r),
    total:  int(r.srep_total),
    dPct:   num(r.srep_d_pct),
    rPct:   num(r.srep_r_pct),
  },
}));

const ts20 = `// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/summit_10_townships_results_2020_with_house_srep.csv
// NOTE: "senate" field is zeroed — no Ohio U.S. Senate race in 2020.

import type { OH31Precinct } from "@/data/oh31PrecinctData";

export const oh31PrecinctData2020: OH31Precinct[] = ${JSON.stringify(precincts20, null, 2)};

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct2020: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData2020.map(p => [p.precinct, p]));
`;

const outPath20 = path.join(DATA_DIR, "oh31PrecinctData2020.ts");
fs.writeFileSync(outPath20, ts20, "utf8");
console.log(`✓ Wrote ${precincts20.length} precincts (2020) → ${outPath20}`);

// ── 2018 Build ────────────────────────────────────────────────────────────────
// "pres" stores 2018 Governor results (Cordray vs DeWine).
// GeoJSON uses NAME18 property which matches CSV precinct names directly.

const rows18 = parseCSV("hd31_2018.csv");

const precincts18 = rows18.map(r => ({
  precinct:    r.precinct,
  township:    normalizeTownship(r.township, r.precinct),
  ballotsCast: int(r.ballots),
  regVoters:   int(r.reg_voters),

  pres: {
    dName:  "Cordray",
    rName:  "DeWine",
    dVotes: int(r.gov_d),
    rVotes: int(r.gov_r),
    total:  int(r.gov_total),
    dPct:   num(r.gov_d_pct),
    rPct:   num(r.gov_r_pct),
  },

  senate: {
    dName:  "Brown",
    rName:  "Renacci",
    dVotes: int(r.sen_d),
    rVotes: int(r.sen_r),
    total:  int(r.sen_total),
    dPct:   num(r.sen_d_pct),
    rPct:   num(r.sen_r_pct),
  },

  uSHouse: {
    dName:  "",
    rName:  "",
    dVotes: int(r.house_d),
    rVotes: int(r.house_r),
    total:  int(r.house_total),
    dPct:   num(r.house_d_pct),
    rPct:   num(r.house_r_pct),
  },

  stRep: {
    dName:  "",
    rName:  "",
    dVotes: int(r.srep_d),
    rVotes: int(r.srep_r),
    total:  int(r.srep_total),
    dPct:   num(r.srep_d_pct),
    rPct:   num(r.srep_r_pct),
  },
}));

const ts18 = `// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/hd31_2018.csv
// NOTE: "pres" field stores 2018 Governor results (Cordray vs DeWine).

import type { OH31Precinct } from "@/data/oh31PrecinctData";

export const oh31PrecinctData2018: OH31Precinct[] = ${JSON.stringify(precincts18, null, 2)};

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct2018: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData2018.map(p => [p.precinct, p]));
`;

const outPath18 = path.join(DATA_DIR, "oh31PrecinctData2018.ts");
fs.writeFileSync(outPath18, ts18, "utf8");
console.log(`✓ Wrote ${precincts18.length} precincts (2018) → ${outPath18}`);

// ── 2016 Build ────────────────────────────────────────────────────────────────
// "pres" stores 2016 President results (Clinton vs Trump).
// GeoJSON uses NAME16 property which matches CSV precinct names directly.

const rows16 = parseCSV("hd31_2016.csv");

const precincts16 = rows16.map(r => ({
  precinct:    r.precinct,
  township:    normalizeTownship(r.township, r.precinct),
  ballotsCast: int(r.ballots),
  regVoters:   int(r.reg_voters),

  pres: {
    dName:  "Clinton",
    rName:  "Trump",
    dVotes: int(r.pres_d),
    rVotes: int(r.pres_r),
    total:  int(r.pres_total),
    dPct:   num(r.pres_d_pct),
    rPct:   num(r.pres_r_pct),
  },

  senate: {
    dName:  "Strickland",
    rName:  "Portman",
    dVotes: int(r.sen_d),
    rVotes: int(r.sen_r),
    total:  int(r.sen_total),
    dPct:   num(r.sen_d_pct),
    rPct:   num(r.sen_r_pct),
  },

  uSHouse: {
    dName:  "",
    rName:  "",
    dVotes: int(r.house_d),
    rVotes: int(r.house_r),
    total:  int(r.house_total),
    dPct:   num(r.house_d_pct),
    rPct:   num(r.house_r_pct),
  },

  stRep: {
    dName:  "",
    rName:  "",
    dVotes: int(r.srep_d),
    rVotes: int(r.srep_r),
    total:  int(r.srep_total),
    dPct:   num(r.srep_d_pct),
    rPct:   num(r.srep_r_pct),
  },
}));

const ts16 = `// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/hd31_2016.csv
// NOTE: "pres" field stores 2016 President results (Clinton vs Trump).

import type { OH31Precinct } from "@/data/oh31PrecinctData";

export const oh31PrecinctData2016: OH31Precinct[] = ${JSON.stringify(precincts16, null, 2)};

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct2016: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData2016.map(p => [p.precinct, p]));
`;

const outPath16 = path.join(DATA_DIR, "oh31PrecinctData2016.ts");
fs.writeFileSync(outPath16, ts16, "utf8");
console.log(`✓ Wrote ${precincts16.length} precincts (2016) → ${outPath16}`);
