/**
 * Map candidate names to image paths under /public/candidates/.
 * Drop any image file into public/candidates/ and add an entry here.
 * Supported formats: .jpg, .jpeg, .png, .webp
 *
 * Example:
 *   "Susan Collins": "/candidates/susan-collins.jpg",
 */
export const candidatePhotos: Record<string, string> = {
  // ── Democrats ──────────────────────────────────────────────────────────────
  "Aaron Ford": "/candidates/aaron-ford.jpg",
  "Annie Andrews": "/candidates/annie-andrews.jpg",
  "Ben Ray Lujan": "/candidates/ben-ray-lujan.jpg",
  "Amy Acton": "/candidates/amy-acton.png",
  "Charles Booker": "/candidates/charles-booker.jpg",
  "Cory Booker": "/candidates/cory-booker.jpg",
  "Deb Haaland": "/candidates/deb-haaland.jpg",
  "Dan Osborne": "/candidates/dan-osborne.jpg",
  "David Roth": "/candidates/david-roth.jpg",
  "Doug Jones": "/candidates/doug-jones.jpg",
  "Everett Wess": "/candidates/everett-wess.jpg",
  "Fredrick Love": "/candidates/fredrick-love.jpg",
  "Gina Hinojosa": "/candidates/gina-hinojosa.jpg",
  "Graham Platner": "/candidates/graham-platner.jpg",
  "Hallie Shoffner": "/candidates/hallie-shoffner.jpg",
  "Hannah Pingree": "/candidates/hannah-pingree.jpg",
  "Jermaine Johnson": "/candidates/jermaine-johnson.jpg",
  "James Talarico": "/candidates/james-talarico.jpg",
  "Jamie Davis": "/candidates/jamie-davis.jpg",
  "Jeff Merkley": "/candidates/jeff-merkley.jpg",
  "Josh Turek": "/candidates/josh-turek.jpg",
  "Julian Beaudion": "/candidates/julian-beaudion.jpg",
  "Jon Husted": "/candidates/jon-husted.jpg",
  "Jon Ossoff": "/candidates/jon-ossoff.jpg",
  "Juliana Stratton": "/candidates/juliana-stratton.jpg",
  "JB Pritzker": "/candidates/jb-pritzker.jpg",
  "Josh Shapiro": "/candidates/josh-shapiro.jpg",
  "Kathy Hochul": "/candidates/kathy-hochul.jpg",
  "Keisha Lance Bottoms": "/candidates/keisha-lance-bottoms.jpg",
  "Lynne Walz": "/candidates/lynne-walz.jpg",
  "Rob Sand": "/candidates/rob-sand.jpg",
  "Roy Cooper": "/candidates/roy-cooper.jpg",
  "Rachel Fetty Anderson": "/candidates/rachel-fetty-anderson.jpg",
  "Scott Colom": "/candidates/scott-colom.jpg",
  "Seth Bodnar": "/candidates/seth-bodnar.jpg",
  "Sherrod Brown": "/candidates/sherrod-brown.jpg",
  "Terri Pickens": "/candidates/terri-pickens.jpg",
  "Tina Kotek": "/candidates/tina-kotek.jpg",
  "Wes Moore": "/candidates/wes-moore.jpg",
  "Xavier Becerra": "/candidates/xavier-becerra.jpg",

  // ── Republicans ────────────────────────────────────────────────────────────
  "Alan Wilson": "/candidates/alan-wilson.jpg",
  "Andy Barr": "/candidates/andy-barr.jpg",
  "Ashley Hinson": "/candidates/ashley-hinson.jpg",
  "Barry Moore": "/candidates/barry-moore.jpg",
  "Brad Little": "/candidates/brad-little.jpg",
  "Bruce Blakeman": "/candidates/bruce-blakeman.jpg",
  "Christine Drazan": "/candidates/christine-drazan.jpg",
  "Cindy Hyde-Smith": "/candidates/cindy-hyde-smith.jpg",
  "Dan Cox": "/candidates/dan-cox.jpg",
  "David Brock Smith": "/candidates/david-brock-smith.jpg",
  "Don Tracy": "/candidates/don-tracy.jpg",
  "Darren Bailey": "/candidates/darren-bailey.jpg",
  "Greg Abbott": "/candidates/greg-abbott.jpg",
  "Gregg Hull": "/candidates/gregg-hull.jpg",
  "Jim Pillen": "/candidates/jim-pillen.jpg",
  "Julia Letlow": "/candidates/julia-letlow.jpg",
  "Ken Paxton": "/candidates/ken-paxton.jpg",
  "Kurt Alme": "/candidates/kurt-alme.jpg",
  "Larry Marker": "/candidates/larry-marker.jpg",
  "Lindsey Graham": "/candidates/lindsey-graham.jpg",
  "Jim Risch": "/candidates/jim-risch.jpg",
  "Justin Murphy": "/candidates/justin-murphy.jpg",
  "Joe Lombardo": "/candidates/joe-lombardo.jpg",
  "Michael Whatley": "/candidates/michael-whatley.jpg",
  "Mike Rounds": "/candidates/mike-rounds.jpg",
  "Mike Collins": "/candidates/mike-collins.jpg",
  "Pete Ricketts": "/candidates/pete-ricketts.jpg",
  "Rick Jackson": "/candidates/rick-jackson.jpg",
  "Robert Charles": "/candidates/robert-charles.jpg",
  "Sarah Huckabee Sanders": "/candidates/sarah-huckabee-sanders.jpg",
  "Shelley Moore Capito": "/candidates/shelley-moore-capito.jpg",
  "Stacy Garrity": "/candidates/stacy-garrity.jpg",
  "Steve Hilton": "/candidates/steve-hilton.jpg",
  "Susan Collins": "/candidates/susan-collins.jpg",
  "Tom Cotton": "/candidates/tom-cotton.jpg",
  "Tommy Tuberville": "/candidates/tommy-tuberville.jpg",
  "Vivek Ramaswamy": "/candidates/vivek-ramaswamy.jpg",
  "Zach Lahn": "/candidates/zach-lahn.jpg",
};
