import { pollsterAliases, pollsterGrades } from "@/data/pollsterLookup";

// ── Pollster identity and grades ─────────────────────────────────────────────
// Poll tables spell one pollster many ways ("Siena University", "NY Times/Siena",
// "Beacon Research (D)/ Shaw & Co. Research" = the Fox News poll). Every name is
// normalised and looked up in the alias table generated by
// scripts/build-pollster-ratings.py (538's own spellings + data-entry/pollster_aliases.csv);
// a pollster with no rating id is keyed by its normalised name.

/** Keep in step with norm_name() in scripts/build-pollster-ratings.py. */
export function normalisePollsterName(name: string): string {
  return name.replace(/\((D|R|I)[^)]*\)/g, " ").replace(/\*\*/g, " ").replace(/&/g, " and ").toLowerCase().replace(/[^a-z0-9/ ]/g, " ").replace(/\s+/g, " ").trim();
}

/** Rating id ("88") when the pollster has one, else "name:<normalised name>". */
export function pollsterIdOf(name: string): string {
  const key = normalisePollsterName(name);
  return pollsterAliases[key] ?? `name:${key}`;
}

export interface PollsterGrade { id: string; name: string; grade: string | null; score: number | null; n: number }

/** The pollster's historical grade, or null when it has no graded polls on file. */
export function pollsterGradeOf(name: string): PollsterGrade | null {
  const id = pollsterIdOf(name); const g = pollsterGrades[id];
  return g ? { id, name: g[0], grade: g[1], score: g[2], n: g[3] } : null;
}
