// GENERATED by `npx tsx scripts/forwardBacktest.ts --env struct --emit` — do not edit by hand.
// The forward backtest behind the Calibration section of /methodology: every eligible Senate / Governor race
// (and House races on stable lines) predicted as of mid-September from a fit on years ≤ Y−1, under the live
// constants. Re-run after any change to the model or its data so the page keeps describing the model as it is.
export const FORECAST_CALIBRATION = {
  "generatedAt": "2026-09-22",
  "years": [
    2018,
    2020,
    2022,
    2024
  ],
  "environment": {
    "c": 0.52,
    "s": 0.72,
    "meanMiss": 1.34,
    "sdMiss": 1.96,
    "sdDrift": 1.7,
    "sigmaEMidSept": 1.87
  },
  "byYear": [
    {
      "year": 2018,
      "office": "S",
      "n": 34,
      "E": -4.4,
      "mae": 6.1,
      "bias": -2.9,
      "r": 0.94
    },
    {
      "year": 2018,
      "office": "G",
      "n": 36,
      "E": -4.4,
      "mae": 9.8,
      "bias": 2.27,
      "r": 0.66
    },
    {
      "year": 2018,
      "office": "H",
      "n": 6,
      "E": -4.4,
      "mae": 6.51,
      "bias": -6.36,
      "r": 1
    },
    {
      "year": 2020,
      "office": "S",
      "n": 33,
      "E": -3.9,
      "mae": 5.39,
      "bias": 4.02,
      "r": 0.96
    },
    {
      "year": 2020,
      "office": "G",
      "n": 11,
      "E": -3.9,
      "mae": 12.37,
      "bias": 11.96,
      "r": 0.82
    },
    {
      "year": 2020,
      "office": "H",
      "n": 5,
      "E": -3.9,
      "mae": 5.87,
      "bias": 5.64,
      "r": 1
    },
    {
      "year": 2022,
      "office": "S",
      "n": 33,
      "E": 0.63,
      "mae": 4.81,
      "bias": 1.1,
      "r": 0.96
    },
    {
      "year": 2022,
      "office": "G",
      "n": 36,
      "E": 0.63,
      "mae": 7.28,
      "bias": 2.38,
      "r": 0.92
    },
    {
      "year": 2022,
      "office": "H",
      "n": 201,
      "E": 0.63,
      "mae": 4.62,
      "bias": 0.85,
      "r": 0.98
    },
    {
      "year": 2024,
      "office": "S",
      "n": 33,
      "E": 0.18,
      "mae": 3.7,
      "bias": 2.23,
      "r": 0.98
    },
    {
      "year": 2024,
      "office": "G",
      "n": 11,
      "E": 0.18,
      "mae": 7.63,
      "bias": 3.05,
      "r": 0.91
    },
    {
      "year": 2024,
      "office": "H",
      "n": 237,
      "E": 0.18,
      "mae": 4.46,
      "bias": 2.58,
      "r": 0.99
    }
  ],
  "pooled": [
    {
      "office": "S",
      "n": 133,
      "mae": 5.01,
      "bias": 1.08,
      "meanAbsYearBias": 2.56,
      "withinRsd": 4.75,
      "nationalSd": 2.54,
      "liveRaceSigma": 6,
      "cover80": 0.797,
      "brier": 0.059,
      "brierCoinFlip": 0.25,
      "calledRight": 0.925
    },
    {
      "office": "G",
      "n": 94,
      "mae": 8.88,
      "bias": 3.53,
      "meanAbsYearBias": 4.91,
      "withinRsd": 8.24,
      "nationalSd": 4.08,
      "liveRaceSigma": 9.4,
      "cover80": 0.83,
      "brier": 0.093,
      "brierCoinFlip": 0.25,
      "calledRight": 0.894
    },
    {
      "office": "H",
      "n": 449,
      "mae": 4.58,
      "bias": 1.72,
      "meanAbsYearBias": 3.86,
      "withinRsd": 4.94,
      "nationalSd": 4.41,
      "liveRaceSigma": 5.3,
      "cover80": 0.788,
      "brier": 0.024,
      "brierCoinFlip": 0.25,
      "calledRight": 0.969
    }
  ],
  "calibration": [
    {
      "lo": 0,
      "hi": 0.05,
      "n": 239,
      "meanP": 0.007,
      "demWon": 0.008
    },
    {
      "lo": 0.05,
      "hi": 0.25,
      "n": 48,
      "meanP": 0.125,
      "demWon": 0.083
    },
    {
      "lo": 0.25,
      "hi": 0.5,
      "n": 31,
      "meanP": 0.368,
      "demWon": 0.29
    },
    {
      "lo": 0.5,
      "hi": 0.75,
      "n": 42,
      "meanP": 0.631,
      "demWon": 0.738
    },
    {
      "lo": 0.75,
      "hi": 0.95,
      "n": 52,
      "meanP": 0.863,
      "demWon": 0.885
    },
    {
      "lo": 0.95,
      "hi": 1,
      "n": 264,
      "meanP": 0.993,
      "demWon": 0.992
    }
  ],
  "ablation": [
    {
      "variant": "Full model",
      "mae": {
        "S": 5.01,
        "G": 8.88,
        "H": 4.58
      }
    },
    {
      "variant": "No candidates",
      "mae": {
        "S": 5.11,
        "G": 10.49,
        "H": 4.78
      }
    },
    {
      "variant": "No fundraising",
      "mae": {
        "S": 5.65,
        "G": 9.33,
        "H": 4.78
      }
    },
    {
      "variant": "No incumbency",
      "mae": {
        "S": 5.87,
        "G": 9.65,
        "H": 5.01
      }
    },
    {
      "variant": "No environment",
      "mae": {
        "S": 5.26,
        "G": 9.12,
        "H": 4.65
      }
    },
    {
      "variant": "Lean only",
      "mae": {
        "S": 6.92,
        "G": 11.61,
        "H": 5.54
      }
    }
  ],
  "polls": [
    {
      "horizon": "Mid-September",
      "office": "S",
      "polled": 105,
      "all": 133,
      "maeModel": 4.85,
      "maePoll": 6.64,
      "maeBlend": 4.69,
      "meanW": 0.4
    },
    {
      "horizon": "Mid-September",
      "office": "G",
      "polled": 80,
      "all": 94,
      "maeModel": 9.36,
      "maePoll": 5.76,
      "maeBlend": 7.27,
      "meanW": 0.45
    },
    {
      "horizon": "Mid-September",
      "office": "H",
      "polled": 104,
      "all": 449,
      "maeModel": 4.16,
      "maePoll": 5.11,
      "maeBlend": 3.61,
      "meanW": 0.19
    },
    {
      "horizon": "Mid-October",
      "office": "S",
      "polled": 115,
      "all": 133,
      "maeModel": 4.83,
      "maePoll": 6.51,
      "maeBlend": 4.54,
      "meanW": 0.48
    },
    {
      "horizon": "Mid-October",
      "office": "G",
      "polled": 87,
      "all": 94,
      "maeModel": 9.1,
      "maePoll": 6.05,
      "maeBlend": 5.86,
      "meanW": 0.55
    },
    {
      "horizon": "Mid-October",
      "office": "H",
      "polled": 121,
      "all": 449,
      "maeModel": 4.14,
      "maePoll": 5.14,
      "maeBlend": 3.51,
      "meanW": 0.24
    },
    {
      "horizon": "November 1",
      "office": "S",
      "polled": 122,
      "all": 133,
      "maeModel": 4.98,
      "maePoll": 6.02,
      "maeBlend": 4.6,
      "meanW": 0.53
    },
    {
      "horizon": "November 1",
      "office": "G",
      "polled": 89,
      "all": 94,
      "maeModel": 9,
      "maePoll": 5.37,
      "maeBlend": 5.4,
      "meanW": 0.58
    },
    {
      "horizon": "November 1",
      "office": "H",
      "polled": 132,
      "all": 449,
      "maeModel": 4.2,
      "maePoll": 5.13,
      "maeBlend": 3.48,
      "meanW": 0.26
    }
  ]
} as const;
