// GENERATED by `npx tsx scripts/forwardBacktest.ts --env struct --emit` — do not edit by hand.
// The forward backtest behind the Calibration section of /methodology: every eligible Senate / Governor race
// (and House races on stable lines) predicted as of mid-September from a fit on years ≤ Y−1, under the live
// constants. Re-run after any change to the model or its data so the page keeps describing the model as it is.
export const FORECAST_CALIBRATION = {
  "generatedAt": "2026-09-21",
  "years": [
    2018,
    2020,
    2022,
    2024
  ],
  "environment": {
    "c": 0.52,
    "s": 0.72,
    "meanMiss": 1.34,
    "sdMiss": 1.96,
    "sdDrift": 1.7,
    "sigmaEMidSept": 1.87
  },
  "byYear": [
    {
      "year": 2018,
      "office": "S",
      "n": 34,
      "E": -4.4,
      "mae": 6.47,
      "bias": -3.12,
      "r": 0.94
    },
    {
      "year": 2018,
      "office": "G",
      "n": 36,
      "E": -4.4,
      "mae": 10.09,
      "bias": 2.18,
      "r": 0.65
    },
    {
      "year": 2018,
      "office": "H",
      "n": 6,
      "E": -4.4,
      "mae": 6.51,
      "bias": -6.36,
      "r": 1
    },
    {
      "year": 2020,
      "office": "S",
      "n": 33,
      "E": -3.9,
      "mae": 5.37,
      "bias": 3.59,
      "r": 0.95
    },
    {
      "year": 2020,
      "office": "G",
      "n": 11,
      "E": -3.9,
      "mae": 11.91,
      "bias": 11.45,
      "r": 0.81
    },
    {
      "year": 2020,
      "office": "H",
      "n": 5,
      "E": -3.9,
      "mae": 5.87,
      "bias": 5.64,
      "r": 1
    },
    {
      "year": 2022,
      "office": "S",
      "n": 33,
      "E": 0.63,
      "mae": 4.69,
      "bias": 0.79,
      "r": 0.97
    },
    {
      "year": 2022,
      "office": "G",
      "n": 36,
      "E": 0.63,
      "mae": 7.21,
      "bias": 2.18,
      "r": 0.92
    },
    {
      "year": 2022,
      "office": "H",
      "n": 201,
      "E": 0.63,
      "mae": 4.62,
      "bias": 0.85,
      "r": 0.98
    },
    {
      "year": 2024,
      "office": "S",
      "n": 33,
      "E": 0.18,
      "mae": 3.62,
      "bias": 1.95,
      "r": 0.98
    },
    {
      "year": 2024,
      "office": "G",
      "n": 11,
      "E": 0.18,
      "mae": 7.63,
      "bias": 2.62,
      "r": 0.9
    },
    {
      "year": 2024,
      "office": "H",
      "n": 237,
      "E": 0.18,
      "mae": 4.46,
      "bias": 2.58,
      "r": 0.99
    }
  ],
  "pooled": [
    {
      "office": "S",
      "n": 133,
      "mae": 5.05,
      "bias": 0.77,
      "meanAbsYearBias": 2.36,
      "withinRsd": 4.88,
      "nationalSd": 2.47,
      "liveRaceSigma": 6,
      "cover80": 0.827,
      "brier": 0.061,
      "brierCoinFlip": 0.25,
      "calledRight": 0.917
    },
    {
      "office": "G",
      "n": 94,
      "mae": 8.91,
      "bias": 3.32,
      "meanAbsYearBias": 4.61,
      "withinRsd": 9.05,
      "nationalSd": 3.96,
      "liveRaceSigma": 9.4,
      "cover80": 0.809,
      "brier": 0.095,
      "brierCoinFlip": 0.25,
      "calledRight": 0.872
    },
    {
      "office": "H",
      "n": 449,
      "mae": 4.58,
      "bias": 1.72,
      "meanAbsYearBias": 3.86,
      "withinRsd": 4.94,
      "nationalSd": 4.41,
      "liveRaceSigma": 5.3,
      "cover80": 0.788,
      "brier": 0.024,
      "brierCoinFlip": 0.25,
      "calledRight": 0.969
    }
  ],
  "calibration": [
    {
      "lo": 0,
      "hi": 0.05,
      "n": 243,
      "meanP": 0.008,
      "demWon": 0.008
    },
    {
      "lo": 0.05,
      "hi": 0.25,
      "n": 47,
      "meanP": 0.132,
      "demWon": 0.085
    },
    {
      "lo": 0.25,
      "hi": 0.5,
      "n": 33,
      "meanP": 0.377,
      "demWon": 0.394
    },
    {
      "lo": 0.5,
      "hi": 0.75,
      "n": 36,
      "meanP": 0.632,
      "demWon": 0.722
    },
    {
      "lo": 0.75,
      "hi": 0.95,
      "n": 54,
      "meanP": 0.861,
      "demWon": 0.889
    },
    {
      "lo": 0.95,
      "hi": 1,
      "n": 263,
      "meanP": 0.993,
      "demWon": 0.992
    }
  ],
  "ablation": [
    {
      "variant": "Full model",
      "mae": {
        "S": 5.05,
        "G": 8.91,
        "H": 4.58
      }
    },
    {
      "variant": "No candidates",
      "mae": {
        "S": 5.2,
        "G": 10.55,
        "H": 4.78
      }
    },
    {
      "variant": "No fundraising",
      "mae": {
        "S": 5.75,
        "G": 9.38,
        "H": 4.78
      }
    },
    {
      "variant": "No incumbency",
      "mae": {
        "S": 5.81,
        "G": 9.72,
        "H": 5.01
      }
    },
    {
      "variant": "No environment",
      "mae": {
        "S": 5.36,
        "G": 9.14,
        "H": 4.65
      }
    },
    {
      "variant": "Lean only",
      "mae": {
        "S": 7.1,
        "G": 11.69,
        "H": 5.54
      }
    }
  ],
  "polls": [
    {
      "horizon": "Mid-September",
      "office": "S",
      "polled": 105,
      "all": 133,
      "maeModel": 4.89,
      "maePoll": 6.64,
      "maeBlend": 4.57,
      "meanW": 0.4
    },
    {
      "horizon": "Mid-September",
      "office": "G",
      "polled": 80,
      "all": 94,
      "maeModel": 9.43,
      "maePoll": 5.76,
      "maeBlend": 7.27,
      "meanW": 0.45
    },
    {
      "horizon": "Mid-September",
      "office": "H",
      "polled": 104,
      "all": 449,
      "maeModel": 4.16,
      "maePoll": 5.11,
      "maeBlend": 3.61,
      "meanW": 0.19
    },
    {
      "horizon": "Mid-October",
      "office": "S",
      "polled": 115,
      "all": 133,
      "maeModel": 4.85,
      "maePoll": 6.51,
      "maeBlend": 4.46,
      "meanW": 0.48
    },
    {
      "horizon": "Mid-October",
      "office": "G",
      "polled": 87,
      "all": 94,
      "maeModel": 9.16,
      "maePoll": 6.05,
      "maeBlend": 5.85,
      "meanW": 0.55
    },
    {
      "horizon": "Mid-October",
      "office": "H",
      "polled": 121,
      "all": 449,
      "maeModel": 4.14,
      "maePoll": 5.14,
      "maeBlend": 3.51,
      "meanW": 0.24
    },
    {
      "horizon": "November 1",
      "office": "S",
      "polled": 122,
      "all": 133,
      "maeModel": 4.99,
      "maePoll": 6.02,
      "maeBlend": 4.5,
      "meanW": 0.53
    },
    {
      "horizon": "November 1",
      "office": "G",
      "polled": 89,
      "all": 94,
      "maeModel": 9.03,
      "maePoll": 5.37,
      "maeBlend": 5.37,
      "meanW": 0.58
    },
    {
      "horizon": "November 1",
      "office": "H",
      "polled": 132,
      "all": 449,
      "maeModel": 4.2,
      "maePoll": 5.13,
      "maeBlend": 3.48,
      "meanW": 0.26
    }
  ]
} as const;
