// Sitting statewide officeholders and when each seat is next up. Auto-generated by
// scripts/generate-officeholders.py from data-entry/governor_seats.csv and
// data-entry/senate_seats.csv — do not edit by hand, rerun the script.
//
// data/forecastData.ts is built from the same rows but keeps only the seats on this cycle's
// ballot; this is the full roster, for answering who represents a given address.

export type OfficeholderParty = "D" | "R" | "I" | "O";

export type Governor = {
  name: string;
  party: OfficeholderParty;
  /** Year this seat is next on the ballot. */
  nextElection: number;
  termYears: number;
};

export type Senator = {
  /** The state's seat 1 or 2 — an arbitrary but stable ordering, not seniority. */
  seat: number;
  /** US Senate class 1, 2 or 3, which is what sets the election year. */
  seatClass: number;
  name: string;
  party: OfficeholderParty;
  nextElection: number;
};

export type StateOfficeholders = { governor: Governor; senators: Senator[] };

// Keyed by state abbreviation.
export const officeholders: Record<string, StateOfficeholders> = {
  AK: {
    governor: { name: "Mike Dunleavy", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Dan Sullivan", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Lisa Murkowski", party: "R", nextElection: 2028 },
    ],
  },
  AL: {
    governor: { name: "Kay Ivey", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Tommy Tuberville", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Katie Britt", party: "R", nextElection: 2028 },
    ],
  },
  AR: {
    governor: { name: "Sarah Huckabee Sanders", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Tom Cotton", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "John Boozman", party: "R", nextElection: 2028 },
    ],
  },
  AZ: {
    governor: { name: "Katie Hobbs", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Ruben Gallego", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Mark Kelly", party: "D", nextElection: 2028 },
    ],
  },
  CA: {
    governor: { name: "Gavin Newsom", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Adam Schiff", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Alex Padilla", party: "D", nextElection: 2028 },
    ],
  },
  CO: {
    governor: { name: "Jared Polis", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "John Hickenlooper", party: "D", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Michael Bennet", party: "D", nextElection: 2028 },
    ],
  },
  CT: {
    governor: { name: "Ned Lamont", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Chris Murphy", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Richard Blumenthal", party: "D", nextElection: 2028 },
    ],
  },
  DE: {
    governor: { name: "Matt Meyer", party: "D", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Lisa Blunt Rochester", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Chris Coons", party: "D", nextElection: 2026 },
    ],
  },
  FL: {
    governor: { name: "Ron DeSantis", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Rick Scott", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Ashley Moody", party: "R", nextElection: 2026 },
    ],
  },
  GA: {
    governor: { name: "Brian Kemp", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Jon Ossoff", party: "D", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Raphael Warnock", party: "D", nextElection: 2028 },
    ],
  },
  HI: {
    governor: { name: "Josh Green", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Mazie Hirono", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Brian Schatz", party: "D", nextElection: 2028 },
    ],
  },
  IA: {
    governor: { name: "Kim Reynolds", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Joni Ernst", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Chuck Grassley", party: "R", nextElection: 2028 },
    ],
  },
  ID: {
    governor: { name: "Brad Little", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Jim Risch", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Mike Crapo", party: "R", nextElection: 2028 },
    ],
  },
  IL: {
    governor: { name: "JB Pritzker", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Dick Durbin", party: "D", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Tammy Duckworth", party: "D", nextElection: 2028 },
    ],
  },
  IN: {
    governor: { name: "Mike Braun", party: "R", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Jim Banks", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Todd Young", party: "R", nextElection: 2028 },
    ],
  },
  KS: {
    governor: { name: "Laura Kelly", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Roger Marshall", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Jerry Moran", party: "R", nextElection: 2028 },
    ],
  },
  KY: {
    governor: { name: "Andy Beshear", party: "D", nextElection: 2027, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Mitch McConnell", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Rand Paul", party: "R", nextElection: 2028 },
    ],
  },
  LA: {
    governor: { name: "Jeff Landry", party: "R", nextElection: 2027, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Bill Cassidy", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "John Kennedy", party: "R", nextElection: 2028 },
    ],
  },
  MA: {
    governor: { name: "Maura Healey", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Elizabeth Warren", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Ed Markey", party: "D", nextElection: 2026 },
    ],
  },
  MD: {
    governor: { name: "Wes Moore", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Angela Alsobrooks", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Chris Van Hollen", party: "D", nextElection: 2028 },
    ],
  },
  ME: {
    governor: { name: "Janet Mills", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Angus King", party: "I", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Susan Collins", party: "R", nextElection: 2026 },
    ],
  },
  MI: {
    governor: { name: "Gretchen Whitmer", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Elissa Slotkin", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Gary Peters", party: "D", nextElection: 2026 },
    ],
  },
  MN: {
    governor: { name: "Tim Walz", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Amy Klobuchar", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Tina Smith", party: "D", nextElection: 2026 },
    ],
  },
  MO: {
    governor: { name: "Mike Kehoe", party: "R", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Josh Hawley", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Eric Schmitt", party: "R", nextElection: 2028 },
    ],
  },
  MS: {
    governor: { name: "Tate Reeves", party: "R", nextElection: 2027, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Roger Wicker", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Cindy Hyde-Smith", party: "R", nextElection: 2026 },
    ],
  },
  MT: {
    governor: { name: "Greg Gianforte", party: "R", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Tim Sheehy", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Steve Daines", party: "R", nextElection: 2026 },
    ],
  },
  NC: {
    governor: { name: "Josh Stein", party: "D", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Thom Tillis", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Ted Budd", party: "R", nextElection: 2028 },
    ],
  },
  ND: {
    governor: { name: "Kelly Armstrong", party: "R", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Kevin Cramer", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "John Hoeven", party: "R", nextElection: 2028 },
    ],
  },
  NE: {
    governor: { name: "Jim Pillen", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Deb Fischer", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Pete Ricketts", party: "R", nextElection: 2026 },
    ],
  },
  NH: {
    governor: { name: "Kelly Ayotte", party: "R", nextElection: 2026, termYears: 2 },
    senators: [
      { seat: 1, seatClass: 2, name: "Jeanne Shaheen", party: "D", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Maggie Hassan", party: "D", nextElection: 2028 },
    ],
  },
  NJ: {
    governor: { name: "Mikie Sherill", party: "D", nextElection: 2029, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Andy Kim", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Cory Booker", party: "D", nextElection: 2026 },
    ],
  },
  NM: {
    governor: { name: "Michelle Lujan Grisham", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Martin Heinrich", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Ben Ray Luján", party: "D", nextElection: 2026 },
    ],
  },
  NV: {
    governor: { name: "Joe Lombardo", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Jacky Rosen", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Catherine Cortez Masto", party: "D", nextElection: 2028 },
    ],
  },
  NY: {
    governor: { name: "Kathy Hochul", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Kirsten Gillibrand", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Chuck Schumer", party: "D", nextElection: 2028 },
    ],
  },
  OH: {
    governor: { name: "Mike DeWine", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Bernie Moreno", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Jon Husted", party: "R", nextElection: 2026 },
    ],
  },
  OK: {
    governor: { name: "Kevin Stitt", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Markwayne Mullin", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "James Lankford", party: "R", nextElection: 2028 },
    ],
  },
  OR: {
    governor: { name: "Tina Kotek", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Jeff Merkley", party: "D", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Ron Wyden", party: "D", nextElection: 2028 },
    ],
  },
  PA: {
    governor: { name: "Josh Shapiro", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "David McCormick", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "John Fetterman", party: "D", nextElection: 2028 },
    ],
  },
  RI: {
    governor: { name: "Dan McKee", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Sheldon Whitehouse", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Jack Reed", party: "D", nextElection: 2026 },
    ],
  },
  SC: {
    governor: { name: "Henry McMaster", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Darline Graham", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "Tim Scott", party: "R", nextElection: 2028 },
    ],
  },
  SD: {
    governor: { name: "Larry Rhoden", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 2, name: "Mike Rounds", party: "R", nextElection: 2026 },
      { seat: 2, seatClass: 3, name: "John Thune", party: "R", nextElection: 2028 },
    ],
  },
  TN: {
    governor: { name: "Bill Lee", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Marsha Blackburn", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Bill Hagerty", party: "R", nextElection: 2026 },
    ],
  },
  TX: {
    governor: { name: "Greg Abbott", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Ted Cruz", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "John Cornyn", party: "R", nextElection: 2026 },
    ],
  },
  UT: {
    governor: { name: "Spencer Cox", party: "R", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "John Curtis", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Mike Lee", party: "R", nextElection: 2028 },
    ],
  },
  VA: {
    governor: { name: "Abigail Spanberger", party: "D", nextElection: 2029, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Tim Kaine", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Mark Warner", party: "D", nextElection: 2026 },
    ],
  },
  VT: {
    governor: { name: "Phil Scott", party: "R", nextElection: 2026, termYears: 2 },
    senators: [
      { seat: 1, seatClass: 1, name: "Bernie Sanders", party: "I", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Peter Welch", party: "D", nextElection: 2028 },
    ],
  },
  WA: {
    governor: { name: "Bob Ferguson", party: "D", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Maria Cantwell", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Patty Murray", party: "D", nextElection: 2028 },
    ],
  },
  WI: {
    governor: { name: "Tony Evers", party: "D", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Tammy Baldwin", party: "D", nextElection: 2030 },
      { seat: 2, seatClass: 3, name: "Ron Johnson", party: "R", nextElection: 2028 },
    ],
  },
  WV: {
    governor: { name: "Patrick Morrisey", party: "R", nextElection: 2028, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "Jim Justice", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Shelley Moore Capito", party: "R", nextElection: 2026 },
    ],
  },
  WY: {
    governor: { name: "Mark Gordon", party: "R", nextElection: 2026, termYears: 4 },
    senators: [
      { seat: 1, seatClass: 1, name: "John Barrasso", party: "R", nextElection: 2030 },
      { seat: 2, seatClass: 2, name: "Cynthia Lummis", party: "R", nextElection: 2026 },
    ],
  },
};
