// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/hd31_2016.csv
// NOTE: "pres" field stores 2016 President results (Clinton vs Trump).

import type { OH31Precinct } from "@/data/oh31PrecinctData";

export const oh31PrecinctData2016: OH31Precinct[] = [
  {
    "precinct": "BARBERTON 1-A",
    "township": "Barberton",
    "ballotsCast": 547,
    "regVoters": 845,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 197,
      "rVotes": 314,
      "total": 541,
      "dPct": 36.4,
      "rPct": 58
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 170,
      "rVotes": 319,
      "total": 525,
      "dPct": 32.4,
      "rPct": 60.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 274,
      "rVotes": 237,
      "total": 511,
      "dPct": 53.6,
      "rPct": 46.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 229,
      "rVotes": 261,
      "total": 490,
      "dPct": 46.7,
      "rPct": 53.3
    }
  },
  {
    "precinct": "BARBERTON 1-B",
    "township": "Barberton",
    "ballotsCast": 516,
    "regVoters": 854,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 223,
      "rVotes": 258,
      "total": 509,
      "dPct": 43.8,
      "rPct": 50.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 209,
      "rVotes": 226,
      "total": 489,
      "dPct": 42.7,
      "rPct": 46.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 290,
      "rVotes": 190,
      "total": 480,
      "dPct": 60.4,
      "rPct": 39.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 209,
      "total": 472,
      "dPct": 55.7,
      "rPct": 44.3
    }
  },
  {
    "precinct": "BARBERTON 1-C",
    "township": "Barberton",
    "ballotsCast": 556,
    "regVoters": 830,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 224,
      "rVotes": 300,
      "total": 545,
      "dPct": 41.1,
      "rPct": 55
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 218,
      "rVotes": 270,
      "total": 522,
      "dPct": 41.8,
      "rPct": 51.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 297,
      "rVotes": 211,
      "total": 508,
      "dPct": 58.5,
      "rPct": 41.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 262,
      "rVotes": 236,
      "total": 498,
      "dPct": 52.6,
      "rPct": 47.4
    }
  },
  {
    "precinct": "BARBERTON 2-A",
    "township": "Barberton",
    "ballotsCast": 620,
    "regVoters": 917,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 267,
      "rVotes": 298,
      "total": 607,
      "dPct": 44,
      "rPct": 49.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 235,
      "rVotes": 307,
      "total": 578,
      "dPct": 40.7,
      "rPct": 53.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 338,
      "rVotes": 213,
      "total": 551,
      "dPct": 61.3,
      "rPct": 38.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 287,
      "rVotes": 234,
      "total": 521,
      "dPct": 55.1,
      "rPct": 44.9
    }
  },
  {
    "precinct": "BARBERTON 2-B",
    "township": "Barberton",
    "ballotsCast": 679,
    "regVoters": 877,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 289,
      "rVotes": 340,
      "total": 660,
      "dPct": 43.8,
      "rPct": 51.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 249,
      "rVotes": 355,
      "total": 649,
      "dPct": 38.4,
      "rPct": 54.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 373,
      "rVotes": 256,
      "total": 629,
      "dPct": 59.3,
      "rPct": 40.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 315,
      "rVotes": 290,
      "total": 605,
      "dPct": 52.1,
      "rPct": 47.9
    }
  },
  {
    "precinct": "BARBERTON 2-C",
    "township": "Barberton",
    "ballotsCast": 546,
    "regVoters": 864,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 256,
      "rVotes": 259,
      "total": 535,
      "dPct": 47.9,
      "rPct": 48.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 224,
      "rVotes": 240,
      "total": 508,
      "dPct": 44.1,
      "rPct": 47.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 316,
      "rVotes": 183,
      "total": 499,
      "dPct": 63.3,
      "rPct": 36.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 273,
      "rVotes": 218,
      "total": 491,
      "dPct": 55.6,
      "rPct": 44.4
    }
  },
  {
    "precinct": "BARBERTON 3-A",
    "township": "Barberton",
    "ballotsCast": 591,
    "regVoters": 955,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 437,
      "rVotes": 125,
      "total": 582,
      "dPct": 75.1,
      "rPct": 21.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 407,
      "rVotes": 125,
      "total": 562,
      "dPct": 72.4,
      "rPct": 22.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 451,
      "rVotes": 103,
      "total": 554,
      "dPct": 81.4,
      "rPct": 18.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 430,
      "rVotes": 117,
      "total": 547,
      "dPct": 78.6,
      "rPct": 21.4
    }
  },
  {
    "precinct": "BARBERTON 3-B",
    "township": "Barberton",
    "ballotsCast": 647,
    "regVoters": 931,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 374,
      "rVotes": 242,
      "total": 634,
      "dPct": 59,
      "rPct": 38.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 326,
      "rVotes": 262,
      "total": 614,
      "dPct": 53.1,
      "rPct": 42.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 429,
      "rVotes": 182,
      "total": 611,
      "dPct": 70.2,
      "rPct": 29.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 394,
      "rVotes": 209,
      "total": 603,
      "dPct": 65.3,
      "rPct": 34.7
    }
  },
  {
    "precinct": "BARBERTON 3-C",
    "township": "Barberton",
    "ballotsCast": 792,
    "regVoters": 947,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 336,
      "rVotes": 411,
      "total": 774,
      "dPct": 43.4,
      "rPct": 53.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 282,
      "rVotes": 438,
      "total": 760,
      "dPct": 37.1,
      "rPct": 57.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 424,
      "rVotes": 306,
      "total": 730,
      "dPct": 58.1,
      "rPct": 41.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 370,
      "rVotes": 340,
      "total": 710,
      "dPct": 52.1,
      "rPct": 47.9
    }
  },
  {
    "precinct": "BARBERTON 4-A",
    "township": "Barberton",
    "ballotsCast": 367,
    "regVoters": 729,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 183,
      "rVotes": 143,
      "total": 352,
      "dPct": 52,
      "rPct": 40.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 159,
      "rVotes": 157,
      "total": 349,
      "dPct": 45.6,
      "rPct": 45
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 234,
      "rVotes": 110,
      "total": 344,
      "dPct": 68,
      "rPct": 32
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 206,
      "rVotes": 124,
      "total": 330,
      "dPct": 62.4,
      "rPct": 37.6
    }
  },
  {
    "precinct": "BARBERTON 4-B",
    "township": "Barberton",
    "ballotsCast": 422,
    "regVoters": 754,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 191,
      "rVotes": 194,
      "total": 415,
      "dPct": 46,
      "rPct": 46.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 188,
      "rVotes": 175,
      "total": 401,
      "dPct": 46.9,
      "rPct": 43.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 244,
      "rVotes": 152,
      "total": 396,
      "dPct": 61.6,
      "rPct": 38.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 227,
      "rVotes": 162,
      "total": 389,
      "dPct": 58.4,
      "rPct": 41.6
    }
  },
  {
    "precinct": "BARBERTON 4-C",
    "township": "Barberton",
    "ballotsCast": 513,
    "regVoters": 798,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 237,
      "rVotes": 242,
      "total": 499,
      "dPct": 47.5,
      "rPct": 48.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 203,
      "rVotes": 237,
      "total": 480,
      "dPct": 42.3,
      "rPct": 49.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 297,
      "rVotes": 173,
      "total": 470,
      "dPct": 63.2,
      "rPct": 36.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 264,
      "rVotes": 194,
      "total": 458,
      "dPct": 57.6,
      "rPct": 42.4
    }
  },
  {
    "precinct": "BARBERTON 5-A",
    "township": "Barberton",
    "ballotsCast": 520,
    "regVoters": 808,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 210,
      "rVotes": 278,
      "total": 514,
      "dPct": 40.9,
      "rPct": 54.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 201,
      "rVotes": 241,
      "total": 490,
      "dPct": 41,
      "rPct": 49.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 280,
      "rVotes": 203,
      "total": 483,
      "dPct": 58,
      "rPct": 42
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 253,
      "rVotes": 218,
      "total": 471,
      "dPct": 53.7,
      "rPct": 46.3
    }
  },
  {
    "precinct": "BARBERTON 5-B",
    "township": "Barberton",
    "ballotsCast": 525,
    "regVoters": 780,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 237,
      "rVotes": 249,
      "total": 516,
      "dPct": 45.9,
      "rPct": 48.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 206,
      "rVotes": 242,
      "total": 489,
      "dPct": 42.1,
      "rPct": 49.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 306,
      "rVotes": 172,
      "total": 478,
      "dPct": 64,
      "rPct": 36
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 265,
      "rVotes": 200,
      "total": 465,
      "dPct": 57,
      "rPct": 43
    }
  },
  {
    "precinct": "BARBERTON 5-C",
    "township": "Barberton",
    "ballotsCast": 481,
    "regVoters": 776,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 213,
      "rVotes": 230,
      "total": 470,
      "dPct": 45.3,
      "rPct": 48.9
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 185,
      "rVotes": 228,
      "total": 453,
      "dPct": 40.8,
      "rPct": 50.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 272,
      "rVotes": 162,
      "total": 434,
      "dPct": 62.7,
      "rPct": 37.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 232,
      "rVotes": 190,
      "total": 422,
      "dPct": 55,
      "rPct": 45
    }
  },
  {
    "precinct": "BARBERTON 6-A",
    "township": "Barberton",
    "ballotsCast": 594,
    "regVoters": 760,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 238,
      "rVotes": 330,
      "total": 587,
      "dPct": 40.5,
      "rPct": 56.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 202,
      "rVotes": 328,
      "total": 567,
      "dPct": 35.6,
      "rPct": 57.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 308,
      "rVotes": 248,
      "total": 556,
      "dPct": 55.4,
      "rPct": 44.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 259,
      "rVotes": 275,
      "total": 534,
      "dPct": 48.5,
      "rPct": 51.5
    }
  },
  {
    "precinct": "BARBERTON 6-B",
    "township": "Barberton",
    "ballotsCast": 438,
    "regVoters": 766,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 175,
      "rVotes": 229,
      "total": 433,
      "dPct": 40.4,
      "rPct": 52.9
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 176,
      "rVotes": 206,
      "total": 424,
      "dPct": 41.5,
      "rPct": 48.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 245,
      "rVotes": 164,
      "total": 409,
      "dPct": 59.9,
      "rPct": 40.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 215,
      "rVotes": 176,
      "total": 391,
      "dPct": 55,
      "rPct": 45
    }
  },
  {
    "precinct": "BARBERTON 6-C",
    "township": "Barberton",
    "ballotsCast": 570,
    "regVoters": 786,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 237,
      "rVotes": 297,
      "total": 560,
      "dPct": 42.3,
      "rPct": 53
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 199,
      "rVotes": 310,
      "total": 544,
      "dPct": 36.6,
      "rPct": 57
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 301,
      "rVotes": 235,
      "total": 536,
      "dPct": 56.2,
      "rPct": 43.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 273,
      "rVotes": 249,
      "total": 522,
      "dPct": 52.3,
      "rPct": 47.7
    }
  },
  {
    "precinct": "BATH TWP A",
    "township": "Bath",
    "ballotsCast": 815,
    "regVoters": 1023,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 323,
      "rVotes": 432,
      "total": 788,
      "dPct": 41,
      "rPct": 54.8
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 224,
      "rVotes": 538,
      "total": 780,
      "dPct": 28.7,
      "rPct": 69
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 260,
      "rVotes": 478,
      "total": 738,
      "dPct": 35.2,
      "rPct": 64.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 219,
      "rVotes": 533,
      "total": 752,
      "dPct": 29.1,
      "rPct": 70.9
    }
  },
  {
    "precinct": "BATH TWP B",
    "township": "Bath",
    "ballotsCast": 775,
    "regVoters": 916,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 270,
      "rVotes": 455,
      "total": 752,
      "dPct": 35.9,
      "rPct": 60.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 200,
      "rVotes": 518,
      "total": 741,
      "dPct": 27,
      "rPct": 69.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 232,
      "rVotes": 467,
      "total": 699,
      "dPct": 33.2,
      "rPct": 66.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 206,
      "rVotes": 505,
      "total": 711,
      "dPct": 29,
      "rPct": 71
    }
  },
  {
    "precinct": "BATH TWP C",
    "township": "Bath",
    "ballotsCast": 914,
    "regVoters": 1103,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 325,
      "rVotes": 505,
      "total": 878,
      "dPct": 37,
      "rPct": 57.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 237,
      "rVotes": 609,
      "total": 872,
      "dPct": 27.2,
      "rPct": 69.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 271,
      "rVotes": 558,
      "total": 829,
      "dPct": 32.7,
      "rPct": 67.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 216,
      "rVotes": 635,
      "total": 851,
      "dPct": 25.4,
      "rPct": 74.6
    }
  },
  {
    "precinct": "BATH TWP D",
    "township": "Bath",
    "ballotsCast": 789,
    "regVoters": 943,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 382,
      "rVotes": 354,
      "total": 765,
      "dPct": 49.9,
      "rPct": 46.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 273,
      "rVotes": 448,
      "total": 752,
      "dPct": 36.3,
      "rPct": 59.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 323,
      "rVotes": 380,
      "total": 703,
      "dPct": 45.9,
      "rPct": 54.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 283,
      "rVotes": 438,
      "total": 721,
      "dPct": 39.3,
      "rPct": 60.7
    }
  },
  {
    "precinct": "BATH TWP E",
    "township": "Bath",
    "ballotsCast": 797,
    "regVoters": 941,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 365,
      "rVotes": 382,
      "total": 777,
      "dPct": 47,
      "rPct": 49.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 260,
      "rVotes": 456,
      "total": 751,
      "dPct": 34.6,
      "rPct": 60.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 325,
      "rVotes": 399,
      "total": 724,
      "dPct": 44.9,
      "rPct": 55.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 265,
      "rVotes": 473,
      "total": 738,
      "dPct": 35.9,
      "rPct": 64.1
    }
  },
  {
    "precinct": "BATH TWP F",
    "township": "Bath",
    "ballotsCast": 757,
    "regVoters": 910,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 335,
      "rVotes": 371,
      "total": 731,
      "dPct": 45.8,
      "rPct": 50.8
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 248,
      "rVotes": 451,
      "total": 723,
      "dPct": 34.3,
      "rPct": 62.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 276,
      "rVotes": 405,
      "total": 681,
      "dPct": 40.5,
      "rPct": 59.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 244,
      "rVotes": 445,
      "total": 689,
      "dPct": 35.4,
      "rPct": 64.6
    }
  },
  {
    "precinct": "BATH TWP G",
    "township": "Bath",
    "ballotsCast": 892,
    "regVoters": 1036,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 352,
      "rVotes": 466,
      "total": 860,
      "dPct": 40.9,
      "rPct": 54.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 258,
      "rVotes": 555,
      "total": 857,
      "dPct": 30.1,
      "rPct": 64.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 296,
      "rVotes": 507,
      "total": 803,
      "dPct": 36.9,
      "rPct": 63.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 258,
      "rVotes": 545,
      "total": 803,
      "dPct": 32.1,
      "rPct": 67.9
    }
  },
  {
    "precinct": "BATH TWP H",
    "township": "Bath",
    "ballotsCast": 749,
    "regVoters": 899,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 418,
      "rVotes": 267,
      "total": 724,
      "dPct": 57.7,
      "rPct": 36.9
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 333,
      "rVotes": 365,
      "total": 723,
      "dPct": 46.1,
      "rPct": 50.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 427,
      "rVotes": 278,
      "total": 705,
      "dPct": 60.6,
      "rPct": 39.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 383,
      "rVotes": 297,
      "total": 680,
      "dPct": 56.3,
      "rPct": 43.7
    }
  },
  {
    "precinct": "BOSTON HTS VILL",
    "township": "Boston Heights",
    "ballotsCast": 847,
    "regVoters": 1048,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 317,
      "rVotes": 473,
      "total": 824,
      "dPct": 38.5,
      "rPct": 57.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 230,
      "rVotes": 546,
      "total": 810,
      "dPct": 28.4,
      "rPct": 67.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 253,
      "rVotes": 530,
      "total": 783,
      "dPct": 32.3,
      "rPct": 67.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 238,
      "rVotes": 524,
      "total": 762,
      "dPct": 31.2,
      "rPct": 68.8
    }
  },
  {
    "precinct": "BOSTON TWP",
    "township": "Boston Twp",
    "ballotsCast": 413,
    "regVoters": 532,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 190,
      "rVotes": 192,
      "total": 405,
      "dPct": 46.9,
      "rPct": 47.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 144,
      "rVotes": 215,
      "total": 391,
      "dPct": 36.8,
      "rPct": 55
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 183,
      "rVotes": 185,
      "total": 368,
      "dPct": 49.7,
      "rPct": 50.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 143,
      "rVotes": 233,
      "total": 376,
      "dPct": 38,
      "rPct": 62
    }
  },
  {
    "precinct": "COPLEY TWP A",
    "township": "Copley",
    "ballotsCast": 773,
    "regVoters": 1004,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 430,
      "rVotes": 301,
      "total": 752,
      "dPct": 57.2,
      "rPct": 40
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 364,
      "rVotes": 333,
      "total": 736,
      "dPct": 49.5,
      "rPct": 45.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 363,
      "rVotes": 338,
      "total": 701,
      "dPct": 51.8,
      "rPct": 48.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 371,
      "rVotes": 343,
      "total": 714,
      "dPct": 52,
      "rPct": 48
    }
  },
  {
    "precinct": "COPLEY TWP B",
    "township": "Copley",
    "ballotsCast": 693,
    "regVoters": 961,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 392,
      "rVotes": 257,
      "total": 673,
      "dPct": 58.2,
      "rPct": 38.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 349,
      "rVotes": 279,
      "total": 667,
      "dPct": 52.3,
      "rPct": 41.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 365,
      "rVotes": 282,
      "total": 647,
      "dPct": 56.4,
      "rPct": 43.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 361,
      "rVotes": 287,
      "total": 648,
      "dPct": 55.7,
      "rPct": 44.3
    }
  },
  {
    "precinct": "COPLEY TWP C",
    "township": "Copley",
    "ballotsCast": 742,
    "regVoters": 986,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 413,
      "rVotes": 280,
      "total": 723,
      "dPct": 57.1,
      "rPct": 38.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 360,
      "rVotes": 309,
      "total": 709,
      "dPct": 50.8,
      "rPct": 43.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 375,
      "rVotes": 307,
      "total": 682,
      "dPct": 55,
      "rPct": 45
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 378,
      "rVotes": 308,
      "total": 686,
      "dPct": 55.1,
      "rPct": 44.9
    }
  },
  {
    "precinct": "COPLEY TWP D",
    "township": "Copley",
    "ballotsCast": 754,
    "regVoters": 962,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 342,
      "rVotes": 373,
      "total": 742,
      "dPct": 46.1,
      "rPct": 50.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 286,
      "rVotes": 387,
      "total": 732,
      "dPct": 39.1,
      "rPct": 52.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 314,
      "rVotes": 374,
      "total": 688,
      "dPct": 45.6,
      "rPct": 54.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 309,
      "rVotes": 396,
      "total": 705,
      "dPct": 43.8,
      "rPct": 56.2
    }
  },
  {
    "precinct": "COPLEY TWP E",
    "township": "Copley",
    "ballotsCast": 810,
    "regVoters": 979,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 317,
      "rVotes": 436,
      "total": 788,
      "dPct": 40.2,
      "rPct": 55.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 255,
      "rVotes": 475,
      "total": 776,
      "dPct": 32.9,
      "rPct": 61.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 282,
      "rVotes": 474,
      "total": 756,
      "dPct": 37.3,
      "rPct": 62.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 268,
      "rVotes": 487,
      "total": 755,
      "dPct": 35.5,
      "rPct": 64.5
    }
  },
  {
    "precinct": "COPLEY TWP F",
    "township": "Copley",
    "ballotsCast": 846,
    "regVoters": 1036,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 403,
      "rVotes": 383,
      "total": 825,
      "dPct": 48.8,
      "rPct": 46.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 307,
      "rVotes": 464,
      "total": 797,
      "dPct": 38.5,
      "rPct": 58.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 306,
      "rVotes": 464,
      "total": 770,
      "dPct": 39.7,
      "rPct": 60.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 297,
      "rVotes": 468,
      "total": 765,
      "dPct": 38.8,
      "rPct": 61.2
    }
  },
  {
    "precinct": "COPLEY TWP G",
    "township": "Copley",
    "ballotsCast": 891,
    "regVoters": 1124,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 455,
      "rVotes": 378,
      "total": 871,
      "dPct": 52.2,
      "rPct": 43.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 342,
      "rVotes": 489,
      "total": 854,
      "dPct": 40,
      "rPct": 57.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 331,
      "rVotes": 493,
      "total": 824,
      "dPct": 40.2,
      "rPct": 59.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 345,
      "rVotes": 470,
      "total": 815,
      "dPct": 42.3,
      "rPct": 57.7
    }
  },
  {
    "precinct": "COPLEY TWP H",
    "township": "Copley",
    "ballotsCast": 751,
    "regVoters": 961,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 361,
      "rVotes": 332,
      "total": 727,
      "dPct": 49.7,
      "rPct": 45.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 262,
      "rVotes": 410,
      "total": 698,
      "dPct": 37.5,
      "rPct": 58.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 268,
      "rVotes": 400,
      "total": 668,
      "dPct": 40.1,
      "rPct": 59.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 271,
      "rVotes": 387,
      "total": 658,
      "dPct": 41.2,
      "rPct": 58.8
    }
  },
  {
    "precinct": "COPLEY TWP I",
    "township": "Copley",
    "ballotsCast": 706,
    "regVoters": 983,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 387,
      "rVotes": 282,
      "total": 689,
      "dPct": 56.2,
      "rPct": 40.9
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 304,
      "rVotes": 343,
      "total": 670,
      "dPct": 45.4,
      "rPct": 51.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 296,
      "rVotes": 341,
      "total": 637,
      "dPct": 46.5,
      "rPct": 53.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 292,
      "rVotes": 363,
      "total": 655,
      "dPct": 44.6,
      "rPct": 55.4
    }
  },
  {
    "precinct": "COPLEY TWP J",
    "township": "Copley",
    "ballotsCast": 849,
    "regVoters": 1055,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 358,
      "rVotes": 437,
      "total": 839,
      "dPct": 42.7,
      "rPct": 52.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 290,
      "rVotes": 493,
      "total": 813,
      "dPct": 35.7,
      "rPct": 60.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 286,
      "rVotes": 497,
      "total": 783,
      "dPct": 36.5,
      "rPct": 63.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 286,
      "rVotes": 506,
      "total": 792,
      "dPct": 36.1,
      "rPct": 63.9
    }
  },
  {
    "precinct": "COPLEY TWP K",
    "township": "Copley",
    "ballotsCast": 796,
    "regVoters": 970,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 378,
      "rVotes": 358,
      "total": 767,
      "dPct": 49.3,
      "rPct": 46.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 298,
      "rVotes": 446,
      "total": 768,
      "dPct": 38.8,
      "rPct": 58.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 442,
      "total": 731,
      "dPct": 39.5,
      "rPct": 60.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 296,
      "rVotes": 450,
      "total": 746,
      "dPct": 39.7,
      "rPct": 60.3
    }
  },
  {
    "precinct": "COPLEY TWP L",
    "township": "Copley",
    "ballotsCast": 815,
    "regVoters": 1011,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 413,
      "rVotes": 344,
      "total": 789,
      "dPct": 52.3,
      "rPct": 43.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 308,
      "rVotes": 452,
      "total": 778,
      "dPct": 39.6,
      "rPct": 58.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 318,
      "rVotes": 444,
      "total": 762,
      "dPct": 41.7,
      "rPct": 58.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 309,
      "rVotes": 440,
      "total": 749,
      "dPct": 41.3,
      "rPct": 58.7
    }
  },
  {
    "precinct": "CUY FALLS 1-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 742,
    "regVoters": 1026,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 397,
      "rVotes": 292,
      "total": 728,
      "dPct": 54.5,
      "rPct": 40.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 350,
      "rVotes": 302,
      "total": 701,
      "dPct": 49.9,
      "rPct": 43.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 450,
      "rVotes": 243,
      "total": 693,
      "dPct": 64.9,
      "rPct": 35.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 325,
      "rVotes": 366,
      "total": 691,
      "dPct": 47,
      "rPct": 53
    }
  },
  {
    "precinct": "CUY FALLS 1-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 699,
    "regVoters": 1080,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 399,
      "rVotes": 249,
      "total": 684,
      "dPct": 58.3,
      "rPct": 36.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 340,
      "rVotes": 277,
      "total": 646,
      "dPct": 52.6,
      "rPct": 42.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 441,
      "rVotes": 203,
      "total": 644,
      "dPct": 68.5,
      "rPct": 31.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 329,
      "rVotes": 305,
      "total": 634,
      "dPct": 51.9,
      "rPct": 48.1
    }
  },
  {
    "precinct": "CUY FALLS 1-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 694,
    "regVoters": 956,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 341,
      "rVotes": 299,
      "total": 685,
      "dPct": 49.8,
      "rPct": 43.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 290,
      "rVotes": 325,
      "total": 663,
      "dPct": 43.7,
      "rPct": 49
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 400,
      "rVotes": 245,
      "total": 645,
      "dPct": 62,
      "rPct": 38
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 285,
      "rVotes": 356,
      "total": 641,
      "dPct": 44.5,
      "rPct": 55.5
    }
  },
  {
    "precinct": "CUY FALLS 1-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 716,
    "regVoters": 958,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 322,
      "rVotes": 337,
      "total": 696,
      "dPct": 46.3,
      "rPct": 48.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 278,
      "rVotes": 350,
      "total": 684,
      "dPct": 40.6,
      "rPct": 51.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 376,
      "rVotes": 273,
      "total": 649,
      "dPct": 57.9,
      "rPct": 42.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 257,
      "rVotes": 397,
      "total": 654,
      "dPct": 39.3,
      "rPct": 60.7
    }
  },
  {
    "precinct": "CUY FALLS 2-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 579,
    "regVoters": 845,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 333,
      "rVotes": 209,
      "total": 570,
      "dPct": 58.4,
      "rPct": 36.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 270,
      "rVotes": 234,
      "total": 545,
      "dPct": 49.5,
      "rPct": 42.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 347,
      "rVotes": 181,
      "total": 528,
      "dPct": 65.7,
      "rPct": 34.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 265,
      "rVotes": 261,
      "total": 526,
      "dPct": 50.4,
      "rPct": 49.6
    }
  },
  {
    "precinct": "CUY FALLS 2-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 595,
    "regVoters": 805,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 318,
      "rVotes": 230,
      "total": 578,
      "dPct": 55,
      "rPct": 39.8
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 253,
      "rVotes": 247,
      "total": 548,
      "dPct": 46.2,
      "rPct": 45.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 351,
      "rVotes": 177,
      "total": 528,
      "dPct": 66.5,
      "rPct": 33.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 250,
      "rVotes": 279,
      "total": 529,
      "dPct": 47.3,
      "rPct": 52.7
    }
  },
  {
    "precinct": "CUY FALLS 2-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 610,
    "regVoters": 792,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 317,
      "rVotes": 247,
      "total": 599,
      "dPct": 52.9,
      "rPct": 41.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 232,
      "rVotes": 299,
      "total": 570,
      "dPct": 40.7,
      "rPct": 52.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 334,
      "rVotes": 220,
      "total": 554,
      "dPct": 60.3,
      "rPct": 39.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 213,
      "rVotes": 342,
      "total": 555,
      "dPct": 38.4,
      "rPct": 61.6
    }
  },
  {
    "precinct": "CUY FALLS 2-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 615,
    "regVoters": 811,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 305,
      "rVotes": 262,
      "total": 605,
      "dPct": 50.4,
      "rPct": 43.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 257,
      "rVotes": 289,
      "total": 578,
      "dPct": 44.5,
      "rPct": 50
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 347,
      "rVotes": 204,
      "total": 551,
      "dPct": 63,
      "rPct": 37
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 227,
      "rVotes": 325,
      "total": 552,
      "dPct": 41.1,
      "rPct": 58.9
    }
  },
  {
    "precinct": "CUY FALLS 2-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 558,
    "regVoters": 762,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 275,
      "rVotes": 235,
      "total": 544,
      "dPct": 50.6,
      "rPct": 43.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 226,
      "rVotes": 261,
      "total": 528,
      "dPct": 42.8,
      "rPct": 49.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 314,
      "rVotes": 205,
      "total": 519,
      "dPct": 60.5,
      "rPct": 39.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 204,
      "rVotes": 307,
      "total": 511,
      "dPct": 39.9,
      "rPct": 60.1
    }
  },
  {
    "precinct": "CUY FALLS 3-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 629,
    "regVoters": 810,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 286,
      "rVotes": 294,
      "total": 613,
      "dPct": 46.7,
      "rPct": 48
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 258,
      "rVotes": 309,
      "total": 601,
      "dPct": 42.9,
      "rPct": 51.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 154,
      "total": 424,
      "dPct": 63.7,
      "rPct": 36.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 234,
      "rVotes": 334,
      "total": 568,
      "dPct": 41.2,
      "rPct": 58.8
    }
  },
  {
    "precinct": "CUY FALLS 3-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 672,
    "regVoters": 824,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 349,
      "rVotes": 275,
      "total": 657,
      "dPct": 53.1,
      "rPct": 41.9
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 279,
      "rVotes": 327,
      "total": 639,
      "dPct": 43.7,
      "rPct": 51.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 373,
      "rVotes": 243,
      "total": 616,
      "dPct": 60.6,
      "rPct": 39.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 264,
      "rVotes": 357,
      "total": 621,
      "dPct": 42.5,
      "rPct": 57.5
    }
  },
  {
    "precinct": "CUY FALLS 3-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 711,
    "regVoters": 892,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 348,
      "rVotes": 312,
      "total": 691,
      "dPct": 50.4,
      "rPct": 45.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 280,
      "rVotes": 352,
      "total": 675,
      "dPct": 41.5,
      "rPct": 52.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 399,
      "rVotes": 261,
      "total": 660,
      "dPct": 60.5,
      "rPct": 39.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 414,
      "total": 644,
      "dPct": 35.7,
      "rPct": 64.3
    }
  },
  {
    "precinct": "CUY FALLS 3-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 662,
    "regVoters": 854,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 310,
      "rVotes": 302,
      "total": 638,
      "dPct": 48.6,
      "rPct": 47.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 252,
      "rVotes": 340,
      "total": 633,
      "dPct": 39.8,
      "rPct": 53.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 352,
      "rVotes": 263,
      "total": 615,
      "dPct": 57.2,
      "rPct": 42.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 387,
      "total": 617,
      "dPct": 37.3,
      "rPct": 62.7
    }
  },
  {
    "precinct": "CUY FALLS 3-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 675,
    "regVoters": 881,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 335,
      "rVotes": 295,
      "total": 665,
      "dPct": 50.4,
      "rPct": 44.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 278,
      "rVotes": 329,
      "total": 650,
      "dPct": 42.8,
      "rPct": 50.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 377,
      "rVotes": 247,
      "total": 624,
      "dPct": 60.4,
      "rPct": 39.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 260,
      "rVotes": 373,
      "total": 633,
      "dPct": 41.1,
      "rPct": 58.9
    }
  },
  {
    "precinct": "CUY FALLS 4-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 465,
    "regVoters": 740,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 257,
      "rVotes": 172,
      "total": 459,
      "dPct": 56,
      "rPct": 37.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 241,
      "rVotes": 170,
      "total": 444,
      "dPct": 54.3,
      "rPct": 38.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 291,
      "rVotes": 138,
      "total": 429,
      "dPct": 67.8,
      "rPct": 32.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 226,
      "rVotes": 201,
      "total": 427,
      "dPct": 52.9,
      "rPct": 47.1
    }
  },
  {
    "precinct": "CUY FALLS 4-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 625,
    "regVoters": 822,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 316,
      "rVotes": 266,
      "total": 606,
      "dPct": 52.1,
      "rPct": 43.9
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 275,
      "rVotes": 265,
      "total": 584,
      "dPct": 47.1,
      "rPct": 45.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 373,
      "rVotes": 203,
      "total": 576,
      "dPct": 64.8,
      "rPct": 35.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 266,
      "rVotes": 307,
      "total": 573,
      "dPct": 46.4,
      "rPct": 53.6
    }
  },
  {
    "precinct": "CUY FALLS 4-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 652,
    "regVoters": 839,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 329,
      "rVotes": 264,
      "total": 635,
      "dPct": 51.8,
      "rPct": 41.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 288,
      "rVotes": 285,
      "total": 616,
      "dPct": 46.8,
      "rPct": 46.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 396,
      "rVotes": 203,
      "total": 599,
      "dPct": 66.1,
      "rPct": 33.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 329,
      "total": 592,
      "dPct": 44.4,
      "rPct": 55.6
    }
  },
  {
    "precinct": "CUY FALLS 4-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 637,
    "regVoters": 854,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 336,
      "rVotes": 246,
      "total": 612,
      "dPct": 54.9,
      "rPct": 40.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 272,
      "rVotes": 300,
      "total": 609,
      "dPct": 44.7,
      "rPct": 49.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 388,
      "rVotes": 206,
      "total": 594,
      "dPct": 65.3,
      "rPct": 34.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 267,
      "rVotes": 324,
      "total": 591,
      "dPct": 45.2,
      "rPct": 54.8
    }
  },
  {
    "precinct": "CUY FALLS 4-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 621,
    "regVoters": 811,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 285,
      "rVotes": 272,
      "total": 600,
      "dPct": 47.5,
      "rPct": 45.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 240,
      "rVotes": 303,
      "total": 577,
      "dPct": 41.6,
      "rPct": 52.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 339,
      "rVotes": 214,
      "total": 553,
      "dPct": 61.3,
      "rPct": 38.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 223,
      "rVotes": 332,
      "total": 555,
      "dPct": 40.2,
      "rPct": 59.8
    }
  },
  {
    "precinct": "CUY FALLS 5-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 465,
    "regVoters": 804,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 261,
      "rVotes": 164,
      "total": 454,
      "dPct": 57.5,
      "rPct": 36.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 246,
      "rVotes": 162,
      "total": 441,
      "dPct": 55.8,
      "rPct": 36.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 159,
      "total": 429,
      "dPct": 62.9,
      "rPct": 37.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 258,
      "rVotes": 170,
      "total": 428,
      "dPct": 60.3,
      "rPct": 39.7
    }
  },
  {
    "precinct": "CUY FALLS 5-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 677,
    "regVoters": 805,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 322,
      "rVotes": 303,
      "total": 647,
      "dPct": 49.8,
      "rPct": 46.8
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 255,
      "rVotes": 361,
      "total": 634,
      "dPct": 40.2,
      "rPct": 56.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 271,
      "rVotes": 337,
      "total": 608,
      "dPct": 44.6,
      "rPct": 55.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 189,
      "rVotes": 397,
      "total": 586,
      "dPct": 32.3,
      "rPct": 67.7
    }
  },
  {
    "precinct": "CUY FALLS 5-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 690,
    "regVoters": 912,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 363,
      "rVotes": 281,
      "total": 667,
      "dPct": 54.4,
      "rPct": 42.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 300,
      "rVotes": 324,
      "total": 660,
      "dPct": 45.5,
      "rPct": 49.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 425,
      "rVotes": 231,
      "total": 656,
      "dPct": 64.8,
      "rPct": 35.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 276,
      "rVotes": 369,
      "total": 645,
      "dPct": 42.8,
      "rPct": 57.2
    }
  },
  {
    "precinct": "CUY FALLS 5-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 676,
    "regVoters": 842,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 327,
      "rVotes": 290,
      "total": 664,
      "dPct": 49.2,
      "rPct": 43.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 246,
      "rVotes": 344,
      "total": 630,
      "dPct": 39,
      "rPct": 54.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 388,
      "rVotes": 231,
      "total": 619,
      "dPct": 62.7,
      "rPct": 37.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 248,
      "rVotes": 368,
      "total": 616,
      "dPct": 40.3,
      "rPct": 59.7
    }
  },
  {
    "precinct": "CUY FALLS 5-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 501,
    "regVoters": 757,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 295,
      "rVotes": 170,
      "total": 488,
      "dPct": 60.5,
      "rPct": 34.8
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 250,
      "rVotes": 187,
      "total": 469,
      "dPct": 53.3,
      "rPct": 39.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 131,
      "rVotes": 68,
      "total": 199,
      "dPct": 65.8,
      "rPct": 34.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 249,
      "rVotes": 206,
      "total": 455,
      "dPct": 54.7,
      "rPct": 45.3
    }
  },
  {
    "precinct": "CUY FALLS 6-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 636,
    "regVoters": 809,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 294,
      "rVotes": 302,
      "total": 620,
      "dPct": 47.4,
      "rPct": 48.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 242,
      "rVotes": 325,
      "total": 600,
      "dPct": 40.3,
      "rPct": 54.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 348,
      "rVotes": 235,
      "total": 583,
      "dPct": 59.7,
      "rPct": 40.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 210,
      "rVotes": 370,
      "total": 580,
      "dPct": 36.2,
      "rPct": 63.8
    }
  },
  {
    "precinct": "CUY FALLS 6-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 639,
    "regVoters": 836,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 290,
      "rVotes": 304,
      "total": 621,
      "dPct": 46.7,
      "rPct": 49
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 256,
      "rVotes": 318,
      "total": 608,
      "dPct": 42.1,
      "rPct": 52.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 345,
      "rVotes": 237,
      "total": 582,
      "dPct": 59.3,
      "rPct": 40.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 216,
      "rVotes": 382,
      "total": 598,
      "dPct": 36.1,
      "rPct": 63.9
    }
  },
  {
    "precinct": "CUY FALLS 6-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 598,
    "regVoters": 807,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 287,
      "rVotes": 261,
      "total": 585,
      "dPct": 49.1,
      "rPct": 44.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 250,
      "rVotes": 285,
      "total": 574,
      "dPct": 43.6,
      "rPct": 49.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 361,
      "rVotes": 198,
      "total": 559,
      "dPct": 64.6,
      "rPct": 35.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 227,
      "rVotes": 319,
      "total": 546,
      "dPct": 41.6,
      "rPct": 58.4
    }
  },
  {
    "precinct": "CUY FALLS 6-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 572,
    "regVoters": 749,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 276,
      "rVotes": 249,
      "total": 564,
      "dPct": 48.9,
      "rPct": 44.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 256,
      "rVotes": 270,
      "total": 556,
      "dPct": 46,
      "rPct": 48.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 342,
      "rVotes": 201,
      "total": 543,
      "dPct": 63,
      "rPct": 37
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 239,
      "rVotes": 297,
      "total": 536,
      "dPct": 44.6,
      "rPct": 55.4
    }
  },
  {
    "precinct": "CUY FALLS 6-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 604,
    "regVoters": 775,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 287,
      "rVotes": 262,
      "total": 586,
      "dPct": 49,
      "rPct": 44.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 254,
      "rVotes": 269,
      "total": 572,
      "dPct": 44.4,
      "rPct": 47
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 334,
      "rVotes": 215,
      "total": 549,
      "dPct": 60.8,
      "rPct": 39.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 218,
      "rVotes": 335,
      "total": 553,
      "dPct": 39.4,
      "rPct": 60.6
    }
  },
  {
    "precinct": "CUY FALLS 7-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 644,
    "regVoters": 824,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 324,
      "rVotes": 272,
      "total": 628,
      "dPct": 51.6,
      "rPct": 43.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 291,
      "rVotes": 297,
      "total": 617,
      "dPct": 47.2,
      "rPct": 48.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 364,
      "rVotes": 225,
      "total": 589,
      "dPct": 61.8,
      "rPct": 38.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 250,
      "rVotes": 335,
      "total": 585,
      "dPct": 42.7,
      "rPct": 57.3
    }
  },
  {
    "precinct": "CUY FALLS 7-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 509,
    "regVoters": 819,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 241,
      "rVotes": 225,
      "total": 494,
      "dPct": 48.8,
      "rPct": 45.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 196,
      "rVotes": 235,
      "total": 469,
      "dPct": 41.8,
      "rPct": 50.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 285,
      "rVotes": 169,
      "total": 454,
      "dPct": 62.8,
      "rPct": 37.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 188,
      "rVotes": 270,
      "total": 458,
      "dPct": 41,
      "rPct": 59
    }
  },
  {
    "precinct": "CUY FALLS 7-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 524,
    "regVoters": 641,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 242,
      "rVotes": 247,
      "total": 510,
      "dPct": 47.5,
      "rPct": 48.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 190,
      "rVotes": 283,
      "total": 492,
      "dPct": 38.6,
      "rPct": 57.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 217,
      "rVotes": 248,
      "total": 465,
      "dPct": 46.7,
      "rPct": 53.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 179,
      "rVotes": 295,
      "total": 474,
      "dPct": 37.8,
      "rPct": 62.2
    }
  },
  {
    "precinct": "CUY FALLS 7-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 617,
    "regVoters": 824,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 291,
      "rVotes": 286,
      "total": 602,
      "dPct": 48.3,
      "rPct": 47.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 252,
      "rVotes": 288,
      "total": 585,
      "dPct": 43.1,
      "rPct": 49.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 350,
      "rVotes": 212,
      "total": 562,
      "dPct": 62.3,
      "rPct": 37.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 315,
      "total": 545,
      "dPct": 42.2,
      "rPct": 57.8
    }
  },
  {
    "precinct": "CUY FALLS 7-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 607,
    "regVoters": 803,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 269,
      "rVotes": 273,
      "total": 591,
      "dPct": 45.5,
      "rPct": 46.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 222,
      "rVotes": 312,
      "total": 581,
      "dPct": 38.2,
      "rPct": 53.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 325,
      "rVotes": 231,
      "total": 556,
      "dPct": 58.5,
      "rPct": 41.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 216,
      "rVotes": 339,
      "total": 555,
      "dPct": 38.9,
      "rPct": 61.1
    }
  },
  {
    "precinct": "CUY FALLS 8-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 785,
    "regVoters": 953,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 291,
      "rVotes": 440,
      "total": 764,
      "dPct": 38.1,
      "rPct": 57.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 245,
      "rVotes": 450,
      "total": 736,
      "dPct": 33.3,
      "rPct": 61.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 255,
      "rVotes": 434,
      "total": 689,
      "dPct": 37,
      "rPct": 63
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 272,
      "rVotes": 432,
      "total": 704,
      "dPct": 38.6,
      "rPct": 61.4
    }
  },
  {
    "precinct": "CUY FALLS 8-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 671,
    "regVoters": 896,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 304,
      "rVotes": 315,
      "total": 652,
      "dPct": 46.6,
      "rPct": 48.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 247,
      "rVotes": 339,
      "total": 636,
      "dPct": 38.8,
      "rPct": 53.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 143,
      "rVotes": 139,
      "total": 282,
      "dPct": 50.7,
      "rPct": 49.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 18,
      "rVotes": 6,
      "total": 24,
      "dPct": 75,
      "rPct": 25
    }
  },
  {
    "precinct": "CUY FALLS 8-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 821,
    "regVoters": 979,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 352,
      "rVotes": 416,
      "total": 794,
      "dPct": 44.3,
      "rPct": 52.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 290,
      "rVotes": 445,
      "total": 771,
      "dPct": 37.6,
      "rPct": 57.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 292,
      "rVotes": 446,
      "total": 738,
      "dPct": 39.6,
      "rPct": 60.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 296,
      "rVotes": 446,
      "total": 742,
      "dPct": 39.9,
      "rPct": 60.1
    }
  },
  {
    "precinct": "CUY FALLS 8-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 622,
    "regVoters": 756,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 269,
      "rVotes": 310,
      "total": 608,
      "dPct": 44.2,
      "rPct": 51
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 224,
      "rVotes": 341,
      "total": 588,
      "dPct": 38.1,
      "rPct": 58
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 295,
      "rVotes": 286,
      "total": 581,
      "dPct": 50.8,
      "rPct": 49.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 248,
      "rVotes": 329,
      "total": 577,
      "dPct": 43,
      "rPct": 57
    }
  },
  {
    "precinct": "CUY FALLS 8-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 921,
    "regVoters": 1087,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 361,
      "rVotes": 492,
      "total": 889,
      "dPct": 40.6,
      "rPct": 55.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 275,
      "rVotes": 579,
      "total": 875,
      "dPct": 31.4,
      "rPct": 66.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 279,
      "rVotes": 554,
      "total": 833,
      "dPct": 33.5,
      "rPct": 66.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 277,
      "rVotes": 563,
      "total": 840,
      "dPct": 33,
      "rPct": 67
    }
  },
  {
    "precinct": "CUY FALLS 8-F",
    "township": "Cuyahoga Falls",
    "ballotsCast": 436,
    "regVoters": 523,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 210,
      "rVotes": 199,
      "total": 427,
      "dPct": 49.2,
      "rPct": 46.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 169,
      "rVotes": 237,
      "total": 419,
      "dPct": 40.3,
      "rPct": 56.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 171,
      "rVotes": 223,
      "total": 394,
      "dPct": 43.4,
      "rPct": 56.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 141,
      "rVotes": 258,
      "total": 399,
      "dPct": 35.3,
      "rPct": 64.7
    }
  },
  {
    "precinct": "NORTON 1-A",
    "township": "Norton",
    "ballotsCast": 545,
    "regVoters": 667,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 184,
      "rVotes": 324,
      "total": 536,
      "dPct": 34.3,
      "rPct": 60.4
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 160,
      "rVotes": 303,
      "total": 502,
      "dPct": 31.9,
      "rPct": 60.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 165,
      "rVotes": 302,
      "total": 467,
      "dPct": 35.3,
      "rPct": 64.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 183,
      "rVotes": 297,
      "total": 480,
      "dPct": 38.1,
      "rPct": 61.9
    }
  },
  {
    "precinct": "NORTON 1-B",
    "township": "Norton",
    "ballotsCast": 528,
    "regVoters": 674,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 214,
      "rVotes": 295,
      "total": 521,
      "dPct": 41.1,
      "rPct": 56.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 171,
      "rVotes": 306,
      "total": 497,
      "dPct": 34.4,
      "rPct": 61.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 201,
      "rVotes": 274,
      "total": 475,
      "dPct": 42.3,
      "rPct": 57.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 202,
      "rVotes": 276,
      "total": 478,
      "dPct": 42.3,
      "rPct": 57.7
    }
  },
  {
    "precinct": "NORTON 1-C",
    "township": "Norton",
    "ballotsCast": 536,
    "regVoters": 696,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 143,
      "rVotes": 354,
      "total": 527,
      "dPct": 27.1,
      "rPct": 67.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 127,
      "rVotes": 348,
      "total": 511,
      "dPct": 24.9,
      "rPct": 68.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 142,
      "rVotes": 349,
      "total": 491,
      "dPct": 28.9,
      "rPct": 71.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 155,
      "rVotes": 348,
      "total": 503,
      "dPct": 30.8,
      "rPct": 69.2
    }
  },
  {
    "precinct": "NORTON 2-A",
    "township": "Norton",
    "ballotsCast": 567,
    "regVoters": 720,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 225,
      "rVotes": 297,
      "total": 553,
      "dPct": 40.7,
      "rPct": 53.7
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 208,
      "rVotes": 286,
      "total": 531,
      "dPct": 39.2,
      "rPct": 53.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 210,
      "rVotes": 296,
      "total": 506,
      "dPct": 41.5,
      "rPct": 58.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 225,
      "rVotes": 284,
      "total": 509,
      "dPct": 44.2,
      "rPct": 55.8
    }
  },
  {
    "precinct": "NORTON 2-B",
    "township": "Norton",
    "ballotsCast": 503,
    "regVoters": 626,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 199,
      "rVotes": 281,
      "total": 494,
      "dPct": 40.3,
      "rPct": 56.9
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 162,
      "rVotes": 293,
      "total": 477,
      "dPct": 34,
      "rPct": 61.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 159,
      "rVotes": 297,
      "total": 456,
      "dPct": 34.9,
      "rPct": 65.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 169,
      "rVotes": 289,
      "total": 458,
      "dPct": 36.9,
      "rPct": 63.1
    }
  },
  {
    "precinct": "NORTON 2-C",
    "township": "Norton",
    "ballotsCast": 507,
    "regVoters": 636,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 177,
      "rVotes": 309,
      "total": 497,
      "dPct": 35.6,
      "rPct": 62.2
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 146,
      "rVotes": 303,
      "total": 475,
      "dPct": 30.7,
      "rPct": 63.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 154,
      "rVotes": 313,
      "total": 467,
      "dPct": 33,
      "rPct": 67
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 158,
      "rVotes": 302,
      "total": 460,
      "dPct": 34.3,
      "rPct": 65.7
    }
  },
  {
    "precinct": "NORTON 3-A",
    "township": "Norton",
    "ballotsCast": 598,
    "regVoters": 729,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 193,
      "rVotes": 359,
      "total": 578,
      "dPct": 33.4,
      "rPct": 62.1
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 168,
      "rVotes": 363,
      "total": 564,
      "dPct": 29.8,
      "rPct": 64.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 180,
      "rVotes": 369,
      "total": 549,
      "dPct": 32.8,
      "rPct": 67.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 199,
      "rVotes": 335,
      "total": 534,
      "dPct": 37.3,
      "rPct": 62.7
    }
  },
  {
    "precinct": "NORTON 3-B",
    "township": "Norton",
    "ballotsCast": 503,
    "regVoters": 687,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 167,
      "rVotes": 303,
      "total": 489,
      "dPct": 34.2,
      "rPct": 62
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 157,
      "rVotes": 280,
      "total": 477,
      "dPct": 32.9,
      "rPct": 58.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 176,
      "rVotes": 273,
      "total": 449,
      "dPct": 39.2,
      "rPct": 60.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 187,
      "rVotes": 271,
      "total": 458,
      "dPct": 40.8,
      "rPct": 59.2
    }
  },
  {
    "precinct": "NORTON 3-C",
    "township": "Norton",
    "ballotsCast": 529,
    "regVoters": 668,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 210,
      "rVotes": 286,
      "total": 514,
      "dPct": 40.9,
      "rPct": 55.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 170,
      "rVotes": 305,
      "total": 507,
      "dPct": 33.5,
      "rPct": 60.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 171,
      "rVotes": 313,
      "total": 484,
      "dPct": 35.3,
      "rPct": 64.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 203,
      "rVotes": 295,
      "total": 498,
      "dPct": 40.8,
      "rPct": 59.2
    }
  },
  {
    "precinct": "NORTON 4-A",
    "township": "Norton",
    "ballotsCast": 684,
    "regVoters": 952,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 204,
      "rVotes": 446,
      "total": 673,
      "dPct": 30.3,
      "rPct": 66.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 180,
      "rVotes": 398,
      "total": 644,
      "dPct": 28,
      "rPct": 61.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 208,
      "rVotes": 393,
      "total": 601,
      "dPct": 34.6,
      "rPct": 65.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 196,
      "rVotes": 404,
      "total": 600,
      "dPct": 32.7,
      "rPct": 67.3
    }
  },
  {
    "precinct": "NORTON 4-B",
    "township": "Norton",
    "ballotsCast": 675,
    "regVoters": 925,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 247,
      "rVotes": 382,
      "total": 663,
      "dPct": 37.3,
      "rPct": 57.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 203,
      "rVotes": 389,
      "total": 641,
      "dPct": 31.7,
      "rPct": 60.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 238,
      "rVotes": 374,
      "total": 612,
      "dPct": 38.9,
      "rPct": 61.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 253,
      "rVotes": 364,
      "total": 617,
      "dPct": 41,
      "rPct": 59
    }
  },
  {
    "precinct": "PENINSULA VILL",
    "township": "Peninsula",
    "ballotsCast": 352,
    "regVoters": 433,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 198,
      "rVotes": 134,
      "total": 344,
      "dPct": 57.6,
      "rPct": 39
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 158,
      "rVotes": 144,
      "total": 323,
      "dPct": 48.9,
      "rPct": 44.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 205,
      "rVotes": 109,
      "total": 314,
      "dPct": 65.3,
      "rPct": 34.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 167,
      "rVotes": 151,
      "total": 318,
      "dPct": 52.5,
      "rPct": 47.5
    }
  },
  {
    "precinct": "RICHFIELD TWP Y",
    "township": "Richfield Township",
    "ballotsCast": 874,
    "regVoters": 1022,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 344,
      "rVotes": 472,
      "total": 846,
      "dPct": 40.7,
      "rPct": 55.8
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 240,
      "rVotes": 558,
      "total": 821,
      "dPct": 29.2,
      "rPct": 68
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 300,
      "rVotes": 482,
      "total": 782,
      "dPct": 38.4,
      "rPct": 61.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 232,
      "rVotes": 552,
      "total": 784,
      "dPct": 29.6,
      "rPct": 70.4
    }
  },
  {
    "precinct": "RICHFIELD TWP Z",
    "township": "Richfield Township",
    "ballotsCast": 825,
    "regVoters": 1030,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 287,
      "rVotes": 484,
      "total": 806,
      "dPct": 35.6,
      "rPct": 60
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 220,
      "rVotes": 511,
      "total": 788,
      "dPct": 27.9,
      "rPct": 64.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 273,
      "rVotes": 467,
      "total": 740,
      "dPct": 36.9,
      "rPct": 63.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 212,
      "rVotes": 519,
      "total": 731,
      "dPct": 29,
      "rPct": 71
    }
  },
  {
    "precinct": "RICHFIELD VILL A",
    "township": "Richfield Village",
    "ballotsCast": 736,
    "regVoters": 914,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 264,
      "rVotes": 424,
      "total": 725,
      "dPct": 36.4,
      "rPct": 58.5
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 219,
      "rVotes": 422,
      "total": 686,
      "dPct": 31.9,
      "rPct": 61.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 262,
      "rVotes": 381,
      "total": 643,
      "dPct": 40.7,
      "rPct": 59.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 212,
      "rVotes": 418,
      "total": 630,
      "dPct": 33.7,
      "rPct": 66.3
    }
  },
  {
    "precinct": "RICHFIELD VILL B",
    "township": "Richfield Village",
    "ballotsCast": 774,
    "regVoters": 921,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 269,
      "rVotes": 455,
      "total": 754,
      "dPct": 35.7,
      "rPct": 60.3
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 183,
      "rVotes": 515,
      "total": 726,
      "dPct": 25.2,
      "rPct": 70.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 225,
      "rVotes": 465,
      "total": 690,
      "dPct": 32.6,
      "rPct": 67.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 188,
      "rVotes": 496,
      "total": 684,
      "dPct": 27.5,
      "rPct": 72.5
    }
  },
  {
    "precinct": "RICHFIELD VILL C",
    "township": "Richfield Village",
    "ballotsCast": 768,
    "regVoters": 893,
    "pres": {
      "dName": "Clinton",
      "rName": "Trump",
      "dVotes": 305,
      "rVotes": 399,
      "total": 744,
      "dPct": 41,
      "rPct": 53.6
    },
    "senate": {
      "dName": "Strickland",
      "rName": "Portman",
      "dVotes": 249,
      "rVotes": 454,
      "total": 743,
      "dPct": 33.5,
      "rPct": 61.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 287,
      "rVotes": 408,
      "total": 695,
      "dPct": 41.3,
      "rPct": 58.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 255,
      "rVotes": 438,
      "total": 693,
      "dPct": 36.8,
      "rPct": 63.2
    }
  }
];

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct2016: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData2016.map(p => [p.precinct, p]));
