// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/hd31_2018.csv
// NOTE: "pres" field stores 2018 Governor results (Cordray vs DeWine).

import type { OH31Precinct } from "@/data/oh31PrecinctData";

export const oh31PrecinctData2018: OH31Precinct[] = [
  {
    "precinct": "BARBERTON 1-A",
    "township": "Barberton",
    "ballotsCast": 423,
    "regVoters": 871,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 197,
      "rVotes": 209,
      "total": 415,
      "dPct": 47.5,
      "rPct": 50.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 210,
      "rVotes": 203,
      "total": 413,
      "dPct": 50.8,
      "rPct": 49.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 206,
      "rVotes": 204,
      "total": 410,
      "dPct": 50.2,
      "rPct": 49.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 186,
      "total": 403,
      "dPct": 48.9,
      "rPct": 46.2
    }
  },
  {
    "precinct": "BARBERTON 1-B",
    "township": "Barberton",
    "ballotsCast": 381,
    "regVoters": 877,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 183,
      "rVotes": 169,
      "total": 368,
      "dPct": 49.7,
      "rPct": 45.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 206,
      "rVotes": 169,
      "total": 375,
      "dPct": 54.9,
      "rPct": 45.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 198,
      "rVotes": 170,
      "total": 368,
      "dPct": 53.8,
      "rPct": 46.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 185,
      "rVotes": 150,
      "total": 362,
      "dPct": 51.1,
      "rPct": 41.4
    }
  },
  {
    "precinct": "BARBERTON 1-C",
    "township": "Barberton",
    "ballotsCast": 447,
    "regVoters": 889,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 226,
      "rVotes": 191,
      "total": 438,
      "dPct": 51.6,
      "rPct": 43.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 246,
      "rVotes": 184,
      "total": 430,
      "dPct": 57.2,
      "rPct": 42.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 236,
      "rVotes": 193,
      "total": 429,
      "dPct": 55,
      "rPct": 45
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 211,
      "rVotes": 178,
      "total": 417,
      "dPct": 50.6,
      "rPct": 42.7
    }
  },
  {
    "precinct": "BARBERTON 2-A",
    "township": "Barberton",
    "ballotsCast": 467,
    "regVoters": 954,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 251,
      "rVotes": 189,
      "total": 459,
      "dPct": 54.7,
      "rPct": 41.2
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 291,
      "rVotes": 163,
      "total": 454,
      "dPct": 64.1,
      "rPct": 35.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 277,
      "rVotes": 167,
      "total": 444,
      "dPct": 62.4,
      "rPct": 37.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 241,
      "rVotes": 157,
      "total": 431,
      "dPct": 55.9,
      "rPct": 36.4
    }
  },
  {
    "precinct": "BARBERTON 2-B",
    "township": "Barberton",
    "ballotsCast": 531,
    "regVoters": 894,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 270,
      "rVotes": 233,
      "total": 517,
      "dPct": 52.2,
      "rPct": 45.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 318,
      "rVotes": 202,
      "total": 520,
      "dPct": 61.2,
      "rPct": 38.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 302,
      "rVotes": 206,
      "total": 508,
      "dPct": 59.4,
      "rPct": 40.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 265,
      "rVotes": 194,
      "total": 493,
      "dPct": 53.8,
      "rPct": 39.4
    }
  },
  {
    "precinct": "BARBERTON 2-C",
    "township": "Barberton",
    "ballotsCast": 407,
    "regVoters": 894,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 224,
      "rVotes": 161,
      "total": 397,
      "dPct": 56.4,
      "rPct": 40.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 242,
      "rVotes": 153,
      "total": 395,
      "dPct": 61.3,
      "rPct": 38.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 160,
      "total": 390,
      "dPct": 59,
      "rPct": 41
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 210,
      "rVotes": 152,
      "total": 383,
      "dPct": 54.8,
      "rPct": 39.7
    }
  },
  {
    "precinct": "BARBERTON 3-A",
    "township": "Barberton",
    "ballotsCast": 429,
    "regVoters": 1008,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 323,
      "rVotes": 89,
      "total": 421,
      "dPct": 76.7,
      "rPct": 21.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 335,
      "rVotes": 87,
      "total": 422,
      "dPct": 79.4,
      "rPct": 20.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 333,
      "rVotes": 87,
      "total": 420,
      "dPct": 79.3,
      "rPct": 20.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 317,
      "rVotes": 81,
      "total": 420,
      "dPct": 75.5,
      "rPct": 19.3
    }
  },
  {
    "precinct": "BARBERTON 3-B",
    "township": "Barberton",
    "ballotsCast": 519,
    "regVoters": 944,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 300,
      "rVotes": 188,
      "total": 504,
      "dPct": 59.5,
      "rPct": 37.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 354,
      "rVotes": 161,
      "total": 515,
      "dPct": 68.7,
      "rPct": 31.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 347,
      "rVotes": 164,
      "total": 511,
      "dPct": 67.9,
      "rPct": 32.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 320,
      "rVotes": 146,
      "total": 495,
      "dPct": 64.6,
      "rPct": 29.5
    }
  },
  {
    "precinct": "BARBERTON 3-C",
    "township": "Barberton",
    "ballotsCast": 692,
    "regVoters": 948,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 341,
      "rVotes": 336,
      "total": 684,
      "dPct": 49.9,
      "rPct": 49.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 379,
      "rVotes": 298,
      "total": 677,
      "dPct": 56,
      "rPct": 44
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 362,
      "rVotes": 308,
      "total": 670,
      "dPct": 54,
      "rPct": 46
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 328,
      "rVotes": 294,
      "total": 647,
      "dPct": 50.7,
      "rPct": 45.4
    }
  },
  {
    "precinct": "BARBERTON 4-A",
    "township": "Barberton",
    "ballotsCast": 266,
    "regVoters": 759,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 147,
      "rVotes": 104,
      "total": 261,
      "dPct": 56.3,
      "rPct": 39.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 155,
      "rVotes": 106,
      "total": 261,
      "dPct": 59.4,
      "rPct": 40.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 148,
      "rVotes": 108,
      "total": 256,
      "dPct": 57.8,
      "rPct": 42.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 136,
      "rVotes": 104,
      "total": 253,
      "dPct": 53.8,
      "rPct": 41.1
    }
  },
  {
    "precinct": "BARBERTON 4-B",
    "township": "Barberton",
    "ballotsCast": 319,
    "regVoters": 808,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 180,
      "rVotes": 116,
      "total": 315,
      "dPct": 57.1,
      "rPct": 36.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 193,
      "rVotes": 122,
      "total": 315,
      "dPct": 61.3,
      "rPct": 38.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 190,
      "rVotes": 123,
      "total": 313,
      "dPct": 60.7,
      "rPct": 39.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 178,
      "rVotes": 114,
      "total": 307,
      "dPct": 58,
      "rPct": 37.1
    }
  },
  {
    "precinct": "BARBERTON 4-C",
    "township": "Barberton",
    "ballotsCast": 394,
    "regVoters": 810,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 221,
      "rVotes": 156,
      "total": 389,
      "dPct": 56.8,
      "rPct": 40.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 235,
      "rVotes": 150,
      "total": 385,
      "dPct": 61,
      "rPct": 39
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 224,
      "rVotes": 160,
      "total": 384,
      "dPct": 58.3,
      "rPct": 41.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 151,
      "total": 374,
      "dPct": 52.7,
      "rPct": 40.4
    }
  },
  {
    "precinct": "BARBERTON 5-A",
    "township": "Barberton",
    "ballotsCast": 368,
    "regVoters": 835,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 179,
      "rVotes": 161,
      "total": 357,
      "dPct": 50.1,
      "rPct": 45.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 204,
      "rVotes": 155,
      "total": 359,
      "dPct": 56.8,
      "rPct": 43.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 200,
      "rVotes": 160,
      "total": 360,
      "dPct": 55.6,
      "rPct": 44.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 175,
      "rVotes": 142,
      "total": 351,
      "dPct": 49.9,
      "rPct": 40.5
    }
  },
  {
    "precinct": "BARBERTON 5-B",
    "township": "Barberton",
    "ballotsCast": 380,
    "regVoters": 802,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 203,
      "rVotes": 146,
      "total": 368,
      "dPct": 55.2,
      "rPct": 39.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 218,
      "rVotes": 145,
      "total": 363,
      "dPct": 60.1,
      "rPct": 39.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 201,
      "rVotes": 160,
      "total": 361,
      "dPct": 55.7,
      "rPct": 44.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 181,
      "rVotes": 143,
      "total": 353,
      "dPct": 51.3,
      "rPct": 40.5
    }
  },
  {
    "precinct": "BARBERTON 5-C",
    "township": "Barberton",
    "ballotsCast": 353,
    "regVoters": 802,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 186,
      "rVotes": 141,
      "total": 341,
      "dPct": 54.5,
      "rPct": 41.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 209,
      "rVotes": 139,
      "total": 348,
      "dPct": 60.1,
      "rPct": 39.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 201,
      "rVotes": 144,
      "total": 345,
      "dPct": 58.3,
      "rPct": 41.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 185,
      "rVotes": 138,
      "total": 339,
      "dPct": 54.6,
      "rPct": 40.7
    }
  },
  {
    "precinct": "BARBERTON 6-A",
    "township": "Barberton",
    "ballotsCast": 525,
    "regVoters": 788,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 258,
      "rVotes": 239,
      "total": 516,
      "dPct": 50,
      "rPct": 46.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 272,
      "rVotes": 242,
      "total": 514,
      "dPct": 52.9,
      "rPct": 47.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 261,
      "rVotes": 244,
      "total": 505,
      "dPct": 51.7,
      "rPct": 48.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 236,
      "rVotes": 220,
      "total": 481,
      "dPct": 49.1,
      "rPct": 45.7
    }
  },
  {
    "precinct": "BARBERTON 6-B",
    "township": "Barberton",
    "ballotsCast": 319,
    "regVoters": 784,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 157,
      "rVotes": 144,
      "total": 314,
      "dPct": 50,
      "rPct": 45.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 170,
      "rVotes": 145,
      "total": 315,
      "dPct": 54,
      "rPct": 46
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 169,
      "rVotes": 146,
      "total": 315,
      "dPct": 53.7,
      "rPct": 46.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 150,
      "rVotes": 134,
      "total": 305,
      "dPct": 49.2,
      "rPct": 43.9
    }
  },
  {
    "precinct": "BARBERTON 6-C",
    "township": "Barberton",
    "ballotsCast": 432,
    "regVoters": 828,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 229,
      "rVotes": 179,
      "total": 425,
      "dPct": 53.9,
      "rPct": 42.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 247,
      "rVotes": 177,
      "total": 424,
      "dPct": 58.3,
      "rPct": 41.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 238,
      "rVotes": 180,
      "total": 418,
      "dPct": 56.9,
      "rPct": 43.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 211,
      "rVotes": 163,
      "total": 406,
      "dPct": 52,
      "rPct": 40.1
    }
  },
  {
    "precinct": "BATH TWP A",
    "township": "Bath",
    "ballotsCast": 711,
    "regVoters": 1005,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 281,
      "rVotes": 409,
      "total": 700,
      "dPct": 40.1,
      "rPct": 58.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 326,
      "rVotes": 376,
      "total": 702,
      "dPct": 46.4,
      "rPct": 53.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 406,
      "total": 695,
      "dPct": 41.6,
      "rPct": 58.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 260,
      "rVotes": 431,
      "total": 691,
      "dPct": 37.6,
      "rPct": 62.4
    }
  },
  {
    "precinct": "BATH TWP B",
    "township": "Bath",
    "ballotsCast": 670,
    "regVoters": 949,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 265,
      "rVotes": 384,
      "total": 659,
      "dPct": 40.2,
      "rPct": 58.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 286,
      "rVotes": 377,
      "total": 663,
      "dPct": 43.1,
      "rPct": 56.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 262,
      "rVotes": 383,
      "total": 645,
      "dPct": 40.6,
      "rPct": 59.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 244,
      "rVotes": 407,
      "total": 651,
      "dPct": 37.5,
      "rPct": 62.5
    }
  },
  {
    "precinct": "BATH TWP C",
    "township": "Bath",
    "ballotsCast": 772,
    "regVoters": 1149,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 273,
      "rVotes": 474,
      "total": 760,
      "dPct": 35.9,
      "rPct": 62.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 313,
      "rVotes": 447,
      "total": 760,
      "dPct": 41.2,
      "rPct": 58.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 460,
      "total": 749,
      "dPct": 38.6,
      "rPct": 61.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 243,
      "rVotes": 504,
      "total": 747,
      "dPct": 32.5,
      "rPct": 67.5
    }
  },
  {
    "precinct": "BATH TWP D",
    "township": "Bath",
    "ballotsCast": 679,
    "regVoters": 943,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 341,
      "rVotes": 315,
      "total": 667,
      "dPct": 51.1,
      "rPct": 47.2
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 380,
      "rVotes": 291,
      "total": 671,
      "dPct": 56.6,
      "rPct": 43.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 351,
      "rVotes": 301,
      "total": 652,
      "dPct": 53.8,
      "rPct": 46.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 321,
      "rVotes": 329,
      "total": 650,
      "dPct": 49.4,
      "rPct": 50.6
    }
  },
  {
    "precinct": "BATH TWP E",
    "township": "Bath",
    "ballotsCast": 705,
    "regVoters": 974,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 327,
      "rVotes": 358,
      "total": 691,
      "dPct": 47.3,
      "rPct": 51.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 357,
      "rVotes": 333,
      "total": 690,
      "dPct": 51.7,
      "rPct": 48.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 339,
      "rVotes": 346,
      "total": 685,
      "dPct": 49.5,
      "rPct": 50.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 313,
      "rVotes": 368,
      "total": 681,
      "dPct": 46,
      "rPct": 54
    }
  },
  {
    "precinct": "BATH TWP F",
    "township": "Bath",
    "ballotsCast": 677,
    "regVoters": 919,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 335,
      "rVotes": 319,
      "total": 664,
      "dPct": 50.5,
      "rPct": 48
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 360,
      "rVotes": 315,
      "total": 675,
      "dPct": 53.3,
      "rPct": 46.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 329,
      "rVotes": 333,
      "total": 662,
      "dPct": 49.7,
      "rPct": 50.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 319,
      "rVotes": 339,
      "total": 658,
      "dPct": 48.5,
      "rPct": 51.5
    }
  },
  {
    "precinct": "BATH TWP G",
    "township": "Bath",
    "ballotsCast": 752,
    "regVoters": 1056,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 307,
      "rVotes": 411,
      "total": 736,
      "dPct": 41.7,
      "rPct": 55.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 341,
      "rVotes": 392,
      "total": 733,
      "dPct": 46.5,
      "rPct": 53.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 306,
      "rVotes": 414,
      "total": 720,
      "dPct": 42.5,
      "rPct": 57.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 280,
      "rVotes": 445,
      "total": 725,
      "dPct": 38.6,
      "rPct": 61.4
    }
  },
  {
    "precinct": "BATH TWP H",
    "township": "Bath",
    "ballotsCast": 653,
    "regVoters": 924,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 398,
      "rVotes": 236,
      "total": 647,
      "dPct": 61.5,
      "rPct": 36.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 416,
      "rVotes": 226,
      "total": 642,
      "dPct": 64.8,
      "rPct": 35.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 427,
      "rVotes": 211,
      "total": 638,
      "dPct": 66.9,
      "rPct": 33.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 402,
      "rVotes": 225,
      "total": 627,
      "dPct": 64.1,
      "rPct": 35.9
    }
  },
  {
    "precinct": "BOSTON HTS VILL",
    "township": "Boston Heights",
    "ballotsCast": 734,
    "regVoters": 1080,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 292,
      "rVotes": 406,
      "total": 715,
      "dPct": 40.8,
      "rPct": 56.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 347,
      "rVotes": 369,
      "total": 716,
      "dPct": 48.5,
      "rPct": 51.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 296,
      "rVotes": 411,
      "total": 707,
      "dPct": 41.9,
      "rPct": 58.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 280,
      "rVotes": 406,
      "total": 686,
      "dPct": 40.8,
      "rPct": 59.2
    }
  },
  {
    "precinct": "BOSTON TWP",
    "township": "Boston Twp",
    "ballotsCast": 354,
    "regVoters": 549,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 159,
      "rVotes": 179,
      "total": 347,
      "dPct": 45.8,
      "rPct": 51.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 193,
      "rVotes": 155,
      "total": 348,
      "dPct": 55.5,
      "rPct": 44.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 184,
      "rVotes": 157,
      "total": 341,
      "dPct": 54,
      "rPct": 46
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 159,
      "rVotes": 176,
      "total": 335,
      "dPct": 47.5,
      "rPct": 52.5
    }
  },
  {
    "precinct": "COPLEY TWP A",
    "township": "Copley",
    "ballotsCast": 665,
    "regVoters": 1037,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 399,
      "rVotes": 241,
      "total": 653,
      "dPct": 61.1,
      "rPct": 36.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 439,
      "rVotes": 218,
      "total": 657,
      "dPct": 66.8,
      "rPct": 33.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 404,
      "rVotes": 248,
      "total": 652,
      "dPct": 62,
      "rPct": 38
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 408,
      "rVotes": 242,
      "total": 650,
      "dPct": 62.8,
      "rPct": 37.2
    }
  },
  {
    "precinct": "COPLEY TWP B",
    "township": "Copley",
    "ballotsCast": 582,
    "regVoters": 965,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 361,
      "rVotes": 195,
      "total": 568,
      "dPct": 63.6,
      "rPct": 34.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 387,
      "rVotes": 183,
      "total": 570,
      "dPct": 67.9,
      "rPct": 32.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 346,
      "rVotes": 214,
      "total": 560,
      "dPct": 61.8,
      "rPct": 38.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 349,
      "rVotes": 211,
      "total": 560,
      "dPct": 62.3,
      "rPct": 37.7
    }
  },
  {
    "precinct": "COPLEY TWP C",
    "township": "Copley",
    "ballotsCast": 643,
    "regVoters": 1062,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 382,
      "rVotes": 232,
      "total": 630,
      "dPct": 60.6,
      "rPct": 36.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 410,
      "rVotes": 228,
      "total": 638,
      "dPct": 64.3,
      "rPct": 35.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 385,
      "rVotes": 246,
      "total": 631,
      "dPct": 61,
      "rPct": 39
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 378,
      "rVotes": 251,
      "total": 629,
      "dPct": 60.1,
      "rPct": 39.9
    }
  },
  {
    "precinct": "COPLEY TWP D",
    "township": "Copley",
    "ballotsCast": 659,
    "regVoters": 1008,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 316,
      "rVotes": 313,
      "total": 643,
      "dPct": 49.1,
      "rPct": 48.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 342,
      "rVotes": 302,
      "total": 644,
      "dPct": 53.1,
      "rPct": 46.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 317,
      "rVotes": 320,
      "total": 637,
      "dPct": 49.8,
      "rPct": 50.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 324,
      "rVotes": 312,
      "total": 636,
      "dPct": 50.9,
      "rPct": 49.1
    }
  },
  {
    "precinct": "COPLEY TWP E",
    "township": "Copley",
    "ballotsCast": 709,
    "regVoters": 997,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 304,
      "rVotes": 380,
      "total": 701,
      "dPct": 43.4,
      "rPct": 54.2
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 329,
      "rVotes": 368,
      "total": 697,
      "dPct": 47.2,
      "rPct": 52.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 300,
      "rVotes": 394,
      "total": 694,
      "dPct": 43.2,
      "rPct": 56.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 283,
      "rVotes": 405,
      "total": 688,
      "dPct": 41.1,
      "rPct": 58.9
    }
  },
  {
    "precinct": "COPLEY TWP F",
    "township": "Copley",
    "ballotsCast": 783,
    "regVoters": 1166,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 425,
      "rVotes": 339,
      "total": 774,
      "dPct": 54.9,
      "rPct": 43.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 458,
      "rVotes": 320,
      "total": 778,
      "dPct": 58.9,
      "rPct": 41.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 420,
      "rVotes": 346,
      "total": 766,
      "dPct": 54.8,
      "rPct": 45.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 396,
      "rVotes": 371,
      "total": 767,
      "dPct": 51.6,
      "rPct": 48.4
    }
  },
  {
    "precinct": "COPLEY TWP G",
    "township": "Copley",
    "ballotsCast": 823,
    "regVoters": 1216,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 462,
      "rVotes": 334,
      "total": 805,
      "dPct": 57.4,
      "rPct": 41.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 482,
      "rVotes": 332,
      "total": 814,
      "dPct": 59.2,
      "rPct": 40.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 442,
      "rVotes": 356,
      "total": 798,
      "dPct": 55.4,
      "rPct": 44.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 440,
      "rVotes": 356,
      "total": 796,
      "dPct": 55.3,
      "rPct": 44.7
    }
  },
  {
    "precinct": "COPLEY TWP H",
    "township": "Copley",
    "ballotsCast": 602,
    "regVoters": 980,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 301,
      "rVotes": 272,
      "total": 587,
      "dPct": 51.3,
      "rPct": 46.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 337,
      "rVotes": 257,
      "total": 594,
      "dPct": 56.7,
      "rPct": 43.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 314,
      "rVotes": 271,
      "total": 585,
      "dPct": 53.7,
      "rPct": 46.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 292,
      "total": 581,
      "dPct": 49.7,
      "rPct": 50.3
    }
  },
  {
    "precinct": "COPLEY TWP I",
    "township": "Copley",
    "ballotsCast": 562,
    "regVoters": 1008,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 295,
      "rVotes": 245,
      "total": 548,
      "dPct": 53.8,
      "rPct": 44.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 316,
      "rVotes": 237,
      "total": 553,
      "dPct": 57.1,
      "rPct": 42.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 294,
      "rVotes": 251,
      "total": 545,
      "dPct": 53.9,
      "rPct": 46.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 295,
      "rVotes": 243,
      "total": 538,
      "dPct": 54.8,
      "rPct": 45.2
    }
  },
  {
    "precinct": "COPLEY TWP J",
    "township": "Copley",
    "ballotsCast": 723,
    "regVoters": 1064,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 322,
      "rVotes": 370,
      "total": 713,
      "dPct": 45.2,
      "rPct": 51.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 373,
      "rVotes": 337,
      "total": 710,
      "dPct": 52.5,
      "rPct": 47.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 323,
      "rVotes": 373,
      "total": 696,
      "dPct": 46.4,
      "rPct": 53.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 326,
      "rVotes": 367,
      "total": 693,
      "dPct": 47,
      "rPct": 53
    }
  },
  {
    "precinct": "COPLEY TWP K",
    "township": "Copley",
    "ballotsCast": 685,
    "regVoters": 979,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 344,
      "rVotes": 321,
      "total": 675,
      "dPct": 51,
      "rPct": 47.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 385,
      "rVotes": 288,
      "total": 673,
      "dPct": 57.2,
      "rPct": 42.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 329,
      "rVotes": 337,
      "total": 666,
      "dPct": 49.4,
      "rPct": 50.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 331,
      "rVotes": 333,
      "total": 664,
      "dPct": 49.8,
      "rPct": 50.2
    }
  },
  {
    "precinct": "COPLEY TWP L",
    "township": "Copley",
    "ballotsCast": 718,
    "regVoters": 1045,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 373,
      "rVotes": 330,
      "total": 710,
      "dPct": 52.5,
      "rPct": 46.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 409,
      "rVotes": 294,
      "total": 703,
      "dPct": 58.2,
      "rPct": 41.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 373,
      "rVotes": 325,
      "total": 698,
      "dPct": 53.4,
      "rPct": 46.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 372,
      "rVotes": 316,
      "total": 688,
      "dPct": 54.1,
      "rPct": 45.9
    }
  },
  {
    "precinct": "CUY FALLS 1-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 577,
    "regVoters": 1045,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 340,
      "rVotes": 205,
      "total": 569,
      "dPct": 59.8,
      "rPct": 36
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 385,
      "rVotes": 185,
      "total": 570,
      "dPct": 67.5,
      "rPct": 32.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 387,
      "rVotes": 177,
      "total": 564,
      "dPct": 68.6,
      "rPct": 31.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 334,
      "rVotes": 225,
      "total": 559,
      "dPct": 59.7,
      "rPct": 40.3
    }
  },
  {
    "precinct": "CUY FALLS 1-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 565,
    "regVoters": 1093,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 343,
      "rVotes": 192,
      "total": 555,
      "dPct": 61.8,
      "rPct": 34.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 387,
      "rVotes": 170,
      "total": 557,
      "dPct": 69.5,
      "rPct": 30.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 373,
      "rVotes": 172,
      "total": 545,
      "dPct": 68.4,
      "rPct": 31.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 335,
      "rVotes": 204,
      "total": 539,
      "dPct": 62.2,
      "rPct": 37.8
    }
  },
  {
    "precinct": "CUY FALLS 1-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 507,
    "regVoters": 975,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 287,
      "rVotes": 192,
      "total": 496,
      "dPct": 57.9,
      "rPct": 38.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 314,
      "rVotes": 187,
      "total": 501,
      "dPct": 62.7,
      "rPct": 37.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 315,
      "rVotes": 185,
      "total": 500,
      "dPct": 63,
      "rPct": 37
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 265,
      "rVotes": 235,
      "total": 500,
      "dPct": 53,
      "rPct": 47
    }
  },
  {
    "precinct": "CUY FALLS 1-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 533,
    "regVoters": 1007,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 289,
      "rVotes": 214,
      "total": 523,
      "dPct": 55.3,
      "rPct": 40.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 317,
      "rVotes": 207,
      "total": 524,
      "dPct": 60.5,
      "rPct": 39.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 312,
      "rVotes": 208,
      "total": 520,
      "dPct": 60,
      "rPct": 40
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 272,
      "rVotes": 245,
      "total": 517,
      "dPct": 52.6,
      "rPct": 47.4
    }
  },
  {
    "precinct": "CUY FALLS 2-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 470,
    "regVoters": 862,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 285,
      "rVotes": 157,
      "total": 460,
      "dPct": 62,
      "rPct": 34.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 320,
      "rVotes": 142,
      "total": 462,
      "dPct": 69.3,
      "rPct": 30.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 316,
      "rVotes": 142,
      "total": 458,
      "dPct": 69,
      "rPct": 31
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 283,
      "rVotes": 179,
      "total": 462,
      "dPct": 61.3,
      "rPct": 38.7
    }
  },
  {
    "precinct": "CUY FALLS 2-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 460,
    "regVoters": 839,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 272,
      "rVotes": 159,
      "total": 453,
      "dPct": 60,
      "rPct": 35.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 297,
      "rVotes": 158,
      "total": 455,
      "dPct": 65.3,
      "rPct": 34.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 281,
      "rVotes": 160,
      "total": 441,
      "dPct": 63.7,
      "rPct": 36.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 245,
      "rVotes": 200,
      "total": 445,
      "dPct": 55.1,
      "rPct": 44.9
    }
  },
  {
    "precinct": "CUY FALLS 2-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 538,
    "regVoters": 837,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 300,
      "rVotes": 216,
      "total": 533,
      "dPct": 56.3,
      "rPct": 40.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 333,
      "rVotes": 200,
      "total": 533,
      "dPct": 62.5,
      "rPct": 37.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 316,
      "rVotes": 213,
      "total": 529,
      "dPct": 59.7,
      "rPct": 40.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 280,
      "rVotes": 246,
      "total": 526,
      "dPct": 53.2,
      "rPct": 46.8
    }
  },
  {
    "precinct": "CUY FALLS 2-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 498,
    "regVoters": 835,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 266,
      "rVotes": 204,
      "total": 491,
      "dPct": 54.2,
      "rPct": 41.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 297,
      "rVotes": 190,
      "total": 487,
      "dPct": 61,
      "rPct": 39
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 287,
      "rVotes": 193,
      "total": 480,
      "dPct": 59.8,
      "rPct": 40.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 248,
      "rVotes": 232,
      "total": 480,
      "dPct": 51.7,
      "rPct": 48.3
    }
  },
  {
    "precinct": "CUY FALLS 2-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 475,
    "regVoters": 805,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 268,
      "rVotes": 171,
      "total": 463,
      "dPct": 57.9,
      "rPct": 36.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 293,
      "rVotes": 165,
      "total": 458,
      "dPct": 64,
      "rPct": 36
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 292,
      "rVotes": 171,
      "total": 463,
      "dPct": 63.1,
      "rPct": 36.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 242,
      "rVotes": 218,
      "total": 460,
      "dPct": 52.6,
      "rPct": 47.4
    }
  },
  {
    "precinct": "CUY FALLS 3-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 521,
    "regVoters": 836,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 269,
      "rVotes": 224,
      "total": 510,
      "dPct": 52.7,
      "rPct": 43.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 298,
      "rVotes": 212,
      "total": 510,
      "dPct": 58.4,
      "rPct": 41.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 228,
      "rVotes": 147,
      "total": 375,
      "dPct": 60.8,
      "rPct": 39.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 241,
      "rVotes": 259,
      "total": 500,
      "dPct": 48.2,
      "rPct": 51.8
    }
  },
  {
    "precinct": "CUY FALLS 3-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 593,
    "regVoters": 861,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 338,
      "rVotes": 225,
      "total": 580,
      "dPct": 58.3,
      "rPct": 38.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 380,
      "rVotes": 203,
      "total": 583,
      "dPct": 65.2,
      "rPct": 34.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 373,
      "rVotes": 208,
      "total": 581,
      "dPct": 64.2,
      "rPct": 35.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 319,
      "rVotes": 265,
      "total": 584,
      "dPct": 54.6,
      "rPct": 45.4
    }
  },
  {
    "precinct": "CUY FALLS 3-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 589,
    "regVoters": 884,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 308,
      "rVotes": 254,
      "total": 581,
      "dPct": 53,
      "rPct": 43.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 345,
      "rVotes": 234,
      "total": 579,
      "dPct": 59.6,
      "rPct": 40.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 332,
      "rVotes": 239,
      "total": 571,
      "dPct": 58.1,
      "rPct": 41.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 275,
      "rVotes": 294,
      "total": 569,
      "dPct": 48.3,
      "rPct": 51.7
    }
  },
  {
    "precinct": "CUY FALLS 3-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 571,
    "regVoters": 842,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 304,
      "rVotes": 240,
      "total": 560,
      "dPct": 54.3,
      "rPct": 42.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 335,
      "rVotes": 226,
      "total": 561,
      "dPct": 59.7,
      "rPct": 40.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 331,
      "rVotes": 229,
      "total": 560,
      "dPct": 59.1,
      "rPct": 40.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 271,
      "rVotes": 287,
      "total": 558,
      "dPct": 48.6,
      "rPct": 51.4
    }
  },
  {
    "precinct": "CUY FALLS 3-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 538,
    "regVoters": 942,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 302,
      "rVotes": 218,
      "total": 532,
      "dPct": 56.8,
      "rPct": 41
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 332,
      "rVotes": 200,
      "total": 532,
      "dPct": 62.4,
      "rPct": 37.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 319,
      "rVotes": 205,
      "total": 524,
      "dPct": 60.9,
      "rPct": 39.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 274,
      "rVotes": 246,
      "total": 520,
      "dPct": 52.7,
      "rPct": 47.3
    }
  },
  {
    "precinct": "CUY FALLS 4-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 339,
    "regVoters": 760,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 219,
      "rVotes": 96,
      "total": 329,
      "dPct": 66.6,
      "rPct": 29.2
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 239,
      "rVotes": 96,
      "total": 335,
      "dPct": 71.3,
      "rPct": 28.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 237,
      "rVotes": 92,
      "total": 329,
      "dPct": 72,
      "rPct": 28
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 222,
      "rVotes": 106,
      "total": 328,
      "dPct": 67.7,
      "rPct": 32.3
    }
  },
  {
    "precinct": "CUY FALLS 4-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 498,
    "regVoters": 858,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 284,
      "rVotes": 186,
      "total": 488,
      "dPct": 58.2,
      "rPct": 38.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 325,
      "rVotes": 165,
      "total": 490,
      "dPct": 66.3,
      "rPct": 33.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 316,
      "rVotes": 166,
      "total": 482,
      "dPct": 65.6,
      "rPct": 34.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 264,
      "rVotes": 222,
      "total": 486,
      "dPct": 54.3,
      "rPct": 45.7
    }
  },
  {
    "precinct": "CUY FALLS 4-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 547,
    "regVoters": 860,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 314,
      "rVotes": 201,
      "total": 537,
      "dPct": 58.5,
      "rPct": 37.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 347,
      "rVotes": 190,
      "total": 537,
      "dPct": 64.6,
      "rPct": 35.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 342,
      "rVotes": 194,
      "total": 536,
      "dPct": 63.8,
      "rPct": 36.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 245,
      "total": 534,
      "dPct": 54.1,
      "rPct": 45.9
    }
  },
  {
    "precinct": "CUY FALLS 4-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 523,
    "regVoters": 886,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 298,
      "rVotes": 199,
      "total": 515,
      "dPct": 57.9,
      "rPct": 38.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 329,
      "rVotes": 187,
      "total": 516,
      "dPct": 63.8,
      "rPct": 36.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 324,
      "rVotes": 182,
      "total": 506,
      "dPct": 64,
      "rPct": 36
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 279,
      "rVotes": 224,
      "total": 503,
      "dPct": 55.5,
      "rPct": 44.5
    }
  },
  {
    "precinct": "CUY FALLS 4-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 493,
    "regVoters": 800,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 262,
      "rVotes": 191,
      "total": 474,
      "dPct": 55.3,
      "rPct": 40.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 297,
      "rVotes": 181,
      "total": 478,
      "dPct": 62.1,
      "rPct": 37.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 185,
      "total": 474,
      "dPct": 61,
      "rPct": 39
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 234,
      "rVotes": 235,
      "total": 469,
      "dPct": 49.9,
      "rPct": 50.1
    }
  },
  {
    "precinct": "CUY FALLS 5-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 350,
    "regVoters": 822,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 208,
      "rVotes": 121,
      "total": 342,
      "dPct": 60.8,
      "rPct": 35.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 227,
      "rVotes": 112,
      "total": 339,
      "dPct": 67,
      "rPct": 33
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 215,
      "rVotes": 125,
      "total": 340,
      "dPct": 63.2,
      "rPct": 36.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 216,
      "rVotes": 124,
      "total": 340,
      "dPct": 63.5,
      "rPct": 36.5
    }
  },
  {
    "precinct": "CUY FALLS 5-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 611,
    "regVoters": 818,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 285,
      "rVotes": 292,
      "total": 587,
      "dPct": 48.6,
      "rPct": 49.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 353,
      "rVotes": 242,
      "total": 595,
      "dPct": 59.3,
      "rPct": 40.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 288,
      "rVotes": 294,
      "total": 582,
      "dPct": 49.5,
      "rPct": 50.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 260,
      "rVotes": 295,
      "total": 555,
      "dPct": 46.8,
      "rPct": 53.2
    }
  },
  {
    "precinct": "CUY FALLS 5-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 584,
    "regVoters": 940,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 317,
      "rVotes": 241,
      "total": 569,
      "dPct": 55.7,
      "rPct": 42.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 366,
      "rVotes": 201,
      "total": 567,
      "dPct": 64.6,
      "rPct": 35.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 356,
      "rVotes": 215,
      "total": 571,
      "dPct": 62.3,
      "rPct": 37.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 285,
      "total": 574,
      "dPct": 50.3,
      "rPct": 49.7
    }
  },
  {
    "precinct": "CUY FALLS 5-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 534,
    "regVoters": 845,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 285,
      "rVotes": 219,
      "total": 518,
      "dPct": 55,
      "rPct": 42.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 315,
      "rVotes": 204,
      "total": 519,
      "dPct": 60.7,
      "rPct": 39.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 313,
      "rVotes": 207,
      "total": 520,
      "dPct": 60.2,
      "rPct": 39.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 266,
      "rVotes": 247,
      "total": 513,
      "dPct": 51.9,
      "rPct": 48.1
    }
  },
  {
    "precinct": "CUY FALLS 5-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 451,
    "regVoters": 800,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 270,
      "rVotes": 151,
      "total": 436,
      "dPct": 61.9,
      "rPct": 34.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 302,
      "rVotes": 138,
      "total": 440,
      "dPct": 68.6,
      "rPct": 31.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 105,
      "rVotes": 54,
      "total": 159,
      "dPct": 66,
      "rPct": 34
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 254,
      "rVotes": 180,
      "total": 434,
      "dPct": 58.5,
      "rPct": 41.5
    }
  },
  {
    "precinct": "CUY FALLS 6-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 508,
    "regVoters": 839,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 250,
      "rVotes": 228,
      "total": 495,
      "dPct": 50.5,
      "rPct": 46.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 287,
      "rVotes": 212,
      "total": 499,
      "dPct": 57.5,
      "rPct": 42.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 272,
      "rVotes": 219,
      "total": 491,
      "dPct": 55.4,
      "rPct": 44.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 220,
      "rVotes": 273,
      "total": 493,
      "dPct": 44.6,
      "rPct": 55.4
    }
  },
  {
    "precinct": "CUY FALLS 6-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 521,
    "regVoters": 831,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 262,
      "rVotes": 228,
      "total": 502,
      "dPct": 52.2,
      "rPct": 45.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 293,
      "rVotes": 222,
      "total": 515,
      "dPct": 56.9,
      "rPct": 43.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 284,
      "rVotes": 223,
      "total": 507,
      "dPct": 56,
      "rPct": 44
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 237,
      "rVotes": 269,
      "total": 506,
      "dPct": 46.8,
      "rPct": 53.2
    }
  },
  {
    "precinct": "CUY FALLS 6-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 459,
    "regVoters": 840,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 234,
      "rVotes": 190,
      "total": 455,
      "dPct": 51.4,
      "rPct": 41.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 279,
      "rVotes": 169,
      "total": 448,
      "dPct": 62.3,
      "rPct": 37.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 273,
      "rVotes": 177,
      "total": 450,
      "dPct": 60.7,
      "rPct": 39.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 213,
      "total": 443,
      "dPct": 51.9,
      "rPct": 48.1
    }
  },
  {
    "precinct": "CUY FALLS 6-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 469,
    "regVoters": 781,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 253,
      "rVotes": 190,
      "total": 463,
      "dPct": 54.6,
      "rPct": 41
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 290,
      "rVotes": 172,
      "total": 462,
      "dPct": 62.8,
      "rPct": 37.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 282,
      "rVotes": 168,
      "total": 450,
      "dPct": 62.7,
      "rPct": 37.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 229,
      "rVotes": 218,
      "total": 447,
      "dPct": 51.2,
      "rPct": 48.8
    }
  },
  {
    "precinct": "CUY FALLS 6-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 458,
    "regVoters": 783,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 245,
      "rVotes": 188,
      "total": 450,
      "dPct": 54.4,
      "rPct": 41.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 277,
      "rVotes": 174,
      "total": 451,
      "dPct": 61.4,
      "rPct": 38.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 171,
      "total": 441,
      "dPct": 61.2,
      "rPct": 38.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 222,
      "rVotes": 218,
      "total": 440,
      "dPct": 50.5,
      "rPct": 49.5
    }
  },
  {
    "precinct": "CUY FALLS 7-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 530,
    "regVoters": 854,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 296,
      "rVotes": 213,
      "total": 523,
      "dPct": 56.6,
      "rPct": 40.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 318,
      "rVotes": 202,
      "total": 520,
      "dPct": 61.2,
      "rPct": 38.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 313,
      "rVotes": 208,
      "total": 521,
      "dPct": 60.1,
      "rPct": 39.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 268,
      "rVotes": 248,
      "total": 516,
      "dPct": 51.9,
      "rPct": 48.1
    }
  },
  {
    "precinct": "CUY FALLS 7-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 391,
    "regVoters": 828,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 218,
      "rVotes": 155,
      "total": 386,
      "dPct": 56.5,
      "rPct": 40.2
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 238,
      "rVotes": 149,
      "total": 387,
      "dPct": 61.5,
      "rPct": 38.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 231,
      "rVotes": 149,
      "total": 380,
      "dPct": 60.8,
      "rPct": 39.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 215,
      "rVotes": 164,
      "total": 379,
      "dPct": 56.7,
      "rPct": 43.3
    }
  },
  {
    "precinct": "CUY FALLS 7-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 445,
    "regVoters": 648,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 217,
      "rVotes": 200,
      "total": 425,
      "dPct": 51.1,
      "rPct": 47.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 241,
      "rVotes": 194,
      "total": 435,
      "dPct": 55.4,
      "rPct": 44.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 202,
      "rVotes": 224,
      "total": 426,
      "dPct": 47.4,
      "rPct": 52.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 176,
      "rVotes": 256,
      "total": 432,
      "dPct": 40.7,
      "rPct": 59.3
    }
  },
  {
    "precinct": "CUY FALLS 7-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 473,
    "regVoters": 852,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 259,
      "rVotes": 188,
      "total": 462,
      "dPct": 56.1,
      "rPct": 40.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 287,
      "rVotes": 177,
      "total": 464,
      "dPct": 61.9,
      "rPct": 38.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 271,
      "rVotes": 183,
      "total": 454,
      "dPct": 59.7,
      "rPct": 40.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 226,
      "rVotes": 225,
      "total": 451,
      "dPct": 50.1,
      "rPct": 49.9
    }
  },
  {
    "precinct": "CUY FALLS 7-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 513,
    "regVoters": 867,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 279,
      "rVotes": 204,
      "total": 502,
      "dPct": 55.6,
      "rPct": 40.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 317,
      "rVotes": 188,
      "total": 505,
      "dPct": 62.8,
      "rPct": 37.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 304,
      "rVotes": 189,
      "total": 493,
      "dPct": 61.7,
      "rPct": 38.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 269,
      "rVotes": 227,
      "total": 496,
      "dPct": 54.2,
      "rPct": 45.8
    }
  },
  {
    "precinct": "CUY FALLS 8-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 737,
    "regVoters": 1003,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 317,
      "rVotes": 335,
      "total": 680,
      "dPct": 46.6,
      "rPct": 49.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 358,
      "rVotes": 320,
      "total": 678,
      "dPct": 52.8,
      "rPct": 47.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 310,
      "rVotes": 357,
      "total": 667,
      "dPct": 46.5,
      "rPct": 53.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 298,
      "rVotes": 366,
      "total": 664,
      "dPct": 44.9,
      "rPct": 55.1
    }
  },
  {
    "precinct": "CUY FALLS 8-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 613,
    "regVoters": 922,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 312,
      "rVotes": 260,
      "total": 596,
      "dPct": 52.3,
      "rPct": 43.6
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 351,
      "rVotes": 246,
      "total": 597,
      "dPct": 58.8,
      "rPct": 41.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 134,
      "rVotes": 135,
      "total": 269,
      "dPct": 49.8,
      "rPct": 50.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 12,
      "rVotes": 7,
      "total": 19,
      "dPct": 63.2,
      "rPct": 36.8
    }
  },
  {
    "precinct": "CUY FALLS 8-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 774,
    "regVoters": 1027,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 376,
      "rVotes": 351,
      "total": 739,
      "dPct": 50.9,
      "rPct": 47.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 410,
      "rVotes": 323,
      "total": 733,
      "dPct": 55.9,
      "rPct": 44.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 354,
      "rVotes": 350,
      "total": 704,
      "dPct": 50.3,
      "rPct": 49.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 325,
      "rVotes": 383,
      "total": 708,
      "dPct": 45.9,
      "rPct": 54.1
    }
  },
  {
    "precinct": "CUY FALLS 8-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 584,
    "regVoters": 790,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 273,
      "rVotes": 285,
      "total": 567,
      "dPct": 48.1,
      "rPct": 50.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 287,
      "rVotes": 283,
      "total": 570,
      "dPct": 50.4,
      "rPct": 49.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 286,
      "rVotes": 277,
      "total": 563,
      "dPct": 50.8,
      "rPct": 49.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 300,
      "total": 563,
      "dPct": 46.7,
      "rPct": 53.3
    }
  },
  {
    "precinct": "CUY FALLS 8-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 863,
    "regVoters": 1195,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 359,
      "rVotes": 458,
      "total": 840,
      "dPct": 42.7,
      "rPct": 54.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 425,
      "rVotes": 416,
      "total": 841,
      "dPct": 50.5,
      "rPct": 49.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 368,
      "rVotes": 460,
      "total": 828,
      "dPct": 44.4,
      "rPct": 55.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 347,
      "rVotes": 475,
      "total": 822,
      "dPct": 42.2,
      "rPct": 57.8
    }
  },
  {
    "precinct": "CUY FALLS 8-F",
    "township": "Cuyahoga Falls",
    "ballotsCast": 380,
    "regVoters": 605,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 191,
      "rVotes": 170,
      "total": 372,
      "dPct": 51.3,
      "rPct": 45.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 221,
      "rVotes": 152,
      "total": 373,
      "dPct": 59.2,
      "rPct": 40.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 198,
      "rVotes": 163,
      "total": 361,
      "dPct": 54.8,
      "rPct": 45.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 172,
      "rVotes": 191,
      "total": 363,
      "dPct": 47.4,
      "rPct": 52.6
    }
  },
  {
    "precinct": "NORTON 1-A",
    "township": "Norton",
    "ballotsCast": 481,
    "regVoters": 679,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 183,
      "rVotes": 243,
      "total": 450,
      "dPct": 40.7,
      "rPct": 54
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 207,
      "rVotes": 252,
      "total": 459,
      "dPct": 45.1,
      "rPct": 54.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 178,
      "rVotes": 263,
      "total": 441,
      "dPct": 40.4,
      "rPct": 59.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 176,
      "rVotes": 263,
      "total": 439,
      "dPct": 40.1,
      "rPct": 59.9
    }
  },
  {
    "precinct": "NORTON 1-B",
    "township": "Norton",
    "ballotsCast": 467,
    "regVoters": 690,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 202,
      "rVotes": 230,
      "total": 445,
      "dPct": 45.4,
      "rPct": 51.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 231,
      "rVotes": 222,
      "total": 453,
      "dPct": 51,
      "rPct": 49
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 233,
      "total": 430,
      "dPct": 45.8,
      "rPct": 54.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 203,
      "rVotes": 231,
      "total": 434,
      "dPct": 46.8,
      "rPct": 53.2
    }
  },
  {
    "precinct": "NORTON 1-C",
    "township": "Norton",
    "ballotsCast": 448,
    "regVoters": 710,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 168,
      "rVotes": 254,
      "total": 436,
      "dPct": 38.5,
      "rPct": 58.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 171,
      "rVotes": 262,
      "total": 433,
      "dPct": 39.5,
      "rPct": 60.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 155,
      "rVotes": 264,
      "total": 419,
      "dPct": 37,
      "rPct": 63
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 159,
      "rVotes": 266,
      "total": 425,
      "dPct": 37.4,
      "rPct": 62.6
    }
  },
  {
    "precinct": "NORTON 2-A",
    "township": "Norton",
    "ballotsCast": 462,
    "regVoters": 740,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 216,
      "rVotes": 214,
      "total": 441,
      "dPct": 49,
      "rPct": 48.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 246,
      "rVotes": 200,
      "total": 446,
      "dPct": 55.2,
      "rPct": 44.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 213,
      "rVotes": 235,
      "total": 448,
      "dPct": 47.5,
      "rPct": 52.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 217,
      "rVotes": 222,
      "total": 439,
      "dPct": 49.4,
      "rPct": 50.6
    }
  },
  {
    "precinct": "NORTON 2-B",
    "township": "Norton",
    "ballotsCast": 440,
    "regVoters": 644,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 194,
      "rVotes": 217,
      "total": 419,
      "dPct": 46.3,
      "rPct": 51.8
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 209,
      "rVotes": 218,
      "total": 427,
      "dPct": 48.9,
      "rPct": 51.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 172,
      "rVotes": 242,
      "total": 414,
      "dPct": 41.5,
      "rPct": 58.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 179,
      "rVotes": 228,
      "total": 407,
      "dPct": 44,
      "rPct": 56
    }
  },
  {
    "precinct": "NORTON 2-C",
    "township": "Norton",
    "ballotsCast": 442,
    "regVoters": 642,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 199,
      "rVotes": 226,
      "total": 431,
      "dPct": 46.2,
      "rPct": 52.4
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 202,
      "rVotes": 226,
      "total": 428,
      "dPct": 47.2,
      "rPct": 52.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 172,
      "rVotes": 242,
      "total": 414,
      "dPct": 41.5,
      "rPct": 58.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 163,
      "rVotes": 242,
      "total": 405,
      "dPct": 40.2,
      "rPct": 59.8
    }
  },
  {
    "precinct": "NORTON 3-A",
    "township": "Norton",
    "ballotsCast": 529,
    "regVoters": 761,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 207,
      "rVotes": 284,
      "total": 508,
      "dPct": 40.7,
      "rPct": 55.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 224,
      "rVotes": 284,
      "total": 508,
      "dPct": 44.1,
      "rPct": 55.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 194,
      "rVotes": 295,
      "total": 489,
      "dPct": 39.7,
      "rPct": 60.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 187,
      "rVotes": 294,
      "total": 481,
      "dPct": 38.9,
      "rPct": 61.1
    }
  },
  {
    "precinct": "NORTON 3-B",
    "township": "Norton",
    "ballotsCast": 415,
    "regVoters": 675,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 175,
      "rVotes": 207,
      "total": 399,
      "dPct": 43.9,
      "rPct": 51.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 196,
      "rVotes": 203,
      "total": 399,
      "dPct": 49.1,
      "rPct": 50.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 166,
      "rVotes": 227,
      "total": 393,
      "dPct": 42.2,
      "rPct": 57.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 170,
      "rVotes": 219,
      "total": 389,
      "dPct": 43.7,
      "rPct": 56.3
    }
  },
  {
    "precinct": "NORTON 3-C",
    "township": "Norton",
    "ballotsCast": 467,
    "regVoters": 665,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 212,
      "rVotes": 220,
      "total": 454,
      "dPct": 46.7,
      "rPct": 48.5
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 234,
      "rVotes": 220,
      "total": 454,
      "dPct": 51.5,
      "rPct": 48.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 208,
      "rVotes": 235,
      "total": 443,
      "dPct": 47,
      "rPct": 53
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 204,
      "rVotes": 231,
      "total": 435,
      "dPct": 46.9,
      "rPct": 53.1
    }
  },
  {
    "precinct": "NORTON 4-A",
    "township": "Norton",
    "ballotsCast": 555,
    "regVoters": 971,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 188,
      "rVotes": 323,
      "total": 541,
      "dPct": 34.8,
      "rPct": 59.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 224,
      "rVotes": 311,
      "total": 535,
      "dPct": 41.9,
      "rPct": 58.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 176,
      "rVotes": 347,
      "total": 523,
      "dPct": 33.7,
      "rPct": 66.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 168,
      "rVotes": 353,
      "total": 521,
      "dPct": 32.2,
      "rPct": 67.8
    }
  },
  {
    "precinct": "NORTON 4-B",
    "township": "Norton",
    "ballotsCast": 544,
    "regVoters": 934,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 227,
      "rVotes": 279,
      "total": 524,
      "dPct": 43.3,
      "rPct": 53.2
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 248,
      "rVotes": 281,
      "total": 529,
      "dPct": 46.9,
      "rPct": 53.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 213,
      "rVotes": 298,
      "total": 511,
      "dPct": 41.7,
      "rPct": 58.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 199,
      "rVotes": 303,
      "total": 502,
      "dPct": 39.6,
      "rPct": 60.4
    }
  },
  {
    "precinct": "PENINSULA VILL",
    "township": "Peninsula",
    "ballotsCast": 326,
    "regVoters": 440,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 193,
      "rVotes": 113,
      "total": 312,
      "dPct": 61.9,
      "rPct": 36.2
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 204,
      "rVotes": 112,
      "total": 316,
      "dPct": 64.6,
      "rPct": 35.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 106,
      "total": 303,
      "dPct": 65,
      "rPct": 35
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 177,
      "rVotes": 123,
      "total": 300,
      "dPct": 59,
      "rPct": 41
    }
  },
  {
    "precinct": "RICHFIELD TWP Y",
    "township": "Richfield Township",
    "ballotsCast": 797,
    "regVoters": 1080,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 309,
      "rVotes": 448,
      "total": 774,
      "dPct": 39.9,
      "rPct": 57.9
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 348,
      "rVotes": 433,
      "total": 781,
      "dPct": 44.6,
      "rPct": 55.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 313,
      "rVotes": 452,
      "total": 765,
      "dPct": 40.9,
      "rPct": 59.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 280,
      "rVotes": 493,
      "total": 773,
      "dPct": 36.2,
      "rPct": 63.8
    }
  },
  {
    "precinct": "RICHFIELD TWP Z",
    "township": "Richfield Township",
    "ballotsCast": 723,
    "regVoters": 1044,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 282,
      "rVotes": 406,
      "total": 708,
      "dPct": 39.8,
      "rPct": 57.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 312,
      "rVotes": 395,
      "total": 707,
      "dPct": 44.1,
      "rPct": 55.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 407,
      "total": 696,
      "dPct": 41.5,
      "rPct": 58.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 235,
      "rVotes": 461,
      "total": 696,
      "dPct": 33.8,
      "rPct": 66.2
    }
  },
  {
    "precinct": "RICHFIELD VILL A",
    "township": "Richfield Village",
    "ballotsCast": 584,
    "regVoters": 936,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 232,
      "rVotes": 321,
      "total": 572,
      "dPct": 40.6,
      "rPct": 56.1
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 268,
      "rVotes": 307,
      "total": 575,
      "dPct": 46.6,
      "rPct": 53.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 226,
      "rVotes": 331,
      "total": 557,
      "dPct": 40.6,
      "rPct": 59.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 367,
      "total": 564,
      "dPct": 34.9,
      "rPct": 65.1
    }
  },
  {
    "precinct": "RICHFIELD VILL B",
    "township": "Richfield Village",
    "ballotsCast": 667,
    "regVoters": 940,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 209,
      "rVotes": 428,
      "total": 662,
      "dPct": 31.6,
      "rPct": 64.7
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 262,
      "rVotes": 397,
      "total": 659,
      "dPct": 39.8,
      "rPct": 60.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 232,
      "rVotes": 410,
      "total": 642,
      "dPct": 36.1,
      "rPct": 63.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 202,
      "rVotes": 440,
      "total": 642,
      "dPct": 31.5,
      "rPct": 68.5
    }
  },
  {
    "precinct": "RICHFIELD VILL C",
    "township": "Richfield Village",
    "ballotsCast": 673,
    "regVoters": 921,
    "pres": {
      "dName": "Cordray",
      "rName": "DeWine",
      "dVotes": 271,
      "rVotes": 373,
      "total": 662,
      "dPct": 40.9,
      "rPct": 56.3
    },
    "senate": {
      "dName": "Brown",
      "rName": "Renacci",
      "dVotes": 328,
      "rVotes": 335,
      "total": 663,
      "dPct": 49.5,
      "rPct": 50.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 283,
      "rVotes": 357,
      "total": 640,
      "dPct": 44.2,
      "rPct": 55.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 251,
      "rVotes": 398,
      "total": 649,
      "dPct": 38.7,
      "rPct": 61.3
    }
  }
];

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct2018: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData2018.map(p => [p.precinct, p]));
