// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/summit_10_townships_results_22.csv
// NOTE: "pres" field stores 2022 Governor results (Whaley vs DeWine).

import type { OH31Precinct } from "@/data/oh31PrecinctData";

export const oh31PrecinctData2022: OH31Precinct[] = [
  {
    "precinct": "BARBERTON 1-A",
    "township": "Barberton",
    "ballotsCast": 364,
    "regVoters": 833,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 127,
      "rVotes": 227,
      "total": 354,
      "dPct": 35.9,
      "rPct": 64.1
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 158,
      "rVotes": 200,
      "total": 358,
      "dPct": 44.1,
      "rPct": 55.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 154,
      "rVotes": 200,
      "total": 354,
      "dPct": 43.5,
      "rPct": 56.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 149,
      "rVotes": 211,
      "total": 360,
      "dPct": 41.4,
      "rPct": 58.6
    }
  },
  {
    "precinct": "BARBERTON 1-B",
    "township": "Barberton",
    "ballotsCast": 360,
    "regVoters": 838,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 123,
      "rVotes": 223,
      "total": 346,
      "dPct": 35.5,
      "rPct": 64.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 162,
      "rVotes": 191,
      "total": 353,
      "dPct": 45.9,
      "rPct": 54.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 159,
      "rVotes": 195,
      "total": 354,
      "dPct": 44.9,
      "rPct": 55.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 144,
      "rVotes": 210,
      "total": 354,
      "dPct": 40.7,
      "rPct": 59.3
    }
  },
  {
    "precinct": "BARBERTON 1-C",
    "township": "Barberton",
    "ballotsCast": 432,
    "regVoters": 905,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 149,
      "rVotes": 263,
      "total": 412,
      "dPct": 36.2,
      "rPct": 63.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 205,
      "rVotes": 218,
      "total": 423,
      "dPct": 48.5,
      "rPct": 51.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 200,
      "rVotes": 214,
      "total": 414,
      "dPct": 48.3,
      "rPct": 51.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 182,
      "rVotes": 236,
      "total": 418,
      "dPct": 43.5,
      "rPct": 56.5
    }
  },
  {
    "precinct": "BARBERTON 2-A",
    "township": "Barberton",
    "ballotsCast": 472,
    "regVoters": 939,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 166,
      "rVotes": 293,
      "total": 459,
      "dPct": 36.2,
      "rPct": 63.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 235,
      "rVotes": 227,
      "total": 462,
      "dPct": 50.9,
      "rPct": 49.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 223,
      "rVotes": 232,
      "total": 455,
      "dPct": 49,
      "rPct": 51
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 206,
      "rVotes": 256,
      "total": 462,
      "dPct": 44.6,
      "rPct": 55.4
    }
  },
  {
    "precinct": "BARBERTON 2-B",
    "township": "Barberton",
    "ballotsCast": 525,
    "regVoters": 887,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 188,
      "rVotes": 321,
      "total": 509,
      "dPct": 36.9,
      "rPct": 63.1
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 261,
      "rVotes": 256,
      "total": 517,
      "dPct": 50.5,
      "rPct": 49.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 260,
      "rVotes": 248,
      "total": 508,
      "dPct": 51.2,
      "rPct": 48.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 236,
      "rVotes": 278,
      "total": 514,
      "dPct": 45.9,
      "rPct": 54.1
    }
  },
  {
    "precinct": "BARBERTON 2-C",
    "township": "Barberton",
    "ballotsCast": 368,
    "regVoters": 875,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 143,
      "rVotes": 218,
      "total": 361,
      "dPct": 39.6,
      "rPct": 60.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 187,
      "rVotes": 176,
      "total": 363,
      "dPct": 51.5,
      "rPct": 48.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 182,
      "rVotes": 175,
      "total": 357,
      "dPct": 51,
      "rPct": 49
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 172,
      "rVotes": 187,
      "total": 359,
      "dPct": 47.9,
      "rPct": 52.1
    }
  },
  {
    "precinct": "BARBERTON 3-A",
    "township": "Barberton",
    "ballotsCast": 406,
    "regVoters": 1052,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 248,
      "rVotes": 144,
      "total": 392,
      "dPct": 63.3,
      "rPct": 36.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 280,
      "rVotes": 119,
      "total": 399,
      "dPct": 70.2,
      "rPct": 29.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 280,
      "rVotes": 119,
      "total": 399,
      "dPct": 70.2,
      "rPct": 29.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 137,
      "total": 400,
      "dPct": 65.8,
      "rPct": 34.2
    }
  },
  {
    "precinct": "BARBERTON 3-B",
    "township": "Barberton",
    "ballotsCast": 503,
    "regVoters": 946,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 237,
      "rVotes": 253,
      "total": 490,
      "dPct": 48.4,
      "rPct": 51.6
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 323,
      "rVotes": 176,
      "total": 499,
      "dPct": 64.7,
      "rPct": 35.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 303,
      "rVotes": 182,
      "total": 485,
      "dPct": 62.5,
      "rPct": 37.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 288,
      "rVotes": 202,
      "total": 490,
      "dPct": 58.8,
      "rPct": 41.2
    }
  },
  {
    "precinct": "BARBERTON 3-C",
    "township": "Barberton",
    "ballotsCast": 655,
    "regVoters": 931,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 405,
      "total": 635,
      "dPct": 36.2,
      "rPct": 63.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 322,
      "rVotes": 323,
      "total": 645,
      "dPct": 49.9,
      "rPct": 50.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 306,
      "rVotes": 332,
      "total": 638,
      "dPct": 48,
      "rPct": 52
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 287,
      "rVotes": 349,
      "total": 636,
      "dPct": 45.1,
      "rPct": 54.9
    }
  },
  {
    "precinct": "BARBERTON 4-A",
    "township": "Barberton",
    "ballotsCast": 242,
    "regVoters": 740,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 94,
      "rVotes": 145,
      "total": 239,
      "dPct": 39.3,
      "rPct": 60.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 116,
      "rVotes": 121,
      "total": 237,
      "dPct": 48.9,
      "rPct": 51.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 113,
      "rVotes": 118,
      "total": 231,
      "dPct": 48.9,
      "rPct": 51.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 113,
      "rVotes": 125,
      "total": 238,
      "dPct": 47.5,
      "rPct": 52.5
    }
  },
  {
    "precinct": "BARBERTON 4-B",
    "township": "Barberton",
    "ballotsCast": 249,
    "regVoters": 754,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 113,
      "rVotes": 127,
      "total": 240,
      "dPct": 47.1,
      "rPct": 52.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 141,
      "rVotes": 105,
      "total": 246,
      "dPct": 57.3,
      "rPct": 42.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 130,
      "rVotes": 114,
      "total": 244,
      "dPct": 53.3,
      "rPct": 46.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 128,
      "rVotes": 117,
      "total": 245,
      "dPct": 52.2,
      "rPct": 47.8
    }
  },
  {
    "precinct": "BARBERTON 4-C",
    "township": "Barberton",
    "ballotsCast": 354,
    "regVoters": 808,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 139,
      "rVotes": 208,
      "total": 347,
      "dPct": 40.1,
      "rPct": 59.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 176,
      "rVotes": 170,
      "total": 346,
      "dPct": 50.9,
      "rPct": 49.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 166,
      "rVotes": 178,
      "total": 344,
      "dPct": 48.3,
      "rPct": 51.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 152,
      "rVotes": 195,
      "total": 347,
      "dPct": 43.8,
      "rPct": 56.2
    }
  },
  {
    "precinct": "BARBERTON 5-A",
    "township": "Barberton",
    "ballotsCast": 311,
    "regVoters": 756,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 110,
      "rVotes": 193,
      "total": 303,
      "dPct": 36.3,
      "rPct": 63.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 129,
      "rVotes": 175,
      "total": 304,
      "dPct": 42.4,
      "rPct": 57.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 141,
      "rVotes": 163,
      "total": 304,
      "dPct": 46.4,
      "rPct": 53.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 122,
      "rVotes": 182,
      "total": 304,
      "dPct": 40.1,
      "rPct": 59.9
    }
  },
  {
    "precinct": "BARBERTON 5-B",
    "township": "Barberton",
    "ballotsCast": 364,
    "regVoters": 785,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 147,
      "rVotes": 207,
      "total": 354,
      "dPct": 41.5,
      "rPct": 58.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 180,
      "rVotes": 176,
      "total": 356,
      "dPct": 50.6,
      "rPct": 49.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 175,
      "rVotes": 174,
      "total": 349,
      "dPct": 50.1,
      "rPct": 49.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 168,
      "rVotes": 189,
      "total": 357,
      "dPct": 47.1,
      "rPct": 52.9
    }
  },
  {
    "precinct": "BARBERTON 5-C",
    "township": "Barberton",
    "ballotsCast": 298,
    "regVoters": 737,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 120,
      "rVotes": 173,
      "total": 293,
      "dPct": 41,
      "rPct": 59
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 151,
      "rVotes": 142,
      "total": 293,
      "dPct": 51.5,
      "rPct": 48.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 146,
      "rVotes": 143,
      "total": 289,
      "dPct": 50.5,
      "rPct": 49.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 132,
      "rVotes": 160,
      "total": 292,
      "dPct": 45.2,
      "rPct": 54.8
    }
  },
  {
    "precinct": "BARBERTON 6-A",
    "township": "Barberton",
    "ballotsCast": 495,
    "regVoters": 784,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 171,
      "rVotes": 309,
      "total": 480,
      "dPct": 35.6,
      "rPct": 64.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 233,
      "rVotes": 250,
      "total": 483,
      "dPct": 48.2,
      "rPct": 51.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 225,
      "rVotes": 255,
      "total": 480,
      "dPct": 46.9,
      "rPct": 53.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 209,
      "rVotes": 273,
      "total": 482,
      "dPct": 43.4,
      "rPct": 56.6
    }
  },
  {
    "precinct": "BARBERTON 6-B",
    "township": "Barberton",
    "ballotsCast": 308,
    "regVoters": 759,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 93,
      "rVotes": 207,
      "total": 300,
      "dPct": 31,
      "rPct": 69
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 131,
      "rVotes": 171,
      "total": 302,
      "dPct": 43.4,
      "rPct": 56.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 130,
      "rVotes": 167,
      "total": 297,
      "dPct": 43.8,
      "rPct": 56.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 112,
      "rVotes": 181,
      "total": 293,
      "dPct": 38.2,
      "rPct": 61.8
    }
  },
  {
    "precinct": "BARBERTON 6-C",
    "township": "Barberton",
    "ballotsCast": 434,
    "regVoters": 825,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 145,
      "rVotes": 275,
      "total": 420,
      "dPct": 34.5,
      "rPct": 65.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 202,
      "rVotes": 226,
      "total": 428,
      "dPct": 47.2,
      "rPct": 52.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 193,
      "rVotes": 225,
      "total": 418,
      "dPct": 46.2,
      "rPct": 53.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 178,
      "rVotes": 239,
      "total": 417,
      "dPct": 42.7,
      "rPct": 57.3
    }
  },
  {
    "precinct": "BATH TWP A",
    "township": "Bath",
    "ballotsCast": 694,
    "regVoters": 995,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 244,
      "rVotes": 435,
      "total": 679,
      "dPct": 35.9,
      "rPct": 64.1
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 324,
      "rVotes": 362,
      "total": 686,
      "dPct": 47.2,
      "rPct": 52.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 320,
      "rVotes": 351,
      "total": 671,
      "dPct": 47.7,
      "rPct": 52.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 268,
      "rVotes": 409,
      "total": 677,
      "dPct": 39.6,
      "rPct": 60.4
    }
  },
  {
    "precinct": "BATH TWP B",
    "township": "Bath",
    "ballotsCast": 639,
    "regVoters": 929,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 207,
      "rVotes": 413,
      "total": 620,
      "dPct": 33.4,
      "rPct": 66.6
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 272,
      "rVotes": 357,
      "total": 629,
      "dPct": 43.2,
      "rPct": 56.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 260,
      "rVotes": 360,
      "total": 620,
      "dPct": 41.9,
      "rPct": 58.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 231,
      "rVotes": 402,
      "total": 633,
      "dPct": 36.5,
      "rPct": 63.5
    }
  },
  {
    "precinct": "BATH TWP C",
    "township": "Bath",
    "ballotsCast": 830,
    "regVoters": 1214,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 547,
      "total": 817,
      "dPct": 33,
      "rPct": 67
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 367,
      "rVotes": 451,
      "total": 818,
      "dPct": 44.9,
      "rPct": 55.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 350,
      "rVotes": 451,
      "total": 801,
      "dPct": 43.7,
      "rPct": 56.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 277,
      "rVotes": 540,
      "total": 817,
      "dPct": 33.9,
      "rPct": 66.1
    }
  },
  {
    "precinct": "BATH TWP D",
    "township": "Bath",
    "ballotsCast": 670,
    "regVoters": 943,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 307,
      "rVotes": 345,
      "total": 652,
      "dPct": 47.1,
      "rPct": 52.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 382,
      "rVotes": 280,
      "total": 662,
      "dPct": 57.7,
      "rPct": 42.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 366,
      "rVotes": 276,
      "total": 642,
      "dPct": 57,
      "rPct": 43
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 323,
      "rVotes": 333,
      "total": 656,
      "dPct": 49.2,
      "rPct": 50.8
    }
  },
  {
    "precinct": "BATH TWP E",
    "township": "Bath",
    "ballotsCast": 690,
    "regVoters": 967,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 294,
      "rVotes": 379,
      "total": 673,
      "dPct": 43.7,
      "rPct": 56.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 354,
      "rVotes": 325,
      "total": 679,
      "dPct": 52.1,
      "rPct": 47.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 346,
      "rVotes": 330,
      "total": 676,
      "dPct": 51.2,
      "rPct": 48.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 304,
      "rVotes": 374,
      "total": 678,
      "dPct": 44.8,
      "rPct": 55.2
    }
  },
  {
    "precinct": "BATH TWP F",
    "township": "Bath",
    "ballotsCast": 653,
    "regVoters": 924,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 285,
      "rVotes": 355,
      "total": 640,
      "dPct": 44.5,
      "rPct": 55.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 343,
      "rVotes": 306,
      "total": 649,
      "dPct": 52.9,
      "rPct": 47.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 338,
      "rVotes": 304,
      "total": 642,
      "dPct": 52.6,
      "rPct": 47.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 303,
      "rVotes": 340,
      "total": 643,
      "dPct": 47.1,
      "rPct": 52.9
    }
  },
  {
    "precinct": "BATH TWP G",
    "township": "Bath",
    "ballotsCast": 774,
    "regVoters": 1094,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 284,
      "rVotes": 469,
      "total": 753,
      "dPct": 37.7,
      "rPct": 62.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 367,
      "rVotes": 399,
      "total": 766,
      "dPct": 47.9,
      "rPct": 52.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 361,
      "rVotes": 389,
      "total": 750,
      "dPct": 48.1,
      "rPct": 51.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 308,
      "rVotes": 448,
      "total": 756,
      "dPct": 40.7,
      "rPct": 59.3
    }
  },
  {
    "precinct": "BATH TWP H",
    "township": "Bath",
    "ballotsCast": 604,
    "regVoters": 895,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 345,
      "rVotes": 246,
      "total": 591,
      "dPct": 58.4,
      "rPct": 41.6
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 405,
      "rVotes": 189,
      "total": 594,
      "dPct": 68.2,
      "rPct": 31.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 396,
      "rVotes": 193,
      "total": 589,
      "dPct": 67.2,
      "rPct": 32.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 359,
      "rVotes": 235,
      "total": 594,
      "dPct": 60.4,
      "rPct": 39.6
    }
  },
  {
    "precinct": "BOSTON HTS VILL",
    "township": "Boston Heights",
    "ballotsCast": 718,
    "regVoters": 1075,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 220,
      "rVotes": 480,
      "total": 700,
      "dPct": 31.4,
      "rPct": 68.6
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 292,
      "rVotes": 413,
      "total": 705,
      "dPct": 41.4,
      "rPct": 58.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 287,
      "rVotes": 403,
      "total": 690,
      "dPct": 41.6,
      "rPct": 58.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 249,
      "rVotes": 445,
      "total": 694,
      "dPct": 35.9,
      "rPct": 64.1
    }
  },
  {
    "precinct": "BOSTON TWP",
    "township": "Boston Twp",
    "ballotsCast": 360,
    "regVoters": 551,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 150,
      "rVotes": 202,
      "total": 352,
      "dPct": 42.6,
      "rPct": 57.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 175,
      "rVotes": 179,
      "total": 354,
      "dPct": 49.4,
      "rPct": 50.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 170,
      "rVotes": 179,
      "total": 349,
      "dPct": 48.7,
      "rPct": 51.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 158,
      "rVotes": 190,
      "total": 348,
      "dPct": 45.4,
      "rPct": 54.6
    }
  },
  {
    "precinct": "COPLEY TWP A",
    "township": "Copley",
    "ballotsCast": 623,
    "regVoters": 1037,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 333,
      "rVotes": 270,
      "total": 603,
      "dPct": 55.2,
      "rPct": 44.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 394,
      "rVotes": 218,
      "total": 612,
      "dPct": 64.4,
      "rPct": 35.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 387,
      "rVotes": 216,
      "total": 603,
      "dPct": 64.2,
      "rPct": 35.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 361,
      "rVotes": 248,
      "total": 609,
      "dPct": 59.3,
      "rPct": 40.7
    }
  },
  {
    "precinct": "COPLEY TWP B",
    "township": "Copley",
    "ballotsCast": 560,
    "regVoters": 967,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 291,
      "rVotes": 251,
      "total": 542,
      "dPct": 53.7,
      "rPct": 46.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 331,
      "rVotes": 216,
      "total": 547,
      "dPct": 60.5,
      "rPct": 39.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 328,
      "rVotes": 214,
      "total": 542,
      "dPct": 60.5,
      "rPct": 39.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 315,
      "rVotes": 231,
      "total": 546,
      "dPct": 57.7,
      "rPct": 42.3
    }
  },
  {
    "precinct": "COPLEY TWP C",
    "township": "Copley",
    "ballotsCast": 611,
    "regVoters": 1037,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 302,
      "rVotes": 290,
      "total": 592,
      "dPct": 51,
      "rPct": 49
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 356,
      "rVotes": 244,
      "total": 600,
      "dPct": 59.3,
      "rPct": 40.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 355,
      "rVotes": 233,
      "total": 588,
      "dPct": 60.4,
      "rPct": 39.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 328,
      "rVotes": 270,
      "total": 598,
      "dPct": 54.8,
      "rPct": 45.2
    }
  },
  {
    "precinct": "COPLEY TWP D",
    "township": "Copley",
    "ballotsCast": 632,
    "regVoters": 1012,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 229,
      "rVotes": 373,
      "total": 602,
      "dPct": 38,
      "rPct": 62
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 328,
      "total": 617,
      "dPct": 46.8,
      "rPct": 53.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 286,
      "rVotes": 323,
      "total": 609,
      "dPct": 47,
      "rPct": 53
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 251,
      "rVotes": 359,
      "total": 610,
      "dPct": 41.1,
      "rPct": 58.9
    }
  },
  {
    "precinct": "COPLEY TWP E",
    "township": "Copley",
    "ballotsCast": 713,
    "regVoters": 1033,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 252,
      "rVotes": 446,
      "total": 698,
      "dPct": 36.1,
      "rPct": 63.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 323,
      "rVotes": 383,
      "total": 706,
      "dPct": 45.8,
      "rPct": 54.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 309,
      "rVotes": 378,
      "total": 687,
      "dPct": 45,
      "rPct": 55
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 275,
      "rVotes": 411,
      "total": 686,
      "dPct": 40.1,
      "rPct": 59.9
    }
  },
  {
    "precinct": "COPLEY TWP F",
    "township": "Copley",
    "ballotsCast": 830,
    "regVoters": 1353,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 390,
      "rVotes": 426,
      "total": 816,
      "dPct": 47.8,
      "rPct": 52.2
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 488,
      "rVotes": 332,
      "total": 820,
      "dPct": 59.5,
      "rPct": 40.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 482,
      "rVotes": 333,
      "total": 815,
      "dPct": 59.1,
      "rPct": 40.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 413,
      "rVotes": 402,
      "total": 815,
      "dPct": 50.7,
      "rPct": 49.3
    }
  },
  {
    "precinct": "COPLEY TWP G",
    "township": "Copley",
    "ballotsCast": 854,
    "regVoters": 1353,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 395,
      "rVotes": 444,
      "total": 839,
      "dPct": 47.1,
      "rPct": 52.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 493,
      "rVotes": 351,
      "total": 844,
      "dPct": 58.4,
      "rPct": 41.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 485,
      "rVotes": 341,
      "total": 826,
      "dPct": 58.7,
      "rPct": 41.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 443,
      "rVotes": 392,
      "total": 835,
      "dPct": 53.1,
      "rPct": 46.9
    }
  },
  {
    "precinct": "COPLEY TWP H",
    "township": "Copley",
    "ballotsCast": 640,
    "regVoters": 1070,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 291,
      "rVotes": 333,
      "total": 624,
      "dPct": 46.6,
      "rPct": 53.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 365,
      "rVotes": 267,
      "total": 632,
      "dPct": 57.8,
      "rPct": 42.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 356,
      "rVotes": 264,
      "total": 620,
      "dPct": 57.4,
      "rPct": 42.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 308,
      "rVotes": 317,
      "total": 625,
      "dPct": 49.3,
      "rPct": 50.7
    }
  },
  {
    "precinct": "COPLEY TWP I",
    "township": "Copley",
    "ballotsCast": 557,
    "regVoters": 960,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 243,
      "rVotes": 291,
      "total": 534,
      "dPct": 45.5,
      "rPct": 54.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 309,
      "rVotes": 236,
      "total": 545,
      "dPct": 56.7,
      "rPct": 43.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 296,
      "rVotes": 238,
      "total": 534,
      "dPct": 55.4,
      "rPct": 44.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 267,
      "rVotes": 264,
      "total": 531,
      "dPct": 50.3,
      "rPct": 49.7
    }
  },
  {
    "precinct": "COPLEY TWP J",
    "township": "Copley",
    "ballotsCast": 760,
    "regVoters": 1087,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 298,
      "rVotes": 445,
      "total": 743,
      "dPct": 40.1,
      "rPct": 59.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 370,
      "rVotes": 378,
      "total": 748,
      "dPct": 49.5,
      "rPct": 50.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 347,
      "rVotes": 384,
      "total": 731,
      "dPct": 47.5,
      "rPct": 52.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 307,
      "rVotes": 433,
      "total": 740,
      "dPct": 41.5,
      "rPct": 58.5
    }
  },
  {
    "precinct": "COPLEY TWP K",
    "township": "Copley",
    "ballotsCast": 688,
    "regVoters": 1034,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 320,
      "rVotes": 353,
      "total": 673,
      "dPct": 47.5,
      "rPct": 52.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 396,
      "rVotes": 285,
      "total": 681,
      "dPct": 58.1,
      "rPct": 41.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 387,
      "rVotes": 277,
      "total": 664,
      "dPct": 58.3,
      "rPct": 41.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 349,
      "rVotes": 320,
      "total": 669,
      "dPct": 52.2,
      "rPct": 47.8
    }
  },
  {
    "precinct": "COPLEY TWP L",
    "township": "Copley",
    "ballotsCast": 752,
    "regVoters": 1102,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 329,
      "rVotes": 403,
      "total": 732,
      "dPct": 44.9,
      "rPct": 55.1
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 434,
      "rVotes": 306,
      "total": 740,
      "dPct": 58.6,
      "rPct": 41.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 419,
      "rVotes": 312,
      "total": 731,
      "dPct": 57.3,
      "rPct": 42.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 373,
      "rVotes": 352,
      "total": 725,
      "dPct": 51.4,
      "rPct": 48.6
    }
  },
  {
    "precinct": "CUY FALLS 1-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 570,
    "regVoters": 1105,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 292,
      "rVotes": 264,
      "total": 556,
      "dPct": 52.5,
      "rPct": 47.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 341,
      "rVotes": 217,
      "total": 558,
      "dPct": 61.1,
      "rPct": 38.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 347,
      "rVotes": 209,
      "total": 556,
      "dPct": 62.4,
      "rPct": 37.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 337,
      "rVotes": 219,
      "total": 556,
      "dPct": 60.6,
      "rPct": 39.4
    }
  },
  {
    "precinct": "CUY FALLS 1-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 498,
    "regVoters": 1127,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 292,
      "rVotes": 200,
      "total": 492,
      "dPct": 59.3,
      "rPct": 40.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 333,
      "rVotes": 158,
      "total": 491,
      "dPct": 67.8,
      "rPct": 32.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 322,
      "rVotes": 162,
      "total": 484,
      "dPct": 66.5,
      "rPct": 33.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 311,
      "rVotes": 177,
      "total": 488,
      "dPct": 63.7,
      "rPct": 36.3
    }
  },
  {
    "precinct": "CUY FALLS 1-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 440,
    "regVoters": 991,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 222,
      "rVotes": 207,
      "total": 429,
      "dPct": 51.7,
      "rPct": 48.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 271,
      "rVotes": 162,
      "total": 433,
      "dPct": 62.6,
      "rPct": 37.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 262,
      "rVotes": 170,
      "total": 432,
      "dPct": 60.6,
      "rPct": 39.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 258,
      "rVotes": 173,
      "total": 431,
      "dPct": 59.9,
      "rPct": 40.1
    }
  },
  {
    "precinct": "CUY FALLS 1-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 511,
    "regVoters": 955,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 243,
      "rVotes": 255,
      "total": 498,
      "dPct": 48.8,
      "rPct": 51.2
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 294,
      "rVotes": 208,
      "total": 502,
      "dPct": 58.6,
      "rPct": 41.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 288,
      "rVotes": 202,
      "total": 490,
      "dPct": 58.8,
      "rPct": 41.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 283,
      "rVotes": 216,
      "total": 499,
      "dPct": 56.7,
      "rPct": 43.3
    }
  },
  {
    "precinct": "CUY FALLS 2-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 417,
    "regVoters": 878,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 213,
      "rVotes": 192,
      "total": 405,
      "dPct": 52.6,
      "rPct": 47.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 152,
      "total": 415,
      "dPct": 63.4,
      "rPct": 36.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 259,
      "rVotes": 148,
      "total": 407,
      "dPct": 63.6,
      "rPct": 36.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 248,
      "rVotes": 156,
      "total": 404,
      "dPct": 61.4,
      "rPct": 38.6
    }
  },
  {
    "precinct": "CUY FALLS 2-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 415,
    "regVoters": 811,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 220,
      "rVotes": 185,
      "total": 405,
      "dPct": 54.3,
      "rPct": 45.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 265,
      "rVotes": 145,
      "total": 410,
      "dPct": 64.6,
      "rPct": 35.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 257,
      "rVotes": 144,
      "total": 401,
      "dPct": 64.1,
      "rPct": 35.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 254,
      "rVotes": 153,
      "total": 407,
      "dPct": 62.4,
      "rPct": 37.6
    }
  },
  {
    "precinct": "CUY FALLS 2-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 543,
    "regVoters": 842,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 282,
      "rVotes": 239,
      "total": 521,
      "dPct": 54.1,
      "rPct": 45.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 335,
      "rVotes": 201,
      "total": 536,
      "dPct": 62.5,
      "rPct": 37.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 328,
      "rVotes": 204,
      "total": 532,
      "dPct": 61.7,
      "rPct": 38.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 328,
      "rVotes": 206,
      "total": 534,
      "dPct": 61.4,
      "rPct": 38.6
    }
  },
  {
    "precinct": "CUY FALLS 2-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 436,
    "regVoters": 837,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 220,
      "rVotes": 206,
      "total": 426,
      "dPct": 51.6,
      "rPct": 48.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 258,
      "rVotes": 171,
      "total": 429,
      "dPct": 60.1,
      "rPct": 39.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 246,
      "rVotes": 175,
      "total": 421,
      "dPct": 58.4,
      "rPct": 41.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 243,
      "rVotes": 180,
      "total": 423,
      "dPct": 57.4,
      "rPct": 42.6
    }
  },
  {
    "precinct": "CUY FALLS 2-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 461,
    "regVoters": 829,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 236,
      "rVotes": 212,
      "total": 448,
      "dPct": 52.7,
      "rPct": 47.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 287,
      "rVotes": 159,
      "total": 446,
      "dPct": 64.3,
      "rPct": 35.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 271,
      "rVotes": 167,
      "total": 438,
      "dPct": 61.9,
      "rPct": 38.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 178,
      "total": 441,
      "dPct": 59.6,
      "rPct": 40.4
    }
  },
  {
    "precinct": "CUY FALLS 3-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 531,
    "regVoters": 859,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 253,
      "rVotes": 263,
      "total": 516,
      "dPct": 49,
      "rPct": 51
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 311,
      "rVotes": 212,
      "total": 523,
      "dPct": 59.5,
      "rPct": 40.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 310,
      "rVotes": 206,
      "total": 516,
      "dPct": 60.1,
      "rPct": 39.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 300,
      "rVotes": 218,
      "total": 518,
      "dPct": 57.9,
      "rPct": 42.1
    }
  },
  {
    "precinct": "CUY FALLS 3-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 564,
    "regVoters": 829,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 299,
      "rVotes": 253,
      "total": 552,
      "dPct": 54.2,
      "rPct": 45.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 362,
      "rVotes": 196,
      "total": 558,
      "dPct": 64.9,
      "rPct": 35.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 352,
      "rVotes": 193,
      "total": 545,
      "dPct": 64.6,
      "rPct": 35.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 338,
      "rVotes": 213,
      "total": 551,
      "dPct": 61.3,
      "rPct": 38.7
    }
  },
  {
    "precinct": "CUY FALLS 3-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 587,
    "regVoters": 907,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 274,
      "rVotes": 291,
      "total": 565,
      "dPct": 48.5,
      "rPct": 51.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 344,
      "rVotes": 239,
      "total": 583,
      "dPct": 59,
      "rPct": 41
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 336,
      "rVotes": 235,
      "total": 571,
      "dPct": 58.8,
      "rPct": 41.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 314,
      "rVotes": 257,
      "total": 571,
      "dPct": 55,
      "rPct": 45
    }
  },
  {
    "precinct": "CUY FALLS 3-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 570,
    "regVoters": 880,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 291,
      "rVotes": 265,
      "total": 556,
      "dPct": 52.3,
      "rPct": 47.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 334,
      "rVotes": 226,
      "total": 560,
      "dPct": 59.6,
      "rPct": 40.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 328,
      "rVotes": 233,
      "total": 561,
      "dPct": 58.5,
      "rPct": 41.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 314,
      "rVotes": 243,
      "total": 557,
      "dPct": 56.4,
      "rPct": 43.6
    }
  },
  {
    "precinct": "CUY FALLS 3-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 518,
    "regVoters": 918,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 278,
      "rVotes": 230,
      "total": 508,
      "dPct": 54.7,
      "rPct": 45.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 340,
      "rVotes": 170,
      "total": 510,
      "dPct": 66.7,
      "rPct": 33.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 324,
      "rVotes": 178,
      "total": 502,
      "dPct": 64.5,
      "rPct": 35.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 320,
      "rVotes": 183,
      "total": 503,
      "dPct": 63.6,
      "rPct": 36.4
    }
  },
  {
    "precinct": "CUY FALLS 4-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 346,
    "regVoters": 829,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 206,
      "rVotes": 128,
      "total": 334,
      "dPct": 61.7,
      "rPct": 38.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 225,
      "rVotes": 118,
      "total": 343,
      "dPct": 65.6,
      "rPct": 34.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 225,
      "rVotes": 113,
      "total": 338,
      "dPct": 66.6,
      "rPct": 33.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 215,
      "rVotes": 127,
      "total": 342,
      "dPct": 62.9,
      "rPct": 37.1
    }
  },
  {
    "precinct": "CUY FALLS 4-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 457,
    "regVoters": 847,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 227,
      "rVotes": 217,
      "total": 444,
      "dPct": 51.1,
      "rPct": 48.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 184,
      "total": 454,
      "dPct": 59.5,
      "rPct": 40.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 267,
      "rVotes": 177,
      "total": 444,
      "dPct": 60.1,
      "rPct": 39.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 255,
      "rVotes": 195,
      "total": 450,
      "dPct": 56.7,
      "rPct": 43.3
    }
  },
  {
    "precinct": "CUY FALLS 4-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 521,
    "regVoters": 884,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 273,
      "rVotes": 239,
      "total": 512,
      "dPct": 53.3,
      "rPct": 46.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 319,
      "rVotes": 194,
      "total": 513,
      "dPct": 62.2,
      "rPct": 37.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 312,
      "rVotes": 198,
      "total": 510,
      "dPct": 61.2,
      "rPct": 38.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 302,
      "rVotes": 211,
      "total": 513,
      "dPct": 58.9,
      "rPct": 41.1
    }
  },
  {
    "precinct": "CUY FALLS 4-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 488,
    "regVoters": 872,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 255,
      "rVotes": 223,
      "total": 478,
      "dPct": 53.3,
      "rPct": 46.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 301,
      "rVotes": 178,
      "total": 479,
      "dPct": 62.8,
      "rPct": 37.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 295,
      "rVotes": 177,
      "total": 472,
      "dPct": 62.5,
      "rPct": 37.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 293,
      "rVotes": 181,
      "total": 474,
      "dPct": 61.8,
      "rPct": 38.2
    }
  },
  {
    "precinct": "CUY FALLS 4-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 464,
    "regVoters": 821,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 218,
      "rVotes": 234,
      "total": 452,
      "dPct": 48.2,
      "rPct": 51.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 267,
      "rVotes": 189,
      "total": 456,
      "dPct": 58.6,
      "rPct": 41.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 185,
      "total": 448,
      "dPct": 58.7,
      "rPct": 41.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 248,
      "rVotes": 198,
      "total": 446,
      "dPct": 55.6,
      "rPct": 44.4
    }
  },
  {
    "precinct": "CUY FALLS 5-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 295,
    "regVoters": 782,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 143,
      "rVotes": 140,
      "total": 283,
      "dPct": 50.5,
      "rPct": 49.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 179,
      "rVotes": 112,
      "total": 291,
      "dPct": 61.5,
      "rPct": 38.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 169,
      "rVotes": 115,
      "total": 284,
      "dPct": 59.5,
      "rPct": 40.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 174,
      "rVotes": 119,
      "total": 293,
      "dPct": 59.4,
      "rPct": 40.6
    }
  },
  {
    "precinct": "CUY FALLS 5-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 563,
    "regVoters": 782,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 319,
      "total": 549,
      "dPct": 41.9,
      "rPct": 58.1
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 313,
      "rVotes": 242,
      "total": 555,
      "dPct": 56.4,
      "rPct": 43.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 306,
      "rVotes": 241,
      "total": 547,
      "dPct": 55.9,
      "rPct": 44.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 287,
      "rVotes": 261,
      "total": 548,
      "dPct": 52.4,
      "rPct": 47.6
    }
  },
  {
    "precinct": "CUY FALLS 5-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 557,
    "regVoters": 1008,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 267,
      "rVotes": 267,
      "total": 534,
      "dPct": 50,
      "rPct": 50
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 343,
      "rVotes": 204,
      "total": 547,
      "dPct": 62.7,
      "rPct": 37.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 332,
      "rVotes": 205,
      "total": 537,
      "dPct": 61.8,
      "rPct": 38.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 327,
      "rVotes": 222,
      "total": 549,
      "dPct": 59.6,
      "rPct": 40.4
    }
  },
  {
    "precinct": "CUY FALLS 5-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 522,
    "regVoters": 856,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 234,
      "rVotes": 275,
      "total": 509,
      "dPct": 46,
      "rPct": 54
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 311,
      "rVotes": 201,
      "total": 512,
      "dPct": 60.7,
      "rPct": 39.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 300,
      "rVotes": 196,
      "total": 496,
      "dPct": 60.5,
      "rPct": 39.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 285,
      "rVotes": 219,
      "total": 504,
      "dPct": 56.5,
      "rPct": 43.5
    }
  },
  {
    "precinct": "CUY FALLS 5-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 442,
    "regVoters": 872,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 226,
      "rVotes": 206,
      "total": 432,
      "dPct": 52.3,
      "rPct": 47.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 283,
      "rVotes": 150,
      "total": 433,
      "dPct": 65.4,
      "rPct": 34.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 155,
      "total": 425,
      "dPct": 63.5,
      "rPct": 36.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 268,
      "rVotes": 165,
      "total": 433,
      "dPct": 61.9,
      "rPct": 38.1
    }
  },
  {
    "precinct": "CUY FALLS 6-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 482,
    "regVoters": 823,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 206,
      "rVotes": 265,
      "total": 471,
      "dPct": 43.7,
      "rPct": 56.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 244,
      "rVotes": 224,
      "total": 468,
      "dPct": 52.1,
      "rPct": 47.9
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 243,
      "rVotes": 218,
      "total": 461,
      "dPct": 52.7,
      "rPct": 47.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 238,
      "total": 468,
      "dPct": 49.1,
      "rPct": 50.9
    }
  },
  {
    "precinct": "CUY FALLS 6-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 504,
    "regVoters": 839,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 211,
      "rVotes": 280,
      "total": 491,
      "dPct": 43,
      "rPct": 57
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 227,
      "total": 497,
      "dPct": 54.3,
      "rPct": 45.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 220,
      "total": 490,
      "dPct": 55.1,
      "rPct": 44.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 255,
      "rVotes": 239,
      "total": 494,
      "dPct": 51.6,
      "rPct": 48.4
    }
  },
  {
    "precinct": "CUY FALLS 6-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 475,
    "regVoters": 854,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 234,
      "rVotes": 227,
      "total": 461,
      "dPct": 50.8,
      "rPct": 49.2
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 276,
      "rVotes": 192,
      "total": 468,
      "dPct": 59,
      "rPct": 41
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 278,
      "rVotes": 179,
      "total": 457,
      "dPct": 60.8,
      "rPct": 39.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 255,
      "rVotes": 206,
      "total": 461,
      "dPct": 55.3,
      "rPct": 44.7
    }
  },
  {
    "precinct": "CUY FALLS 6-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 437,
    "regVoters": 768,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 225,
      "rVotes": 198,
      "total": 423,
      "dPct": 53.2,
      "rPct": 46.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 266,
      "rVotes": 163,
      "total": 429,
      "dPct": 62,
      "rPct": 38
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 265,
      "rVotes": 158,
      "total": 423,
      "dPct": 62.6,
      "rPct": 37.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 263,
      "rVotes": 161,
      "total": 424,
      "dPct": 62,
      "rPct": 38
    }
  },
  {
    "precinct": "CUY FALLS 6-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 447,
    "regVoters": 792,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 218,
      "rVotes": 215,
      "total": 433,
      "dPct": 50.3,
      "rPct": 49.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 262,
      "rVotes": 171,
      "total": 433,
      "dPct": 60.5,
      "rPct": 39.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 254,
      "rVotes": 176,
      "total": 430,
      "dPct": 59.1,
      "rPct": 40.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 244,
      "rVotes": 187,
      "total": 431,
      "dPct": 56.6,
      "rPct": 43.4
    }
  },
  {
    "precinct": "CUY FALLS 7-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 513,
    "regVoters": 857,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 262,
      "rVotes": 235,
      "total": 497,
      "dPct": 52.7,
      "rPct": 47.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 290,
      "rVotes": 213,
      "total": 503,
      "dPct": 57.7,
      "rPct": 42.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 288,
      "rVotes": 210,
      "total": 498,
      "dPct": 57.8,
      "rPct": 42.2
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 276,
      "rVotes": 228,
      "total": 504,
      "dPct": 54.8,
      "rPct": 45.2
    }
  },
  {
    "precinct": "CUY FALLS 7-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 371,
    "regVoters": 849,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 176,
      "rVotes": 186,
      "total": 362,
      "dPct": 48.6,
      "rPct": 51.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 199,
      "rVotes": 165,
      "total": 364,
      "dPct": 54.7,
      "rPct": 45.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 210,
      "rVotes": 152,
      "total": 362,
      "dPct": 58,
      "rPct": 42
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 167,
      "total": 364,
      "dPct": 54.1,
      "rPct": 45.9
    }
  },
  {
    "precinct": "CUY FALLS 7-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 403,
    "regVoters": 673,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 169,
      "rVotes": 217,
      "total": 386,
      "dPct": 43.8,
      "rPct": 56.2
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 211,
      "rVotes": 183,
      "total": 394,
      "dPct": 53.6,
      "rPct": 46.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 214,
      "rVotes": 169,
      "total": 383,
      "dPct": 55.9,
      "rPct": 44.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 194,
      "total": 391,
      "dPct": 50.4,
      "rPct": 49.6
    }
  },
  {
    "precinct": "CUY FALLS 7-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 427,
    "regVoters": 853,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 193,
      "rVotes": 229,
      "total": 422,
      "dPct": 45.7,
      "rPct": 54.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 230,
      "rVotes": 192,
      "total": 422,
      "dPct": 54.5,
      "rPct": 45.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 229,
      "rVotes": 188,
      "total": 417,
      "dPct": 54.9,
      "rPct": 45.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 222,
      "rVotes": 196,
      "total": 418,
      "dPct": 53.1,
      "rPct": 46.9
    }
  },
  {
    "precinct": "CUY FALLS 7-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 499,
    "regVoters": 825,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 236,
      "rVotes": 253,
      "total": 489,
      "dPct": 48.3,
      "rPct": 51.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 273,
      "rVotes": 223,
      "total": 496,
      "dPct": 55,
      "rPct": 45
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 273,
      "rVotes": 212,
      "total": 485,
      "dPct": 56.3,
      "rPct": 43.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 261,
      "rVotes": 225,
      "total": 486,
      "dPct": 53.7,
      "rPct": 46.3
    }
  },
  {
    "precinct": "CUY FALLS 8-A",
    "township": "Cuyahoga Falls",
    "ballotsCast": 629,
    "regVoters": 996,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 214,
      "rVotes": 394,
      "total": 608,
      "dPct": 35.2,
      "rPct": 64.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 284,
      "rVotes": 338,
      "total": 622,
      "dPct": 45.7,
      "rPct": 54.3
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 276,
      "rVotes": 328,
      "total": 604,
      "dPct": 45.7,
      "rPct": 54.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 252,
      "rVotes": 363,
      "total": 615,
      "dPct": 41,
      "rPct": 59
    }
  },
  {
    "precinct": "CUY FALLS 8-B",
    "township": "Cuyahoga Falls",
    "ballotsCast": 615,
    "regVoters": 967,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 258,
      "rVotes": 334,
      "total": 592,
      "dPct": 43.6,
      "rPct": 56.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 329,
      "rVotes": 278,
      "total": 607,
      "dPct": 54.2,
      "rPct": 45.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 325,
      "rVotes": 275,
      "total": 600,
      "dPct": 54.2,
      "rPct": 45.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 307,
      "rVotes": 288,
      "total": 595,
      "dPct": 51.6,
      "rPct": 48.4
    }
  },
  {
    "precinct": "CUY FALLS 8-C",
    "township": "Cuyahoga Falls",
    "ballotsCast": 708,
    "regVoters": 1072,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 307,
      "rVotes": 391,
      "total": 698,
      "dPct": 44,
      "rPct": 56
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 361,
      "rVotes": 336,
      "total": 697,
      "dPct": 51.8,
      "rPct": 48.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 360,
      "rVotes": 327,
      "total": 687,
      "dPct": 52.4,
      "rPct": 47.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 345,
      "rVotes": 343,
      "total": 688,
      "dPct": 50.1,
      "rPct": 49.9
    }
  },
  {
    "precinct": "CUY FALLS 8-D",
    "township": "Cuyahoga Falls",
    "ballotsCast": 650,
    "regVoters": 935,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 288,
      "rVotes": 345,
      "total": 633,
      "dPct": 45.5,
      "rPct": 54.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 341,
      "rVotes": 304,
      "total": 645,
      "dPct": 52.9,
      "rPct": 47.1
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 323,
      "rVotes": 309,
      "total": 632,
      "dPct": 51.1,
      "rPct": 48.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 319,
      "rVotes": 316,
      "total": 635,
      "dPct": 50.2,
      "rPct": 49.8
    }
  },
  {
    "precinct": "CUY FALLS 8-E",
    "township": "Cuyahoga Falls",
    "ballotsCast": 925,
    "regVoters": 1366,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 357,
      "rVotes": 553,
      "total": 910,
      "dPct": 39.2,
      "rPct": 60.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 440,
      "rVotes": 462,
      "total": 902,
      "dPct": 48.8,
      "rPct": 51.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 441,
      "rVotes": 455,
      "total": 896,
      "dPct": 49.2,
      "rPct": 50.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 414,
      "rVotes": 484,
      "total": 898,
      "dPct": 46.1,
      "rPct": 53.9
    }
  },
  {
    "precinct": "CUY FALLS 8-F",
    "township": "Cuyahoga Falls",
    "ballotsCast": 375,
    "regVoters": 714,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 175,
      "rVotes": 189,
      "total": 364,
      "dPct": 48.1,
      "rPct": 51.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 218,
      "rVotes": 148,
      "total": 366,
      "dPct": 59.6,
      "rPct": 40.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 211,
      "rVotes": 152,
      "total": 363,
      "dPct": 58.1,
      "rPct": 41.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 201,
      "rVotes": 159,
      "total": 360,
      "dPct": 55.8,
      "rPct": 44.2
    }
  },
  {
    "precinct": "NORTON 1-A",
    "township": "Norton",
    "ballotsCast": 423,
    "regVoters": 665,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 121,
      "rVotes": 286,
      "total": 407,
      "dPct": 29.7,
      "rPct": 70.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 164,
      "rVotes": 254,
      "total": 418,
      "dPct": 39.2,
      "rPct": 60.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 158,
      "rVotes": 248,
      "total": 406,
      "dPct": 38.9,
      "rPct": 61.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 131,
      "rVotes": 278,
      "total": 409,
      "dPct": 32,
      "rPct": 68
    }
  },
  {
    "precinct": "NORTON 1-B",
    "township": "Norton",
    "ballotsCast": 414,
    "regVoters": 677,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 134,
      "rVotes": 261,
      "total": 395,
      "dPct": 33.9,
      "rPct": 66.1
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 184,
      "rVotes": 223,
      "total": 407,
      "dPct": 45.2,
      "rPct": 54.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 174,
      "rVotes": 227,
      "total": 401,
      "dPct": 43.4,
      "rPct": 56.6
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 160,
      "rVotes": 243,
      "total": 403,
      "dPct": 39.7,
      "rPct": 60.3
    }
  },
  {
    "precinct": "NORTON 1-C",
    "township": "Norton",
    "ballotsCast": 428,
    "regVoters": 708,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 126,
      "rVotes": 286,
      "total": 412,
      "dPct": 30.6,
      "rPct": 69.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 157,
      "rVotes": 265,
      "total": 422,
      "dPct": 37.2,
      "rPct": 62.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 151,
      "rVotes": 263,
      "total": 414,
      "dPct": 36.5,
      "rPct": 63.5
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 140,
      "rVotes": 277,
      "total": 417,
      "dPct": 33.6,
      "rPct": 66.4
    }
  },
  {
    "precinct": "NORTON 2-A",
    "township": "Norton",
    "ballotsCast": 437,
    "regVoters": 778,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 151,
      "rVotes": 269,
      "total": 420,
      "dPct": 36,
      "rPct": 64
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 190,
      "rVotes": 236,
      "total": 426,
      "dPct": 44.6,
      "rPct": 55.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 190,
      "rVotes": 231,
      "total": 421,
      "dPct": 45.1,
      "rPct": 54.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 165,
      "rVotes": 260,
      "total": 425,
      "dPct": 38.8,
      "rPct": 61.2
    }
  },
  {
    "precinct": "NORTON 2-B",
    "township": "Norton",
    "ballotsCast": 395,
    "regVoters": 606,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 138,
      "rVotes": 244,
      "total": 382,
      "dPct": 36.1,
      "rPct": 63.9
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 171,
      "rVotes": 219,
      "total": 390,
      "dPct": 43.8,
      "rPct": 56.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 167,
      "rVotes": 216,
      "total": 383,
      "dPct": 43.6,
      "rPct": 56.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 147,
      "rVotes": 243,
      "total": 390,
      "dPct": 37.7,
      "rPct": 62.3
    }
  },
  {
    "precinct": "NORTON 2-C",
    "township": "Norton",
    "ballotsCast": 427,
    "regVoters": 703,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 145,
      "rVotes": 272,
      "total": 417,
      "dPct": 34.8,
      "rPct": 65.2
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 180,
      "rVotes": 243,
      "total": 423,
      "dPct": 42.6,
      "rPct": 57.4
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 174,
      "rVotes": 237,
      "total": 411,
      "dPct": 42.3,
      "rPct": 57.7
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 153,
      "rVotes": 268,
      "total": 421,
      "dPct": 36.3,
      "rPct": 63.7
    }
  },
  {
    "precinct": "NORTON 3-A",
    "township": "Norton",
    "ballotsCast": 500,
    "regVoters": 763,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 142,
      "rVotes": 352,
      "total": 494,
      "dPct": 28.7,
      "rPct": 71.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 197,
      "rVotes": 295,
      "total": 492,
      "dPct": 40,
      "rPct": 60
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 193,
      "rVotes": 289,
      "total": 482,
      "dPct": 40,
      "rPct": 60
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 162,
      "rVotes": 323,
      "total": 485,
      "dPct": 33.4,
      "rPct": 66.6
    }
  },
  {
    "precinct": "NORTON 3-B",
    "township": "Norton",
    "ballotsCast": 384,
    "regVoters": 656,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 129,
      "rVotes": 243,
      "total": 372,
      "dPct": 34.7,
      "rPct": 65.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 165,
      "rVotes": 212,
      "total": 377,
      "dPct": 43.8,
      "rPct": 56.2
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 158,
      "rVotes": 209,
      "total": 367,
      "dPct": 43.1,
      "rPct": 56.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 143,
      "rVotes": 235,
      "total": 378,
      "dPct": 37.8,
      "rPct": 62.2
    }
  },
  {
    "precinct": "NORTON 3-C",
    "township": "Norton",
    "ballotsCast": 423,
    "regVoters": 661,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 142,
      "rVotes": 272,
      "total": 414,
      "dPct": 34.3,
      "rPct": 65.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 208,
      "rVotes": 206,
      "total": 414,
      "dPct": 50.2,
      "rPct": 49.8
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 192,
      "rVotes": 216,
      "total": 408,
      "dPct": 47.1,
      "rPct": 52.9
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 177,
      "rVotes": 234,
      "total": 411,
      "dPct": 43.1,
      "rPct": 56.9
    }
  },
  {
    "precinct": "NORTON 4-A",
    "township": "Norton",
    "ballotsCast": 514,
    "regVoters": 959,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 105,
      "rVotes": 388,
      "total": 493,
      "dPct": 21.3,
      "rPct": 78.7
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 179,
      "rVotes": 327,
      "total": 506,
      "dPct": 35.4,
      "rPct": 64.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 164,
      "rVotes": 335,
      "total": 499,
      "dPct": 32.9,
      "rPct": 67.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 136,
      "rVotes": 360,
      "total": 496,
      "dPct": 27.4,
      "rPct": 72.6
    }
  },
  {
    "precinct": "NORTON 4-B",
    "township": "Norton",
    "ballotsCast": 530,
    "regVoters": 937,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 172,
      "rVotes": 338,
      "total": 510,
      "dPct": 33.7,
      "rPct": 66.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 222,
      "rVotes": 301,
      "total": 523,
      "dPct": 42.4,
      "rPct": 57.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 216,
      "rVotes": 291,
      "total": 507,
      "dPct": 42.6,
      "rPct": 57.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 186,
      "rVotes": 328,
      "total": 514,
      "dPct": 36.2,
      "rPct": 63.8
    }
  },
  {
    "precinct": "PENINSULA VILL",
    "township": "Peninsula",
    "ballotsCast": 298,
    "regVoters": 427,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 149,
      "rVotes": 142,
      "total": 291,
      "dPct": 51.2,
      "rPct": 48.8
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 182,
      "rVotes": 114,
      "total": 296,
      "dPct": 61.5,
      "rPct": 38.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 173,
      "rVotes": 120,
      "total": 293,
      "dPct": 59,
      "rPct": 41
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 152,
      "rVotes": 141,
      "total": 293,
      "dPct": 51.9,
      "rPct": 48.1
    }
  },
  {
    "precinct": "RICHFIELD TWP Y",
    "township": "Richfield Township",
    "ballotsCast": 771,
    "regVoters": 1106,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 270,
      "rVotes": 487,
      "total": 757,
      "dPct": 35.7,
      "rPct": 64.3
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 345,
      "rVotes": 417,
      "total": 762,
      "dPct": 45.3,
      "rPct": 54.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 334,
      "rVotes": 414,
      "total": 748,
      "dPct": 44.7,
      "rPct": 55.3
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 289,
      "rVotes": 468,
      "total": 757,
      "dPct": 38.2,
      "rPct": 61.8
    }
  },
  {
    "precinct": "RICHFIELD TWP Z",
    "township": "Richfield Township",
    "ballotsCast": 682,
    "regVoters": 1032,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 212,
      "rVotes": 454,
      "total": 666,
      "dPct": 31.8,
      "rPct": 68.2
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 277,
      "rVotes": 392,
      "total": 669,
      "dPct": 41.4,
      "rPct": 58.6
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 259,
      "rVotes": 395,
      "total": 654,
      "dPct": 39.6,
      "rPct": 60.4
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 233,
      "rVotes": 436,
      "total": 669,
      "dPct": 34.8,
      "rPct": 65.2
    }
  },
  {
    "precinct": "RICHFIELD VILL A",
    "township": "Richfield Village",
    "ballotsCast": 603,
    "regVoters": 951,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 203,
      "rVotes": 386,
      "total": 589,
      "dPct": 34.5,
      "rPct": 65.5
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 257,
      "rVotes": 340,
      "total": 597,
      "dPct": 43,
      "rPct": 57
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 244,
      "rVotes": 325,
      "total": 569,
      "dPct": 42.9,
      "rPct": 57.1
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 217,
      "rVotes": 377,
      "total": 594,
      "dPct": 36.5,
      "rPct": 63.5
    }
  },
  {
    "precinct": "RICHFIELD VILL B",
    "township": "Richfield Village",
    "ballotsCast": 599,
    "regVoters": 940,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 186,
      "rVotes": 402,
      "total": 588,
      "dPct": 31.6,
      "rPct": 68.4
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 242,
      "rVotes": 355,
      "total": 597,
      "dPct": 40.5,
      "rPct": 59.5
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 234,
      "rVotes": 348,
      "total": 582,
      "dPct": 40.2,
      "rPct": 59.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 191,
      "rVotes": 397,
      "total": 588,
      "dPct": 32.5,
      "rPct": 67.5
    }
  },
  {
    "precinct": "RICHFIELD VILL C",
    "township": "Richfield Village",
    "ballotsCast": 700,
    "regVoters": 978,
    "pres": {
      "dName": "",
      "rName": "",
      "dVotes": 243,
      "rVotes": 444,
      "total": 687,
      "dPct": 35.4,
      "rPct": 64.6
    },
    "senate": {
      "dName": "",
      "rName": "",
      "dVotes": 314,
      "rVotes": 379,
      "total": 693,
      "dPct": 45.3,
      "rPct": 54.7
    },
    "uSHouse": {
      "dName": "",
      "rName": "",
      "dVotes": 298,
      "rVotes": 376,
      "total": 674,
      "dPct": 44.2,
      "rPct": 55.8
    },
    "stRep": {
      "dName": "",
      "rName": "",
      "dVotes": 259,
      "rVotes": 433,
      "total": 692,
      "dPct": 37.4,
      "rPct": 62.6
    }
  }
];

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct2022: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData2022.map(p => [p.precinct, p]));

/** Maps GeoJSON PRECINCT code (e.g. "ANO") → human-readable name (e.g. "NORTON A") */
export const oh31PrecinctCodeToName2022: Record<string, string> = {
  "AJA": "BARBERTON 1-A",
  "AJD": "BARBERTON 1-B",
  "AJG": "BARBERTON 2-A",
  "AJH": "BARBERTON 2-B",
  "AJL": "BARBERTON 3-A",
  "AJM": "BARBERTON 3-B",
  "AJO": "BARBERTON 3-C",
  "AJR": "BARBERTON 4-A",
  "AJT": "BARBERTON 4-B",
  "AJV": "BARBERTON 5-A",
  "AJW": "BARBERTON 5-B",
  "AKA": "BARBERTON 6-A",
  "AKC": "BARBERTON 6-B",
  "AKF": "CUY FALLS 1-A",
  "AKG": "CUY FALLS 1-B",
  "AKJ": "CUY FALLS 1-C",
  "AKO": "CUY FALLS 2-A",
  "AKP": "CUY FALLS 2-B",
  "AKS": "CUY FALLS 2-C",
  "AKV": "CUY FALLS 3-A",
  "AKW": "CUY FALLS 3-B",
  "AKZ": "CUY FALLS 3-C",
  "ALA": "CUY FALLS 3-D",
  "ALE": "CUY FALLS 4-A",
  "ALF": "CUY FALLS 4-B",
  "ALH": "CUY FALLS 4-C",
  "ALN": "CUY FALLS 5-A",
  "ALO": "CUY FALLS 5-B",
  "ALP": "CUY FALLS 5-C",
  "ALQ": "CUY FALLS 5-D",
  "ALV": "CUY FALLS 6-A",
  "ALW": "CUY FALLS 6-B",
  "ALY": "CUY FALLS 6-C",
  "AMC": "CUY FALLS 7-A",
  "AME": "CUY FALLS 7-B",
  "AMG": "CUY FALLS 7-C",
  "AMH": "CUY FALLS 7-D",
  "AMJ": "CUY FALLS 8-A",
  "AMK": "CUY FALLS 8-B",
  "AMM": "CUY FALLS 8-C",
  "AMN": "CUY FALLS 8-D",
  "AMO": "CUY FALLS 8-E",
  "ANO": "NORTON 1-A",
  "ANP": "NORTON 1-B",
  "ANS": "NORTON 2-A",
  "ANU": "NORTON 2-B",
  "AOA": "NORTON 3-A",
  "AOC": "NORTON 3-B",
  "ARB": "BATH TWP A",
  "ARD": "BATH TWP B",
  "ARE": "BATH TWP C",
  "ARH": "BATH TWP D",
  "ARI": "BATH TWP E",
  "ARK": "BATH TWP F",
  "ARO": "PENINSULA VILL",
  "ARP": "BOSTON TWP",
  "ARR": "BOSTON HTS VILL",
  "ARW": "COPLEY TWP A",
  "ARX": "COPLEY TWP B",
  "ARY": "COPLEY TWP C",
  "ASD": "COPLEY TWP D",
  "ASE": "COPLEY TWP E",
  "ASF": "COPLEY TWP F",
  "ASG": "COPLEY TWP G",
  "ASH": "COPLEY TWP H",
  "ATE": "NORTON 4-A",
  "ATG": "NORTON 4-B",
  "AUL": "RICHFIELD TWP Y",
  "AUM": "RICHFIELD TWP Z",
  "AUN": "RICHFIELD VILL A",
  "AUQ": "RICHFIELD VILL B",
  "AYH": "COPLEY TWP I",
  "BAB": "BARBERTON 1-C",
  "BAC": "BARBERTON 2-C",
  "BAD": "BARBERTON 4-C",
  "BAE": "BARBERTON 5-C",
  "BAF": "BARBERTON 6-C",
  "BAG": "CUY FALLS 1-D",
  "BAH": "CUY FALLS 2-D",
  "BAI": "CUY FALLS 2-E",
  "BAJ": "CUY FALLS 3-E",
  "BAK": "CUY FALLS 4-D",
  "BAL": "CUY FALLS 4-E",
  "BAM": "CUY FALLS 5-E",
  "BAN": "CUY FALLS 6-D",
  "BAO": "CUY FALLS 6-E",
  "BAP": "CUY FALLS 7-E",
  "BAQ": "CUY FALLS 8-F",
  "BBP": "NORTON 1-C",
  "BBQ": "NORTON 2-C",
  "BBR": "NORTON 3-C",
  "BCK": "RICHFIELD VILL C",
  "BCL": "BATH TWP G",
  "BCM": "BATH TWP H",
  "BCN": "COPLEY TWP J",
  "BCO": "COPLEY TWP K",
  "BCP": "COPLEY TWP L"
};
