// AUTO-GENERATED by data-entry/build-oh31.js — do not edit by hand
// Source: data-entry/ohio_hd31_precinct_results.csv

export interface OH31RaceResult {
  dName:  string;
  rName:  string;
  dVotes: number;
  rVotes: number;
  total:  number;
  dPct:   number;
  rPct:   number;
}

export interface OH31Precinct {
  precinct:    string;
  ballotsCast: number;
  regVoters:   number;
  pres:        OH31RaceResult;
  senate:      OH31RaceResult;
  uSHouse:     OH31RaceResult;
  stRep:       OH31RaceResult;
}

export const oh31PrecinctData: OH31Precinct[] = [
  {
    "precinct": "BARBERTON 1-A",
    "ballotsCast": 600,
    "regVoters": 935,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 226,
      "rVotes": 363,
      "total": 595,
      "dPct": 37.98,
      "rPct": 61.01
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 254,
      "rVotes": 312,
      "total": 589,
      "dPct": 43.12,
      "rPct": 52.97
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 238,
      "rVotes": 342,
      "total": 580,
      "dPct": 41.03,
      "rPct": 58.97
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 213,
      "rVotes": 352,
      "total": 565,
      "dPct": 37.7,
      "rPct": 62.3
    }
  },
  {
    "precinct": "BARBERTON 1-B",
    "ballotsCast": 572,
    "regVoters": 867,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 216,
      "rVotes": 343,
      "total": 569,
      "dPct": 37.96,
      "rPct": 60.28
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 229,
      "rVotes": 312,
      "total": 564,
      "dPct": 40.6,
      "rPct": 55.32
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 234,
      "rVotes": 323,
      "total": 557,
      "dPct": 42.01,
      "rPct": 57.99
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 209,
      "rVotes": 332,
      "total": 541,
      "dPct": 38.63,
      "rPct": 61.37
    }
  },
  {
    "precinct": "BARBERTON 1-C",
    "ballotsCast": 606,
    "regVoters": 873,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 234,
      "rVotes": 363,
      "total": 604,
      "dPct": 38.74,
      "rPct": 60.1
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 262,
      "rVotes": 306,
      "total": 593,
      "dPct": 44.18,
      "rPct": 51.6
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 254,
      "rVotes": 331,
      "total": 585,
      "dPct": 43.42,
      "rPct": 56.58
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 236,
      "rVotes": 340,
      "total": 576,
      "dPct": 40.97,
      "rPct": 59.03
    }
  },
  {
    "precinct": "BARBERTON 2-A",
    "ballotsCast": 572,
    "regVoters": 904,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 259,
      "rVotes": 301,
      "total": 566,
      "dPct": 45.76,
      "rPct": 53.18
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 272,
      "rVotes": 255,
      "total": 557,
      "dPct": 48.83,
      "rPct": 45.78
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 265,
      "rVotes": 282,
      "total": 547,
      "dPct": 48.45,
      "rPct": 51.55
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 242,
      "rVotes": 289,
      "total": 531,
      "dPct": 45.57,
      "rPct": 54.43
    }
  },
  {
    "precinct": "BARBERTON 2-B",
    "ballotsCast": 646,
    "regVoters": 923,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 284,
      "rVotes": 345,
      "total": 641,
      "dPct": 44.31,
      "rPct": 53.82
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 309,
      "rVotes": 285,
      "total": 629,
      "dPct": 49.13,
      "rPct": 45.31
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 296,
      "rVotes": 322,
      "total": 618,
      "dPct": 47.9,
      "rPct": 52.1
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 287,
      "rVotes": 319,
      "total": 606,
      "dPct": 47.36,
      "rPct": 52.64
    }
  },
  {
    "precinct": "BARBERTON 2-C",
    "ballotsCast": 723,
    "regVoters": 944,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 320,
      "rVotes": 383,
      "total": 711,
      "dPct": 45.01,
      "rPct": 53.87
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 351,
      "rVotes": 340,
      "total": 713,
      "dPct": 49.23,
      "rPct": 47.69
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 333,
      "rVotes": 364,
      "total": 697,
      "dPct": 47.78,
      "rPct": 52.22
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 287,
      "rVotes": 401,
      "total": 688,
      "dPct": 41.72,
      "rPct": 58.28
    }
  },
  {
    "precinct": "BARBERTON 3-A",
    "ballotsCast": 725,
    "regVoters": 1148,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 428,
      "rVotes": 281,
      "total": 719,
      "dPct": 59.53,
      "rPct": 39.08
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 443,
      "rVotes": 242,
      "total": 707,
      "dPct": 62.66,
      "rPct": 34.23
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 450,
      "rVotes": 250,
      "total": 700,
      "dPct": 64.29,
      "rPct": 35.71
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 426,
      "rVotes": 264,
      "total": 690,
      "dPct": 61.74,
      "rPct": 38.26
    }
  },
  {
    "precinct": "BARBERTON 3-B",
    "ballotsCast": 652,
    "regVoters": 1019,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 368,
      "rVotes": 272,
      "total": 645,
      "dPct": 57.05,
      "rPct": 42.17
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 378,
      "rVotes": 246,
      "total": 645,
      "dPct": 58.6,
      "rPct": 38.14
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 380,
      "rVotes": 256,
      "total": 636,
      "dPct": 59.75,
      "rPct": 40.25
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 355,
      "rVotes": 262,
      "total": 617,
      "dPct": 57.54,
      "rPct": 42.46
    }
  },
  {
    "precinct": "BARBERTON 3-C",
    "ballotsCast": 859,
    "regVoters": 1027,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 376,
      "rVotes": 456,
      "total": 844,
      "dPct": 44.55,
      "rPct": 54.03
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 400,
      "rVotes": 429,
      "total": 843,
      "dPct": 47.45,
      "rPct": 50.89
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 395,
      "rVotes": 438,
      "total": 833,
      "dPct": 47.42,
      "rPct": 52.58
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 354,
      "rVotes": 447,
      "total": 801,
      "dPct": 44.19,
      "rPct": 55.81
    }
  },
  {
    "precinct": "BARBERTON 4-A",
    "ballotsCast": 658,
    "regVoters": 1195,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 297,
      "rVotes": 351,
      "total": 654,
      "dPct": 45.41,
      "rPct": 53.67
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 307,
      "rVotes": 294,
      "total": 644,
      "dPct": 47.67,
      "rPct": 45.65
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 325,
      "rVotes": 308,
      "total": 633,
      "dPct": 51.34,
      "rPct": 48.66
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 294,
      "rVotes": 319,
      "total": 613,
      "dPct": 47.96,
      "rPct": 52.04
    }
  },
  {
    "precinct": "BARBERTON 4-B",
    "ballotsCast": 772,
    "regVoters": 1173,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 344,
      "rVotes": 409,
      "total": 762,
      "dPct": 45.14,
      "rPct": 53.67
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 378,
      "rVotes": 332,
      "total": 752,
      "dPct": 50.27,
      "rPct": 44.15
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 373,
      "rVotes": 357,
      "total": 730,
      "dPct": 51.1,
      "rPct": 48.9
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 347,
      "rVotes": 369,
      "total": 716,
      "dPct": 48.46,
      "rPct": 51.54
    }
  },
  {
    "precinct": "BARBERTON 5-A",
    "ballotsCast": 775,
    "regVoters": 1179,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 297,
      "rVotes": 458,
      "total": 770,
      "dPct": 38.57,
      "rPct": 59.48
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 339,
      "rVotes": 388,
      "total": 758,
      "dPct": 44.72,
      "rPct": 51.19
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 325,
      "rVotes": 419,
      "total": 744,
      "dPct": 43.68,
      "rPct": 56.32
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 288,
      "rVotes": 440,
      "total": 728,
      "dPct": 39.56,
      "rPct": 60.44
    }
  },
  {
    "precinct": "BARBERTON 5-B",
    "ballotsCast": 732,
    "regVoters": 1167,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 284,
      "rVotes": 436,
      "total": 723,
      "dPct": 39.28,
      "rPct": 60.3
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 296,
      "rVotes": 363,
      "total": 707,
      "dPct": 41.87,
      "rPct": 51.34
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 305,
      "rVotes": 395,
      "total": 700,
      "dPct": 43.57,
      "rPct": 56.43
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 279,
      "rVotes": 400,
      "total": 679,
      "dPct": 41.09,
      "rPct": 58.91
    }
  },
  {
    "precinct": "BARBERTON 6-A",
    "ballotsCast": 827,
    "regVoters": 1245,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 304,
      "rVotes": 508,
      "total": 820,
      "dPct": 37.07,
      "rPct": 61.95
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 324,
      "rVotes": 445,
      "total": 806,
      "dPct": 40.2,
      "rPct": 55.21
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 318,
      "rVotes": 474,
      "total": 792,
      "dPct": 40.15,
      "rPct": 59.85
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 282,
      "rVotes": 480,
      "total": 762,
      "dPct": 37.01,
      "rPct": 62.99
    }
  },
  {
    "precinct": "BARBERTON 6-B",
    "ballotsCast": 963,
    "regVoters": 1231,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 387,
      "rVotes": 554,
      "total": 953,
      "dPct": 40.61,
      "rPct": 58.13
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 421,
      "rVotes": 487,
      "total": 941,
      "dPct": 44.74,
      "rPct": 51.75
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 410,
      "rVotes": 522,
      "total": 932,
      "dPct": 43.99,
      "rPct": 56.01
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 369,
      "rVotes": 534,
      "total": 903,
      "dPct": 40.86,
      "rPct": 59.14
    }
  },
  {
    "precinct": "BATH TWP A",
    "ballotsCast": 860,
    "regVoters": 1021,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 357,
      "rVotes": 475,
      "total": 845,
      "dPct": 42.25,
      "rPct": 56.21
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 375,
      "rVotes": 451,
      "total": 845,
      "dPct": 44.38,
      "rPct": 53.37
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 337,
      "rVotes": 495,
      "total": 832,
      "dPct": 40.5,
      "rPct": 59.5
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 287,
      "rVotes": 539,
      "total": 826,
      "dPct": 34.75,
      "rPct": 65.25
    }
  },
  {
    "precinct": "BATH TWP B",
    "ballotsCast": 829,
    "regVoters": 988,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 351,
      "rVotes": 453,
      "total": 813,
      "dPct": 43.17,
      "rPct": 55.72
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 381,
      "rVotes": 410,
      "total": 813,
      "dPct": 46.86,
      "rPct": 50.43
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 342,
      "rVotes": 462,
      "total": 804,
      "dPct": 42.54,
      "rPct": 57.46
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 291,
      "rVotes": 502,
      "total": 793,
      "dPct": 36.7,
      "rPct": 63.3
    }
  },
  {
    "precinct": "BATH TWP C",
    "ballotsCast": 843,
    "regVoters": 982,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 417,
      "rVotes": 404,
      "total": 837,
      "dPct": 49.82,
      "rPct": 48.27
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 427,
      "rVotes": 395,
      "total": 832,
      "dPct": 51.32,
      "rPct": 47.48
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 406,
      "rVotes": 410,
      "total": 816,
      "dPct": 49.75,
      "rPct": 50.25
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 351,
      "rVotes": 458,
      "total": 809,
      "dPct": 43.39,
      "rPct": 56.61
    }
  },
  {
    "precinct": "BATH TWP D",
    "ballotsCast": 1068,
    "regVoters": 1270,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 496,
      "rVotes": 543,
      "total": 1057,
      "dPct": 46.93,
      "rPct": 51.37
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 515,
      "rVotes": 516,
      "total": 1057,
      "dPct": 48.72,
      "rPct": 48.82
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 463,
      "rVotes": 578,
      "total": 1041,
      "dPct": 44.48,
      "rPct": 55.52
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 427,
      "rVotes": 604,
      "total": 1031,
      "dPct": 41.42,
      "rPct": 58.58
    }
  },
  {
    "precinct": "BATH TWP E",
    "ballotsCast": 788,
    "regVoters": 938,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 392,
      "rVotes": 379,
      "total": 781,
      "dPct": 50.19,
      "rPct": 48.53
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 401,
      "rVotes": 348,
      "total": 769,
      "dPct": 52.15,
      "rPct": 45.25
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 380,
      "rVotes": 385,
      "total": 765,
      "dPct": 49.67,
      "rPct": 50.33
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 331,
      "rVotes": 428,
      "total": 759,
      "dPct": 43.61,
      "rPct": 56.39
    }
  },
  {
    "precinct": "BATH TWP F",
    "ballotsCast": 808,
    "regVoters": 977,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 413,
      "rVotes": 365,
      "total": 796,
      "dPct": 51.88,
      "rPct": 45.85
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 425,
      "rVotes": 355,
      "total": 793,
      "dPct": 53.59,
      "rPct": 44.77
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 400,
      "rVotes": 385,
      "total": 785,
      "dPct": 50.96,
      "rPct": 49.04
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 313,
      "rVotes": 391,
      "total": 704,
      "dPct": 44.46,
      "rPct": 55.54
    }
  },
  {
    "precinct": "BATH TWP G",
    "ballotsCast": 798,
    "regVoters": 973,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 394,
      "rVotes": 388,
      "total": 791,
      "dPct": 49.81,
      "rPct": 49.05
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 394,
      "rVotes": 380,
      "total": 787,
      "dPct": 50.06,
      "rPct": 48.28
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 368,
      "rVotes": 405,
      "total": 773,
      "dPct": 47.61,
      "rPct": 52.39
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 325,
      "rVotes": 446,
      "total": 771,
      "dPct": 42.15,
      "rPct": 57.85
    }
  },
  {
    "precinct": "BATH TWP H",
    "ballotsCast": 807,
    "regVoters": 958,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 495,
      "rVotes": 287,
      "total": 796,
      "dPct": 62.19,
      "rPct": 36.06
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 526,
      "rVotes": 248,
      "total": 791,
      "dPct": 66.5,
      "rPct": 31.35
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 498,
      "rVotes": 291,
      "total": 789,
      "dPct": 63.12,
      "rPct": 36.88
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 17,
      "rVotes": 25,
      "total": 42,
      "dPct": 40.48,
      "rPct": 59.52
    }
  },
  {
    "precinct": "BOSTON HTS VILL",
    "ballotsCast": 923,
    "regVoters": 1102,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 363,
      "rVotes": 529,
      "total": 907,
      "dPct": 40.02,
      "rPct": 58.32
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 391,
      "rVotes": 483,
      "total": 901,
      "dPct": 43.4,
      "rPct": 53.61
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 354,
      "rVotes": 523,
      "total": 877,
      "dPct": 40.36,
      "rPct": 59.64
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 316,
      "rVotes": 551,
      "total": 867,
      "dPct": 36.45,
      "rPct": 63.55
    }
  },
  {
    "precinct": "BOSTON TWP",
    "ballotsCast": 453,
    "regVoters": 592,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 208,
      "rVotes": 234,
      "total": 449,
      "dPct": 46.33,
      "rPct": 52.12
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 214,
      "rVotes": 221,
      "total": 446,
      "dPct": 47.98,
      "rPct": 49.55
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 197,
      "rVotes": 237,
      "total": 434,
      "dPct": 45.39,
      "rPct": 54.61
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 193,
      "rVotes": 230,
      "total": 423,
      "dPct": 45.63,
      "rPct": 54.37
    }
  },
  {
    "precinct": "COPLEY TWP A",
    "ballotsCast": 1036,
    "regVoters": 1303,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 574,
      "rVotes": 434,
      "total": 1020,
      "dPct": 56.27,
      "rPct": 42.55
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 599,
      "rVotes": 406,
      "total": 1021,
      "dPct": 58.67,
      "rPct": 39.76
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 550,
      "rVotes": 448,
      "total": 998,
      "dPct": 55.11,
      "rPct": 44.89
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 487,
      "rVotes": 493,
      "total": 980,
      "dPct": 49.69,
      "rPct": 50.31
    }
  },
  {
    "precinct": "COPLEY TWP B",
    "ballotsCast": 985,
    "regVoters": 1272,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 556,
      "rVotes": 402,
      "total": 974,
      "dPct": 57.08,
      "rPct": 41.27
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 569,
      "rVotes": 371,
      "total": 969,
      "dPct": 58.72,
      "rPct": 38.29
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 531,
      "rVotes": 421,
      "total": 952,
      "dPct": 55.78,
      "rPct": 44.22
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 480,
      "rVotes": 456,
      "total": 936,
      "dPct": 51.28,
      "rPct": 48.72
    }
  },
  {
    "precinct": "COPLEY TWP C",
    "ballotsCast": 847,
    "regVoters": 1149,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 443,
      "rVotes": 375,
      "total": 834,
      "dPct": 53.12,
      "rPct": 44.96
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 462,
      "rVotes": 338,
      "total": 823,
      "dPct": 56.14,
      "rPct": 41.07
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 428,
      "rVotes": 376,
      "total": 804,
      "dPct": 53.23,
      "rPct": 46.77
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 390,
      "rVotes": 393,
      "total": 783,
      "dPct": 49.81,
      "rPct": 50.19
    }
  },
  {
    "precinct": "COPLEY TWP D",
    "ballotsCast": 876,
    "regVoters": 1045,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 497,
      "rVotes": 353,
      "total": 867,
      "dPct": 57.32,
      "rPct": 40.72
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 506,
      "rVotes": 322,
      "total": 851,
      "dPct": 59.46,
      "rPct": 37.84
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 475,
      "rVotes": 360,
      "total": 835,
      "dPct": 56.89,
      "rPct": 43.11
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 414,
      "rVotes": 409,
      "total": 823,
      "dPct": 50.3,
      "rPct": 49.7
    }
  },
  {
    "precinct": "COPLEY TWP E",
    "ballotsCast": 892,
    "regVoters": 1075,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 509,
      "rVotes": 362,
      "total": 881,
      "dPct": 57.78,
      "rPct": 41.09
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 538,
      "rVotes": 315,
      "total": 877,
      "dPct": 61.35,
      "rPct": 35.92
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 501,
      "rVotes": 365,
      "total": 866,
      "dPct": 57.85,
      "rPct": 42.15
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 441,
      "rVotes": 413,
      "total": 854,
      "dPct": 51.64,
      "rPct": 48.36
    }
  },
  {
    "precinct": "COPLEY TWP F",
    "ballotsCast": 897,
    "regVoters": 1180,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 485,
      "rVotes": 389,
      "total": 886,
      "dPct": 54.74,
      "rPct": 43.91
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 505,
      "rVotes": 351,
      "total": 881,
      "dPct": 57.32,
      "rPct": 39.84
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 492,
      "rVotes": 382,
      "total": 874,
      "dPct": 56.29,
      "rPct": 43.71
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 436,
      "rVotes": 422,
      "total": 858,
      "dPct": 50.82,
      "rPct": 49.18
    }
  },
  {
    "precinct": "COPLEY TWP G",
    "ballotsCast": 908,
    "regVoters": 1059,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 420,
      "rVotes": 465,
      "total": 899,
      "dPct": 46.72,
      "rPct": 51.72
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 445,
      "rVotes": 420,
      "total": 890,
      "dPct": 50,
      "rPct": 47.19
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 422,
      "rVotes": 460,
      "total": 882,
      "dPct": 47.85,
      "rPct": 52.15
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 370,
      "rVotes": 501,
      "total": 871,
      "dPct": 42.48,
      "rPct": 57.52
    }
  },
  {
    "precinct": "COPLEY TWP H",
    "ballotsCast": 888,
    "regVoters": 1088,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 427,
      "rVotes": 439,
      "total": 877,
      "dPct": 48.69,
      "rPct": 50.06
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 447,
      "rVotes": 399,
      "total": 873,
      "dPct": 51.2,
      "rPct": 45.7
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 444,
      "rVotes": 417,
      "total": 861,
      "dPct": 51.57,
      "rPct": 48.43
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 388,
      "rVotes": 450,
      "total": 838,
      "dPct": 46.3,
      "rPct": 53.7
    }
  },
  {
    "precinct": "COPLEY TWP I",
    "ballotsCast": 881,
    "regVoters": 1094,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 475,
      "rVotes": 391,
      "total": 871,
      "dPct": 54.54,
      "rPct": 44.89
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 485,
      "rVotes": 351,
      "total": 859,
      "dPct": 56.46,
      "rPct": 40.86
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 473,
      "rVotes": 379,
      "total": 852,
      "dPct": 55.52,
      "rPct": 44.48
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 441,
      "rVotes": 395,
      "total": 836,
      "dPct": 52.75,
      "rPct": 47.25
    }
  },
  {
    "precinct": "COPLEY TWP J",
    "ballotsCast": 844,
    "regVoters": 1129,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 516,
      "rVotes": 311,
      "total": 837,
      "dPct": 61.65,
      "rPct": 37.16
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 527,
      "rVotes": 269,
      "total": 829,
      "dPct": 63.57,
      "rPct": 32.45
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 524,
      "rVotes": 288,
      "total": 812,
      "dPct": 64.53,
      "rPct": 35.47
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 492,
      "rVotes": 301,
      "total": 793,
      "dPct": 62.04,
      "rPct": 37.96
    }
  },
  {
    "precinct": "COPLEY TWP K",
    "ballotsCast": 865,
    "regVoters": 1092,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 494,
      "rVotes": 356,
      "total": 859,
      "dPct": 57.51,
      "rPct": 41.44
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 516,
      "rVotes": 301,
      "total": 848,
      "dPct": 60.85,
      "rPct": 35.5
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 509,
      "rVotes": 331,
      "total": 840,
      "dPct": 60.6,
      "rPct": 39.4
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 457,
      "rVotes": 359,
      "total": 816,
      "dPct": 56,
      "rPct": 44
    }
  },
  {
    "precinct": "COPLEY TWP L",
    "ballotsCast": 849,
    "regVoters": 1033,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 309,
      "rVotes": 528,
      "total": 845,
      "dPct": 36.57,
      "rPct": 62.49
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 330,
      "rVotes": 483,
      "total": 832,
      "dPct": 39.66,
      "rPct": 58.05
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 312,
      "rVotes": 505,
      "total": 817,
      "dPct": 38.19,
      "rPct": 61.81
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 275,
      "rVotes": 532,
      "total": 807,
      "dPct": 34.08,
      "rPct": 65.92
    }
  },
  {
    "precinct": "CUY FALLS 1-A",
    "ballotsCast": 761,
    "regVoters": 1129,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 399,
      "rVotes": 343,
      "total": 757,
      "dPct": 52.71,
      "rPct": 45.31
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 421,
      "rVotes": 280,
      "total": 737,
      "dPct": 57.12,
      "rPct": 37.99
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 414,
      "rVotes": 320,
      "total": 734,
      "dPct": 56.4,
      "rPct": 43.6
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 405,
      "rVotes": 304,
      "total": 709,
      "dPct": 57.12,
      "rPct": 42.88
    }
  },
  {
    "precinct": "CUY FALLS 1-B",
    "ballotsCast": 829,
    "regVoters": 1123,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 427,
      "rVotes": 388,
      "total": 823,
      "dPct": 51.88,
      "rPct": 47.14
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 438,
      "rVotes": 327,
      "total": 806,
      "dPct": 54.34,
      "rPct": 40.57
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 436,
      "rVotes": 360,
      "total": 796,
      "dPct": 54.77,
      "rPct": 45.23
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 413,
      "rVotes": 359,
      "total": 772,
      "dPct": 53.5,
      "rPct": 46.5
    }
  },
  {
    "precinct": "CUY FALLS 1-C",
    "ballotsCast": 737,
    "regVoters": 1090,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 429,
      "rVotes": 291,
      "total": 731,
      "dPct": 58.69,
      "rPct": 39.81
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 440,
      "rVotes": 250,
      "total": 710,
      "dPct": 61.97,
      "rPct": 35.21
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 432,
      "rVotes": 275,
      "total": 707,
      "dPct": 61.1,
      "rPct": 38.9
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 403,
      "rVotes": 287,
      "total": 690,
      "dPct": 58.41,
      "rPct": 41.59
    }
  },
  {
    "precinct": "CUY FALLS 1-D",
    "ballotsCast": 797,
    "regVoters": 1132,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 485,
      "rVotes": 300,
      "total": 792,
      "dPct": 61.24,
      "rPct": 37.88
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 489,
      "rVotes": 250,
      "total": 766,
      "dPct": 63.84,
      "rPct": 32.64
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 478,
      "rVotes": 280,
      "total": 758,
      "dPct": 63.06,
      "rPct": 36.94
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 455,
      "rVotes": 278,
      "total": 733,
      "dPct": 62.07,
      "rPct": 37.93
    }
  },
  {
    "precinct": "CUY FALLS 2-A",
    "ballotsCast": 922,
    "regVoters": 1139,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 516,
      "rVotes": 388,
      "total": 914,
      "dPct": 56.46,
      "rPct": 42.45
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 532,
      "rVotes": 329,
      "total": 901,
      "dPct": 59.05,
      "rPct": 36.51
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 526,
      "rVotes": 361,
      "total": 887,
      "dPct": 59.3,
      "rPct": 40.7
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 507,
      "rVotes": 366,
      "total": 873,
      "dPct": 58.08,
      "rPct": 41.92
    }
  },
  {
    "precinct": "CUY FALLS 2-B",
    "ballotsCast": 810,
    "regVoters": 1151,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 434,
      "rVotes": 343,
      "total": 795,
      "dPct": 54.59,
      "rPct": 43.14
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 451,
      "rVotes": 296,
      "total": 790,
      "dPct": 57.09,
      "rPct": 37.47
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 456,
      "rVotes": 317,
      "total": 773,
      "dPct": 58.99,
      "rPct": 41.01
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 421,
      "rVotes": 341,
      "total": 762,
      "dPct": 55.25,
      "rPct": 44.75
    }
  },
  {
    "precinct": "CUY FALLS 2-C",
    "ballotsCast": 920,
    "regVoters": 1137,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 542,
      "rVotes": 348,
      "total": 908,
      "dPct": 59.69,
      "rPct": 38.33
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 567,
      "rVotes": 302,
      "total": 905,
      "dPct": 62.65,
      "rPct": 33.37
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 547,
      "rVotes": 347,
      "total": 894,
      "dPct": 61.19,
      "rPct": 38.81
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 524,
      "rVotes": 347,
      "total": 871,
      "dPct": 60.16,
      "rPct": 39.84
    }
  },
  {
    "precinct": "CUY FALLS 2-D",
    "ballotsCast": 805,
    "regVoters": 1136,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 477,
      "rVotes": 305,
      "total": 799,
      "dPct": 59.7,
      "rPct": 38.17
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 496,
      "rVotes": 253,
      "total": 781,
      "dPct": 63.51,
      "rPct": 32.39
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 478,
      "rVotes": 279,
      "total": 757,
      "dPct": 63.14,
      "rPct": 36.86
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 460,
      "rVotes": 285,
      "total": 745,
      "dPct": 61.74,
      "rPct": 38.26
    }
  },
  {
    "precinct": "CUY FALLS 3-A",
    "ballotsCast": 814,
    "regVoters": 1020,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 419,
      "rVotes": 363,
      "total": 798,
      "dPct": 52.51,
      "rPct": 45.49
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 447,
      "rVotes": 322,
      "total": 804,
      "dPct": 55.6,
      "rPct": 40.05
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 426,
      "rVotes": 363,
      "total": 789,
      "dPct": 53.99,
      "rPct": 46.01
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 389,
      "rVotes": 383,
      "total": 772,
      "dPct": 50.39,
      "rPct": 49.61
    }
  },
  {
    "precinct": "CUY FALLS 3-B",
    "ballotsCast": 736,
    "regVoters": 1024,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 407,
      "rVotes": 313,
      "total": 724,
      "dPct": 56.22,
      "rPct": 43.23
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 419,
      "rVotes": 272,
      "total": 711,
      "dPct": 58.93,
      "rPct": 38.26
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 387,
      "rVotes": 310,
      "total": 697,
      "dPct": 55.52,
      "rPct": 44.48
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 368,
      "rVotes": 308,
      "total": 676,
      "dPct": 54.44,
      "rPct": 45.56
    }
  },
  {
    "precinct": "CUY FALLS 3-C",
    "ballotsCast": 757,
    "regVoters": 988,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 440,
      "rVotes": 301,
      "total": 752,
      "dPct": 58.51,
      "rPct": 40.03
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 446,
      "rVotes": 265,
      "total": 740,
      "dPct": 60.27,
      "rPct": 35.81
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 461,
      "rVotes": 282,
      "total": 743,
      "dPct": 62.05,
      "rPct": 37.95
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 421,
      "rVotes": 302,
      "total": 723,
      "dPct": 58.23,
      "rPct": 41.77
    }
  },
  {
    "precinct": "CUY FALLS 3-D",
    "ballotsCast": 840,
    "regVoters": 1008,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 456,
      "rVotes": 370,
      "total": 832,
      "dPct": 54.81,
      "rPct": 44.47
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 475,
      "rVotes": 334,
      "total": 830,
      "dPct": 57.23,
      "rPct": 40.24
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 458,
      "rVotes": 359,
      "total": 817,
      "dPct": 56.06,
      "rPct": 43.94
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 432,
      "rVotes": 371,
      "total": 803,
      "dPct": 53.8,
      "rPct": 46.2
    }
  },
  {
    "precinct": "CUY FALLS 3-E",
    "ballotsCast": 831,
    "regVoters": 995,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 503,
      "rVotes": 317,
      "total": 827,
      "dPct": 60.82,
      "rPct": 38.33
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 506,
      "rVotes": 285,
      "total": 816,
      "dPct": 62.01,
      "rPct": 34.93
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 486,
      "rVotes": 322,
      "total": 808,
      "dPct": 60.15,
      "rPct": 39.85
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 470,
      "rVotes": 325,
      "total": 795,
      "dPct": 59.12,
      "rPct": 40.88
    }
  },
  {
    "precinct": "CUY FALLS 4-A",
    "ballotsCast": 845,
    "regVoters": 1097,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 433,
      "rVotes": 389,
      "total": 835,
      "dPct": 51.86,
      "rPct": 46.59
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 456,
      "rVotes": 329,
      "total": 823,
      "dPct": 55.41,
      "rPct": 39.98
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 440,
      "rVotes": 363,
      "total": 803,
      "dPct": 54.79,
      "rPct": 45.21
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 426,
      "rVotes": 356,
      "total": 782,
      "dPct": 54.48,
      "rPct": 45.52
    }
  },
  {
    "precinct": "CUY FALLS 4-B",
    "ballotsCast": 865,
    "regVoters": 1117,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 483,
      "rVotes": 355,
      "total": 851,
      "dPct": 56.76,
      "rPct": 41.72
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 505,
      "rVotes": 315,
      "total": 849,
      "dPct": 59.48,
      "rPct": 37.1
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 500,
      "rVotes": 335,
      "total": 835,
      "dPct": 59.88,
      "rPct": 40.12
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 468,
      "rVotes": 343,
      "total": 811,
      "dPct": 57.71,
      "rPct": 42.29
    }
  },
  {
    "precinct": "CUY FALLS 4-C",
    "ballotsCast": 896,
    "regVoters": 1107,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 444,
      "rVotes": 428,
      "total": 884,
      "dPct": 50.23,
      "rPct": 48.42
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 481,
      "rVotes": 364,
      "total": 882,
      "dPct": 54.54,
      "rPct": 41.27
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 465,
      "rVotes": 406,
      "total": 871,
      "dPct": 53.39,
      "rPct": 46.61
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 434,
      "rVotes": 415,
      "total": 849,
      "dPct": 51.12,
      "rPct": 48.88
    }
  },
  {
    "precinct": "CUY FALLS 4-D",
    "ballotsCast": 878,
    "regVoters": 1096,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 495,
      "rVotes": 356,
      "total": 870,
      "dPct": 56.9,
      "rPct": 40.92
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 527,
      "rVotes": 291,
      "total": 858,
      "dPct": 61.42,
      "rPct": 33.92
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 504,
      "rVotes": 346,
      "total": 850,
      "dPct": 59.29,
      "rPct": 40.71
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 463,
      "rVotes": 359,
      "total": 822,
      "dPct": 56.33,
      "rPct": 43.67
    }
  },
  {
    "precinct": "CUY FALLS 5-A",
    "ballotsCast": 618,
    "regVoters": 1027,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 383,
      "rVotes": 217,
      "total": 608,
      "dPct": 62.99,
      "rPct": 35.69
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 387,
      "rVotes": 189,
      "total": 604,
      "dPct": 64.07,
      "rPct": 31.29
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 397,
      "rVotes": 207,
      "total": 604,
      "dPct": 65.73,
      "rPct": 34.27
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 362,
      "rVotes": 215,
      "total": 577,
      "dPct": 62.74,
      "rPct": 37.26
    }
  },
  {
    "precinct": "CUY FALLS 5-B",
    "ballotsCast": 939,
    "regVoters": 1181,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 501,
      "rVotes": 413,
      "total": 925,
      "dPct": 54.16,
      "rPct": 44.65
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 529,
      "rVotes": 371,
      "total": 924,
      "dPct": 57.25,
      "rPct": 40.15
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 498,
      "rVotes": 402,
      "total": 900,
      "dPct": 55.33,
      "rPct": 44.67
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 443,
      "rVotes": 425,
      "total": 868,
      "dPct": 51.04,
      "rPct": 48.96
    }
  },
  {
    "precinct": "CUY FALLS 5-C",
    "ballotsCast": 804,
    "regVoters": 1090,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 450,
      "rVotes": 327,
      "total": 787,
      "dPct": 57.18,
      "rPct": 41.55
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 470,
      "rVotes": 299,
      "total": 794,
      "dPct": 59.19,
      "rPct": 37.66
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 459,
      "rVotes": 325,
      "total": 784,
      "dPct": 58.55,
      "rPct": 41.45
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 414,
      "rVotes": 355,
      "total": 769,
      "dPct": 53.84,
      "rPct": 46.16
    }
  },
  {
    "precinct": "CUY FALLS 5-D",
    "ballotsCast": 799,
    "regVoters": 1023,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 439,
      "rVotes": 343,
      "total": 792,
      "dPct": 55.43,
      "rPct": 43.31
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 450,
      "rVotes": 300,
      "total": 779,
      "dPct": 57.77,
      "rPct": 38.51
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 435,
      "rVotes": 330,
      "total": 765,
      "dPct": 56.86,
      "rPct": 43.14
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 415,
      "rVotes": 347,
      "total": 762,
      "dPct": 54.46,
      "rPct": 45.54
    }
  },
  {
    "precinct": "CUY FALLS 6-A",
    "ballotsCast": 816,
    "regVoters": 1057,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 412,
      "rVotes": 387,
      "total": 809,
      "dPct": 50.93,
      "rPct": 47.84
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 437,
      "rVotes": 335,
      "total": 800,
      "dPct": 54.62,
      "rPct": 41.88
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 418,
      "rVotes": 367,
      "total": 785,
      "dPct": 53.25,
      "rPct": 46.75
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 401,
      "rVotes": 363,
      "total": 764,
      "dPct": 52.49,
      "rPct": 47.51
    }
  },
  {
    "precinct": "CUY FALLS 6-B",
    "ballotsCast": 902,
    "regVoters": 1131,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 444,
      "rVotes": 438,
      "total": 894,
      "dPct": 49.66,
      "rPct": 48.99
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 470,
      "rVotes": 378,
      "total": 886,
      "dPct": 53.05,
      "rPct": 42.66
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 452,
      "rVotes": 409,
      "total": 861,
      "dPct": 52.5,
      "rPct": 47.5
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 413,
      "rVotes": 436,
      "total": 849,
      "dPct": 48.65,
      "rPct": 51.35
    }
  },
  {
    "precinct": "CUY FALLS 6-C",
    "ballotsCast": 790,
    "regVoters": 1051,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 413,
      "rVotes": 362,
      "total": 783,
      "dPct": 52.75,
      "rPct": 46.23
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 445,
      "rVotes": 295,
      "total": 767,
      "dPct": 58.02,
      "rPct": 38.46
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 412,
      "rVotes": 337,
      "total": 749,
      "dPct": 55.01,
      "rPct": 44.99
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 382,
      "rVotes": 350,
      "total": 732,
      "dPct": 52.19,
      "rPct": 47.81
    }
  },
  {
    "precinct": "CUY FALLS 6-D",
    "ballotsCast": 812,
    "regVoters": 1050,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 460,
      "rVotes": 336,
      "total": 804,
      "dPct": 57.21,
      "rPct": 41.79
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 472,
      "rVotes": 283,
      "total": 791,
      "dPct": 59.67,
      "rPct": 35.78
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 458,
      "rVotes": 322,
      "total": 780,
      "dPct": 58.72,
      "rPct": 41.28
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 432,
      "rVotes": 334,
      "total": 766,
      "dPct": 56.4,
      "rPct": 43.6
    }
  },
  {
    "precinct": "CUY FALLS 7-A",
    "ballotsCast": 720,
    "regVoters": 1077,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 437,
      "rVotes": 268,
      "total": 717,
      "dPct": 60.95,
      "rPct": 37.38
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 448,
      "rVotes": 224,
      "total": 707,
      "dPct": 63.37,
      "rPct": 31.68
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 447,
      "rVotes": 246,
      "total": 693,
      "dPct": 64.5,
      "rPct": 35.5
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 429,
      "rVotes": 246,
      "total": 675,
      "dPct": 63.56,
      "rPct": 36.44
    }
  },
  {
    "precinct": "CUY FALLS 7-B",
    "ballotsCast": 789,
    "regVoters": 1053,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 403,
      "rVotes": 370,
      "total": 782,
      "dPct": 51.53,
      "rPct": 47.31
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 411,
      "rVotes": 324,
      "total": 772,
      "dPct": 53.24,
      "rPct": 41.97
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 403,
      "rVotes": 363,
      "total": 766,
      "dPct": 52.61,
      "rPct": 47.39
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 392,
      "rVotes": 360,
      "total": 752,
      "dPct": 52.13,
      "rPct": 47.87
    }
  },
  {
    "precinct": "CUY FALLS 7-C",
    "ballotsCast": 846,
    "regVoters": 1132,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 413,
      "rVotes": 416,
      "total": 836,
      "dPct": 49.4,
      "rPct": 49.76
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 436,
      "rVotes": 357,
      "total": 823,
      "dPct": 52.98,
      "rPct": 43.38
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 429,
      "rVotes": 386,
      "total": 815,
      "dPct": 52.64,
      "rPct": 47.36
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 397,
      "rVotes": 391,
      "total": 788,
      "dPct": 50.38,
      "rPct": 49.62
    }
  },
  {
    "precinct": "CUY FALLS 7-D",
    "ballotsCast": 872,
    "regVoters": 1109,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 404,
      "rVotes": 444,
      "total": 861,
      "dPct": 46.92,
      "rPct": 51.57
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 439,
      "rVotes": 372,
      "total": 848,
      "dPct": 51.77,
      "rPct": 43.87
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 412,
      "rVotes": 412,
      "total": 824,
      "dPct": 50,
      "rPct": 50
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 382,
      "rVotes": 421,
      "total": 803,
      "dPct": 47.57,
      "rPct": 52.43
    }
  },
  {
    "precinct": "CUY FALLS 8-A",
    "ballotsCast": 858,
    "regVoters": 1001,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 412,
      "rVotes": 432,
      "total": 853,
      "dPct": 48.3,
      "rPct": 50.64
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 423,
      "rVotes": 384,
      "total": 835,
      "dPct": 50.66,
      "rPct": 45.99
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 406,
      "rVotes": 410,
      "total": 816,
      "dPct": 49.75,
      "rPct": 50.25
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 360,
      "rVotes": 410,
      "total": 770,
      "dPct": 46.75,
      "rPct": 53.25
    }
  },
  {
    "precinct": "CUY FALLS 8-B",
    "ballotsCast": 864,
    "regVoters": 1079,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 426,
      "rVotes": 399,
      "total": 843,
      "dPct": 50.53,
      "rPct": 47.33
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 446,
      "rVotes": 376,
      "total": 844,
      "dPct": 52.84,
      "rPct": 44.55
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 421,
      "rVotes": 407,
      "total": 828,
      "dPct": 50.85,
      "rPct": 49.15
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 385,
      "rVotes": 419,
      "total": 804,
      "dPct": 47.89,
      "rPct": 52.11
    }
  },
  {
    "precinct": "CUY FALLS 8-C",
    "ballotsCast": 820,
    "regVoters": 992,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 338,
      "rVotes": 466,
      "total": 811,
      "dPct": 41.68,
      "rPct": 57.46
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 361,
      "rVotes": 415,
      "total": 803,
      "dPct": 44.96,
      "rPct": 51.68
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 328,
      "rVotes": 459,
      "total": 787,
      "dPct": 41.68,
      "rPct": 58.32
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 295,
      "rVotes": 469,
      "total": 764,
      "dPct": 38.61,
      "rPct": 61.39
    }
  },
  {
    "precinct": "CUY FALLS 8-D",
    "ballotsCast": 881,
    "regVoters": 1058,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 440,
      "rVotes": 413,
      "total": 868,
      "dPct": 50.69,
      "rPct": 47.58
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 452,
      "rVotes": 386,
      "total": 860,
      "dPct": 52.56,
      "rPct": 44.88
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 445,
      "rVotes": 411,
      "total": 856,
      "dPct": 51.99,
      "rPct": 48.01
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 404,
      "rVotes": 417,
      "total": 821,
      "dPct": 49.21,
      "rPct": 50.79
    }
  },
  {
    "precinct": "CUY FALLS 8-E",
    "ballotsCast": 837,
    "regVoters": 1031,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 375,
      "rVotes": 436,
      "total": 822,
      "dPct": 45.62,
      "rPct": 53.04
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 403,
      "rVotes": 405,
      "total": 820,
      "dPct": 49.15,
      "rPct": 49.39
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 354,
      "rVotes": 452,
      "total": 806,
      "dPct": 43.92,
      "rPct": 56.08
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 329,
      "rVotes": 462,
      "total": 791,
      "dPct": 41.59,
      "rPct": 58.41
    }
  },
  {
    "precinct": "NORTON 1-A",
    "ballotsCast": 857,
    "regVoters": 1051,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 265,
      "rVotes": 571,
      "total": 848,
      "dPct": 31.25,
      "rPct": 67.33
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 292,
      "rVotes": 509,
      "total": 843,
      "dPct": 34.64,
      "rPct": 60.38
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 284,
      "rVotes": 541,
      "total": 825,
      "dPct": 34.42,
      "rPct": 65.58
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 235,
      "rVotes": 573,
      "total": 808,
      "dPct": 29.08,
      "rPct": 70.92
    }
  },
  {
    "precinct": "NORTON 1-B",
    "ballotsCast": 842,
    "regVoters": 1017,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 319,
      "rVotes": 510,
      "total": 838,
      "dPct": 38.07,
      "rPct": 60.86
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 336,
      "rVotes": 445,
      "total": 817,
      "dPct": 41.13,
      "rPct": 54.47
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 322,
      "rVotes": 482,
      "total": 804,
      "dPct": 40.05,
      "rPct": 59.95
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 288,
      "rVotes": 496,
      "total": 784,
      "dPct": 36.73,
      "rPct": 63.27
    }
  },
  {
    "precinct": "NORTON 2-A",
    "ballotsCast": 757,
    "regVoters": 992,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 277,
      "rVotes": 466,
      "total": 751,
      "dPct": 36.88,
      "rPct": 62.05
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 296,
      "rVotes": 403,
      "total": 735,
      "dPct": 40.27,
      "rPct": 54.83
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 297,
      "rVotes": 418,
      "total": 715,
      "dPct": 41.54,
      "rPct": 58.46
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 265,
      "rVotes": 436,
      "total": 701,
      "dPct": 37.8,
      "rPct": 62.2
    }
  },
  {
    "precinct": "NORTON 2-B",
    "ballotsCast": 1037,
    "regVoters": 1235,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 411,
      "rVotes": 608,
      "total": 1029,
      "dPct": 39.94,
      "rPct": 59.09
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 443,
      "rVotes": 550,
      "total": 1018,
      "dPct": 43.52,
      "rPct": 54.03
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 431,
      "rVotes": 567,
      "total": 998,
      "dPct": 43.19,
      "rPct": 56.81
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 368,
      "rVotes": 624,
      "total": 992,
      "dPct": 37.1,
      "rPct": 62.9
    }
  },
  {
    "precinct": "NORTON 3-A",
    "ballotsCast": 1050,
    "regVoters": 1221,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 378,
      "rVotes": 638,
      "total": 1033,
      "dPct": 36.59,
      "rPct": 61.76
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 418,
      "rVotes": 569,
      "total": 1030,
      "dPct": 40.58,
      "rPct": 55.24
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 388,
      "rVotes": 617,
      "total": 1005,
      "dPct": 38.61,
      "rPct": 61.39
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 336,
      "rVotes": 642,
      "total": 978,
      "dPct": 34.36,
      "rPct": 65.64
    }
  },
  {
    "precinct": "NORTON 3-B",
    "ballotsCast": 872,
    "regVoters": 1082,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 347,
      "rVotes": 507,
      "total": 866,
      "dPct": 40.07,
      "rPct": 58.55
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 369,
      "rVotes": 455,
      "total": 857,
      "dPct": 43.06,
      "rPct": 53.09
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 361,
      "rVotes": 480,
      "total": 841,
      "dPct": 42.93,
      "rPct": 57.07
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 302,
      "rVotes": 517,
      "total": 819,
      "dPct": 36.87,
      "rPct": 63.13
    }
  },
  {
    "precinct": "NORTON 4-A",
    "ballotsCast": 702,
    "regVoters": 927,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 231,
      "rVotes": 460,
      "total": 700,
      "dPct": 33,
      "rPct": 65.71
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 248,
      "rVotes": 409,
      "total": 691,
      "dPct": 35.89,
      "rPct": 59.19
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 238,
      "rVotes": 439,
      "total": 677,
      "dPct": 35.16,
      "rPct": 64.84
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 225,
      "rVotes": 440,
      "total": 665,
      "dPct": 33.83,
      "rPct": 66.17
    }
  },
  {
    "precinct": "NORTON 4-B",
    "ballotsCast": 758,
    "regVoters": 972,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 214,
      "rVotes": 534,
      "total": 755,
      "dPct": 28.34,
      "rPct": 70.73
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 248,
      "rVotes": 465,
      "total": 742,
      "dPct": 33.42,
      "rPct": 62.67
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 221,
      "rVotes": 493,
      "total": 714,
      "dPct": 30.95,
      "rPct": 69.05
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 195,
      "rVotes": 506,
      "total": 701,
      "dPct": 27.82,
      "rPct": 72.18
    }
  },
  {
    "precinct": "PENINSULA VILL",
    "ballotsCast": 358,
    "regVoters": 434,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 206,
      "rVotes": 145,
      "total": 355,
      "dPct": 58.03,
      "rPct": 40.85
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 220,
      "rVotes": 127,
      "total": 353,
      "dPct": 62.32,
      "rPct": 35.98
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 211,
      "rVotes": 132,
      "total": 343,
      "dPct": 61.52,
      "rPct": 38.48
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 180,
      "rVotes": 152,
      "total": 332,
      "dPct": 54.22,
      "rPct": 45.78
    }
  },
  {
    "precinct": "RICHFIELD TWP Y",
    "ballotsCast": 901,
    "regVoters": 1056,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 351,
      "rVotes": 530,
      "total": 889,
      "dPct": 39.48,
      "rPct": 59.62
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 353,
      "rVotes": 509,
      "total": 878,
      "dPct": 40.21,
      "rPct": 57.97
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 323,
      "rVotes": 536,
      "total": 859,
      "dPct": 37.6,
      "rPct": 62.4
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 271,
      "rVotes": 589,
      "total": 860,
      "dPct": 31.51,
      "rPct": 68.49
    }
  },
  {
    "precinct": "RICHFIELD TWP Z",
    "ballotsCast": 962,
    "regVoters": 1142,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 412,
      "rVotes": 524,
      "total": 948,
      "dPct": 43.46,
      "rPct": 55.27
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 429,
      "rVotes": 487,
      "total": 940,
      "dPct": 45.64,
      "rPct": 51.81
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 380,
      "rVotes": 532,
      "total": 912,
      "dPct": 41.67,
      "rPct": 58.33
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 335,
      "rVotes": 589,
      "total": 924,
      "dPct": 36.26,
      "rPct": 63.74
    }
  },
  {
    "precinct": "RICHFIELD VILL A",
    "ballotsCast": 783,
    "regVoters": 946,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 310,
      "rVotes": 451,
      "total": 773,
      "dPct": 40.1,
      "rPct": 58.34
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 321,
      "rVotes": 421,
      "total": 755,
      "dPct": 42.52,
      "rPct": 55.76
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 281,
      "rVotes": 451,
      "total": 732,
      "dPct": 38.39,
      "rPct": 61.61
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 241,
      "rVotes": 492,
      "total": 733,
      "dPct": 32.88,
      "rPct": 67.12
    }
  },
  {
    "precinct": "RICHFIELD VILL B",
    "ballotsCast": 923,
    "regVoters": 1073,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 382,
      "rVotes": 518,
      "total": 910,
      "dPct": 41.98,
      "rPct": 56.92
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 423,
      "rVotes": 464,
      "total": 906,
      "dPct": 46.69,
      "rPct": 51.21
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 375,
      "rVotes": 505,
      "total": 880,
      "dPct": 42.61,
      "rPct": 57.39
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 304,
      "rVotes": 570,
      "total": 874,
      "dPct": 34.78,
      "rPct": 65.22
    }
  },
  {
    "precinct": "RICHFIELD VILL C",
    "ballotsCast": 843,
    "regVoters": 1022,
    "pres": {
      "dName": "Kamala Harris",
      "rName": "Donald J. Trump",
      "dVotes": 318,
      "rVotes": 510,
      "total": 838,
      "dPct": 37.95,
      "rPct": 60.86
    },
    "senate": {
      "dName": "Sherrod Brown",
      "rName": "Bernie Moreno",
      "dVotes": 352,
      "rVotes": 453,
      "total": 830,
      "dPct": 42.41,
      "rPct": 54.58
    },
    "uSHouse": {
      "dName": "Emilia Sykes",
      "rName": "Kevin Coughlin",
      "dVotes": 323,
      "rVotes": 479,
      "total": 802,
      "dPct": 40.27,
      "rPct": 59.73
    },
    "stRep": {
      "dName": "A. J. Harris",
      "rName": "Bill Roemer",
      "dVotes": 282,
      "rVotes": 529,
      "total": 811,
      "dPct": 34.77,
      "rPct": 65.23
    }
  }
];

/** Lookup map: precinct name → OH31Precinct */
export const oh31ByPrecinct: Record<string, OH31Precinct> =
  Object.fromEntries(oh31PrecinctData.map(p => [p.precinct, p]));
