// GENERATED by `npx tsx scripts/tplBacktest.ts --emit` — do not edit by hand.
// The 2024 holdout behind the Validation table on /methodology/state-tpl: each predictor is built from
// information through 2022 and scored on 2024 after removing a uniform national shift.
export const TPL_VALIDATION = {
  "generatedAt": "2026-09-21",
  "pass": true,
  "rows": [
    {
      "target": "2024 President",
      "predictor": "TPL holdout (full NM pipeline)",
      "n": 50,
      "mae": 2.5,
      "r": 0.988,
      "shift": 0.95
    },
    {
      "target": "2024 President",
      "predictor": "Adjusted only (no IF/CQ/WA)",
      "n": 50,
      "mae": 2.92,
      "r": 0.987,
      "shift": 1.51
    },
    {
      "target": "2024 President",
      "predictor": "Raw, clipped ±50",
      "n": 50,
      "mae": 3.16,
      "r": 0.984,
      "shift": 1.65
    },
    {
      "target": "2024 President",
      "predictor": "2020 presidential alone",
      "n": 50,
      "mae": 1.93,
      "r": 0.994,
      "shift": 4.05
    },
    {
      "target": "2024 Senate",
      "predictor": "TPL holdout (full NM pipeline)",
      "n": 33,
      "mae": 4.9,
      "r": 0.949,
      "shift": -0.39
    },
    {
      "target": "2024 Senate",
      "predictor": "Adjusted only (no IF/CQ/WA)",
      "n": 33,
      "mae": 4.98,
      "r": 0.95,
      "shift": -0.14
    },
    {
      "target": "2024 Senate",
      "predictor": "Raw, clipped ±50",
      "n": 33,
      "mae": 5,
      "r": 0.949,
      "shift": 0
    },
    {
      "target": "2024 Senate",
      "predictor": "2020 presidential alone",
      "n": 33,
      "mae": 4.95,
      "r": 0.947,
      "shift": 1.38
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "TPL holdout (full NM pipeline)",
      "n": 50,
      "mae": 3.01,
      "r": 0.989,
      "shift": 0.14
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "Adjusted only (no IF/CQ/WA)",
      "n": 50,
      "mae": 2.51,
      "r": 0.989,
      "shift": 0.88
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "Raw, clipped ±50",
      "n": 50,
      "mae": 2.69,
      "r": 0.988,
      "shift": 0.94
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "2020 presidential alone",
      "n": 50,
      "mae": 2.79,
      "r": 0.985,
      "shift": 3.41
    }
  ]
} as const;
