// GENERATED by `npx tsx scripts/tplBacktest.ts --emit` — do not edit by hand.
// The 2024 holdout behind the Validation table on /methodology/state-tpl: each predictor is built from
// information through 2022 and scored on 2024 after removing a uniform national shift.
export const TPL_VALIDATION = {
  "generatedAt": "2026-09-22",
  "pass": true,
  "rows": [
    {
      "target": "2024 President",
      "predictor": "TPL holdout (full NM pipeline)",
      "n": 50,
      "mae": 2.46,
      "r": 0.988,
      "shift": 1.43
    },
    {
      "target": "2024 President",
      "predictor": "Adjusted only (no IF/CQ/WA)",
      "n": 50,
      "mae": 2.6,
      "r": 0.988,
      "shift": 2.37
    },
    {
      "target": "2024 President",
      "predictor": "Raw, clipped ±50",
      "n": 50,
      "mae": 2.78,
      "r": 0.985,
      "shift": 2.02
    },
    {
      "target": "2024 President",
      "predictor": "2020 presidential alone",
      "n": 50,
      "mae": 1.93,
      "r": 0.994,
      "shift": 4.05
    },
    {
      "target": "2024 Senate",
      "predictor": "TPL holdout (full NM pipeline)",
      "n": 33,
      "mae": 5.02,
      "r": 0.948,
      "shift": -0.21
    },
    {
      "target": "2024 Senate",
      "predictor": "Adjusted only (no IF/CQ/WA)",
      "n": 33,
      "mae": 4.97,
      "r": 0.948,
      "shift": 0.82
    },
    {
      "target": "2024 Senate",
      "predictor": "Raw, clipped ±50",
      "n": 33,
      "mae": 5.01,
      "r": 0.948,
      "shift": 0.82
    },
    {
      "target": "2024 Senate",
      "predictor": "2020 presidential alone",
      "n": 33,
      "mae": 4.95,
      "r": 0.947,
      "shift": 1.38
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "TPL holdout (full NM pipeline)",
      "n": 50,
      "mae": 3.06,
      "r": 0.989,
      "shift": 1.47
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "Adjusted only (no IF/CQ/WA)",
      "n": 50,
      "mae": 2.36,
      "r": 0.991,
      "shift": 1.54
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "Raw, clipped ±50",
      "n": 50,
      "mae": 2.54,
      "r": 0.991,
      "shift": 1.34
    },
    {
      "target": "2024 House avg (adjusted)",
      "predictor": "2020 presidential alone",
      "n": 50,
      "mae": 2.79,
      "r": 0.985,
      "shift": 3.41
    }
  ]
} as const;
