// Auto-generated by scripts/turnoutBacktest.ts --emit — do not edit by hand.
// The 2026 turnout estimate's backtest (2022 predicted from 2018 and the 2020 presidential vote)
// and the SHRINK_VOTES grid, read by components/methodology/TurnoutMethodology.tsx.
export const TURNOUT_BACKTEST = {
  "generated": "2026-10-04",
  "target": 2022,
  "basis": 2018,
  "state": {
    "n": 50,
    "mape": 0.08053398842696134,
    "bias": 0.061606372398907594,
    "worst": [
      {
        "state": "ND",
        "office": "senate",
        "predicted": 309131.23716411233,
        "actual": 240140,
        "error": 0.28729589890943763
      },
      {
        "state": "TN",
        "office": "governor",
        "predicted": 2164395.8224677467,
        "actual": 1739932,
        "error": 0.2439542594007964
      },
      {
        "state": "MS",
        "office": "house",
        "predicted": 873527.274321518,
        "actual": 709100,
        "error": 0.23188164479131013
      },
      {
        "state": "IN",
        "office": "senate",
        "predicted": 2215263.9917389113,
        "actual": 1860154,
        "error": 0.1909035444048779
      },
      {
        "state": "CA",
        "office": "governor",
        "predicted": 12931145.26958379,
        "actual": 10933018,
        "error": 0.18276081403906863
      },
      {
        "state": "MO",
        "office": "senate",
        "predicted": 2414882.2882763464,
        "actual": 2069130,
        "error": 0.1671003215246729
      }
    ]
  },
  "noCompetitiveness": {
    "state": {
      "mape": 0.08975417502597624,
      "bias": 0.0743357537483681
    },
    "district": {
      "n": 393,
      "mape": 0.12350355467711617,
      "bias": 0.10612094948302864
    },
    "county": {
      "n": 3140,
      "mape": 0.09443048064152798,
      "weightedMape": 0.09855128334734642,
      "bias": 0.06146818231839496
    }
  },
  "county": {
    "n": 3140,
    "mape": 0.08542545257668967,
    "weightedMape": 0.09098598935546383,
    "bias": 0.0477717455207566
  },
  "countyShare": {
    "n": 3140,
    "weightedMape": 0.043906938917471654
  },
  "district": {
    "n": 393,
    "mape": 0.1144635250942061,
    "bias": 0.09767372941969103
  },
  "ticket": {
    "others": -0.0817737011252001,
    "switchers": [
      {
        "state": "DE",
        "from": "statewide",
        "to": "House only",
        "change": -0.17779858567825205
      },
      {
        "state": "KY",
        "from": "House only",
        "to": "statewide",
        "change": -0.07819366054813372
      },
      {
        "state": "LA",
        "from": "House only",
        "to": "statewide",
        "change": -0.05612327826982593
      },
      {
        "state": "MS",
        "from": "statewide",
        "to": "House only",
        "change": -0.28958131552023275
      },
      {
        "state": "MT",
        "from": "statewide",
        "to": "House only",
        "change": -0.13943911401414777
      },
      {
        "state": "NC",
        "from": "House only",
        "to": "statewide",
        "change": -0.012663717215839093
      },
      {
        "state": "NJ",
        "from": "statewide",
        "to": "House only",
        "change": -0.24266766423434175
      },
      {
        "state": "VA",
        "from": "statewide",
        "to": "House only",
        "change": -0.13137617765090676
      },
      {
        "state": "WV",
        "from": "statewide",
        "to": "House only",
        "change": -0.20175651950830692
      }
    ],
    "estimate": 0.9159320772076303
  },
  "grid": [
    {
      "k": 0,
      "countyShare": 0.045186121289879116,
      "county": 0.09185994688213106,
      "district": 0.11557602932537367
    },
    {
      "k": 2000,
      "countyShare": 0.04464777913337852,
      "county": 0.09139812878656786,
      "district": 0.11538535881301488
    },
    {
      "k": 5000,
      "countyShare": 0.04429482185933792,
      "county": 0.09114655075054241,
      "district": 0.11518381046814703
    },
    {
      "k": 10000,
      "countyShare": 0.04405280209115808,
      "county": 0.09101340437308421,
      "district": 0.11490613434526178
    },
    {
      "k": 20000,
      "countyShare": 0.043906938917471654,
      "county": 0.09098598935546383,
      "district": 0.1144635250942061
    },
    {
      "k": 50000,
      "countyShare": 0.04411144049993142,
      "county": 0.09123487657955899,
      "district": 0.1135514523816939
    },
    {
      "k": 100000,
      "countyShare": 0.04464770689706158,
      "county": 0.09165312268174601,
      "district": 0.11259958145917522
    },
    {
      "k": 1000000000,
      "countyShare": 0.05227220264095228,
      "county": 0.09545223008619237,
      "district": 0.1133190587642674
    }
  ],
  "liveShrink": 20000,
  "national": {
    "houseVotes": 110357321,
    "low": 106223515,
    "high": 116383547,
    "cvap": 240327046,
    "rate": 45.9,
    "basis": [
      {
        "year": 2018,
        "houseVotes": 113662891,
        "topVotes": 116851374,
        "cvap": 228407007
      },
      {
        "year": 2022,
        "houseVotes": 107661224,
        "topVotes": 110571248,
        "cvap": 237630249
      }
    ]
  }
} as const;
