#!/usr/bin/env python3
"""
Generates data/presByBoundaryVintage.ts from data-entry/pres_by_boundary_vintage.csv
(built by scripts/build-pres-by-boundary-vintage.py — see that script's docstring for the
sources and for why this table exists at all).

Run from project root: python3 scripts/generate-pres-by-boundary-vintage.py
"""
import csv, os
from collections import defaultdict

SRC = os.path.join(os.path.dirname(__file__), "../data-entry/pres_by_boundary_vintage.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/presByBoundaryVintage.ts")

by_vintage = defaultdict(dict)
pres_year = {}
for r in csv.DictReader(open(SRC)):
    v = int(r["boundary_year"])
    pres_year[v] = int(r["pres_year"])
    by_vintage[v][r["district_id"]] = (r["district_name"], float(r["dem_pct"]),
                                       float(r["rep_pct"]), float(r["margin"]))

vintages = sorted(by_vintage)

out = [
    "// Auto-generated by scripts/generate-pres-by-boundary-vintage.py — do not edit by hand.",
    "// Source: data-entry/pres_by_boundary_vintage.csv (see scripts/build-pres-by-boundary-vintage.py).",
    "//",
    "// The SAME presidential election measured on each congressional map actually used from",
    "// 2016 to 2024, so a House race can be relocated onto today's lines:",
    "//",
    "//   adjHouseMargin(Y) = houseMargin(Y) − [ presP(lines used in Y) − presP(2026 lines) ]",
    "//",
    "// The 2026-lines side of that subtraction is data/districtPresidentialData.ts. Without",
    "// the adjustment a pre-redistricting House race cannot enter District TPL at all, which",
    "// is why 183 districts are currently presidential-only.",
    "//",
    "// Percentages and margins are PERCENT OF TOTAL VOTE (third parties included), matching",
    "// every other margin in the TPL model. Margins are R-positive.",
    "// Keys are district_id (state FIPS + district, no leading zeros), the same key",
    "// districtPresidentialData uses. DC's delegate district is 1198.",
    "//",
    "// A district number that did not exist in a given cycle is simply absent (TX-38 has no",
    "// 2016-lines row; CA-53 has no 2024-lines row) — and correspondingly has no House race",
    "// from that era, so the lookup is never needed for it.",
    "",
    "export type BoundaryVintage = " + " | ".join(str(v) for v in vintages) + ";",
    "",
    "export type VintagePresResult = {",
    "  code: string;    // e.g. 'PA-07' AS NUMBERED IN THAT CYCLE",
    "  demPct: number;",
    "  repPct: number;",
    "  margin: number;  // R-positive, percent of total vote",
    "};",
    "",
    "/** Which presidential election is measured on each map — the one contemporaneous with",
    " *  the House races that ran on it. 2016 and 2018 House races are both scored against",
    " *  2016, 2020 and 2022 against 2020, 2024 against 2024. */",
    "export const PRES_YEAR_FOR_VINTAGE: Record<BoundaryVintage, number> = {",
]
for v in vintages:
    out.append(f"  {v}: {pres_year[v]},")
out += [
    "};",
    "",
    "/** The congressional map a House election year was run on. Returns null outside the",
    " *  covered range; 2026 races need no adjustment because 2026 IS the reference map. */",
    "export function boundaryVintageForHouseYear(year: number): BoundaryVintage | null {",
    "  " + " ".join(f"if (year === {v}) return {v};" for v in vintages),
    "  return null;",
    "}",
    "",
    "export const presByBoundaryVintage: Record<BoundaryVintage, Record<string, VintagePresResult>> = {",
]
for v in vintages:
    out.append(f"  {v}: {{")
    for did, (code, d, r, m) in sorted(by_vintage[v].items(), key=lambda kv: kv[1][0]):
        out.append(f'    "{did}": {{ code: "{code}", demPct: {d}, repPct: {r}, margin: {m} }},')
    out.append("  },")
out += [
    "};",
    "",
    "/** Presidential margin for a district on the map used in `houseYear`, or null if that",
    " *  district did not exist then. Pair with districtPresidentialData for the 2026 side. */",
    "export function presMarginOnHouseYearLines(districtId: string, houseYear: number): number | null {",
    "  const vintage = boundaryVintageForHouseYear(houseYear);",
    "  if (vintage == null) return null;",
    "  return presByBoundaryVintage[vintage][districtId]?.margin ?? null;",
    "}",
    "",
]

with open(DST, "w") as f:
    f.write("\n".join(out))

total = sum(len(by_vintage[v]) for v in vintages)
print(f"Written {total} rows across {len(vintages)} vintages → {DST}")
for v in vintages:
    print(f"  {v} lines / {pres_year[v]} pres: {len(by_vintage[v])} districts")
