#!/usr/bin/env python3
"""
Generates data/countySenateData.ts by merging every data-entry/county_senate_results_{year}.csv
found on disk (each scraped from Wikipedia's per-state "By county" tables - see
scripts/scrape-county-senate-{year}.py). Margins are R-positive (positive = R advantage),
matching lib/colorScale.ts's convention.
Run from project root: python3 scripts/generate-county-senate-data.py
"""
import csv, glob, os, re
from collections import defaultdict

SRC_GLOB = os.path.join(os.path.dirname(__file__), "../data-entry/county_senate_results_*.csv")
SPECIAL_SRC_GLOB = os.path.join(os.path.dirname(__file__), "../data-entry/county_senate_special_results_*.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/countySenateData.ts")

SRC_FILES = sorted(glob.glob(SRC_GLOB))
SPECIAL_SRC_FILES = sorted(glob.glob(SPECIAL_SRC_GLOB))
YEARS = sorted(int(re.search(r"_(\d{4})\.csv$", f).group(1)) for f in SRC_FILES)

def share_pct(a, total):
    return round(a / total * 100, 2) if total else 0.0

def load_into(dst_key, src_files, counties):
    for path in src_files:
        year = int(re.search(r"_(\d{4})\.csv$", path).group(1))
        with open(path, newline="") as f:
            for r in csv.DictReader(f):
                fips = r["county_id"]
                entry = counties.setdefault(fips, {"state": r["state"], "countyName": r["county_name"], "years": {}, "specialYears": {}})
                dem, gop, oth, total = int(r[f"dem_{year}"]), int(r[f"gop_{year}"]), int(r[f"oth_{year}"]), int(r[f"total_{year}"])
                dem_pct, rep_pct = share_pct(dem, total), share_pct(gop, total)
                entry[dst_key][year] = {
                    "dem": dem, "gop": gop, "oth": oth, "total": total,
                    "demPct": dem_pct, "repPct": rep_pct,
                    "margin": round(rep_pct - dem_pct, 2),
                }

counties = {}
load_into("years", SRC_FILES, counties)
load_into("specialYears", SPECIAL_SRC_FILES, counties)

out = [
    "// Auto-generated by scripts/generate-county-senate-data.py",
    "// Source: data-entry/county_senate_results_{year}.csv, scraped from Wikipedia's per-state",
    "// \"By county\" tables (scripts/scrape-county-senate-{year}.py) and cross-validated against",
    "// data-entry/senate_past_results.csv's state-level totals. Margins are R-positive",
    "// (positive = R advantage). Key = 5-digit county FIPS. Only states with a Senate race",
    "// that year are present; states without one that cycle simply have no entry for it.",
    f"// Years covered: {', '.join(str(y) for y in YEARS)}.",
    "// CA 2016 and 2018 are both same-party top-two general elections (2016: Harris vs.",
    "// Sanchez; 2018: Feinstein vs. de Leon - both years all-Democrat, per",
    "// senate_past_results.csv's trailing \"(D)\" marker on the rep_candidate column) -",
    "// scrape-county-senate-{2016,2018}.py exclude CA on purpose (doesn't fit their two-party",
    "// model); filled separately via scripts/fetch-county-senate-ca-samedem.py, which buckets",
    "// BOTH candidates' votes as dem (gop=0 for every CA county, matching how the map should",
    "// read a same-party race - solid Democratic, not an ordinary two-party contest).",
    "// Verified against senate_past_results.csv's total_votes: exact match, 0% diff, both years.",
    "// Known gaps: NY 2024 undercounts the Democratic column by ~540k votes (fusion voting -",
    "// Wikipedia's table only shows the Democratic ballot line, not the combined total used",
    "// in senate_past_results.csv); MO 2024 is missing Dallas County (absent from the Wikipedia",
    "// source table itself); most other states run <1% (often <0.1%) under the certified state",
    "// total, likely uncounted absentee/overseas ballots reported only at the state level.",
    "// 2022 has no county-level source table at all for IA, KS, KY, LA, MO, NC, OK -",
    "// those states' Wikipedia Senate pages lack a \"By county\" section for that year (confirmed",
    "// by manual inspection, not a scraper bug). AK 2016/2020/2022 ARE included though -",
    "// Alaska has no by-county breakdown in ANY source's normal reporting since it has no",
    "// counties, but was reconstructed from the state's official election data instead; see",
    "// data-entry/README-ak-cvr-reconstructions.md. 2016/2020 predate AK's RCV system (plain",
    "// plurality, matches certified within ~0.5%). 2022 uses ROUND-1 (first-choice) vote",
    "// shares for Chesbro (dem) / Murkowski (rep) specifically, matching how",
    "// senate_past_results.csv already stores this race (the true final RCV round was",
    "// Murkowski vs. Tshibaka - both Republicans - so a final-round number wouldn't be a",
    "// meaningful D-vs-R comparison). Because of that, 2022's \"oth\" bucket is unusually",
    "// large in some counties (Tshibaka's own round-1 share), which pulls demPct+repPct",
    "// noticeably below 100 there (share-of-total, not two-party) more than a typical race -",
    "// a real property of the underlying contest, not a data error.",
    "// specialYears covers states that held a SEPARATE special Senate election the same year",
    "// as a regular one (MN/MS 2018, GA/AZ 2020 - AZ had a special ONLY, no regular AZ race",
    "// that year, so all of AZ's 2020 data lives here, not in `years` - OK 2022, NE 2024),",
    "// sourced from data-entry/county_senate_special_results_{year}.csv (see",
    "// scripts/scrape-county-senate-{year}-special.py / fill-county-senate-{year}-special-medsl.py).",
    "// GA 2020's special race is ~1-2% over senate_past_results.csv's certified runoff total -",
    "// verified this is a genuine discrepancy between Wikipedia's own by-county table and that",
    "// same article's infobox summary (not a parsing bug - county count and per-county numbers",
    "// are all internally consistent), same tolerance class as this file's other <2% gaps.",
    "",
    "export type CountyYearResult = {",
    "  demVotes: number; repVotes: number; othVotes: number; totalVotes: number;",
    "  demPct: number; repPct: number; // share of totalVotes (D+R+Other all sum to 100)",
    "  margin: number; // R-positive (repPct - demPct)",
    "};",
    "export type CountySenateResult = {",
    "  state: string;",
    "  countyName: string;",
    "  years: Partial<Record<number, CountyYearResult>>;",
    "  specialYears: Partial<Record<number, CountyYearResult>>;",
    "};",
    "",
    "export const countySenateData: Record<string, CountySenateResult> = {",
]

def fmt_years(years: dict) -> str:
    return ", ".join(
        f'{y}: {{ demVotes: {v["dem"]}, repVotes: {v["gop"]}, othVotes: {v["oth"]}, totalVotes: {v["total"]}, '
        f'demPct: {v["demPct"]}, repPct: {v["repPct"]}, margin: {v["margin"]} }}'
        for y, v in sorted(years.items())
    )

for fips, c in sorted(counties.items()):
    year_entries = fmt_years(c["years"])
    special_entries = fmt_years(c["specialYears"])
    name = c["countyName"].replace('"', '\\"')
    out.append(
        f'  "{fips}": {{ state: "{c["state"]}", countyName: "{name}", years: {{ {year_entries} }}, specialYears: {{ {special_entries} }} }},'
    )

out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(counties)} counties across years {YEARS} -> {DST}")
