#!/usr/bin/env python3
"""
Generates data/countySenateData.ts by merging every data-entry/county_senate_results_{year}.csv
found on disk (each scraped from Wikipedia's per-state "By county" tables - see
scripts/scrape-county-senate-{year}.py). Margins are R-positive (positive = R advantage),
matching lib/colorScale.ts's convention.
Run from project root: python3 scripts/generate-county-senate-data.py
"""
import csv, glob, os, re
from collections import defaultdict

SRC_GLOB = os.path.join(os.path.dirname(__file__), "../data-entry/county_senate_results_*.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/countySenateData.ts")

SRC_FILES = sorted(glob.glob(SRC_GLOB))
YEARS = sorted(int(re.search(r"_(\d{4})\.csv$", f).group(1)) for f in SRC_FILES)

def two_pct(a, b):
    total = a + b
    return round(a / total * 100, 2) if total else 0.0

counties = {}
for path in SRC_FILES:
    year = int(re.search(r"_(\d{4})\.csv$", path).group(1))
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            fips = r["county_id"]
            entry = counties.setdefault(fips, {"state": r["state"], "countyName": r["county_name"], "years": {}})
            dem, gop, oth, total = int(r[f"dem_{year}"]), int(r[f"gop_{year}"]), int(r[f"oth_{year}"]), int(r[f"total_{year}"])
            entry["years"][year] = {
                "dem": dem, "gop": gop, "oth": oth, "total": total,
                "demPct": two_pct(dem, gop), "repPct": two_pct(gop, dem),
                "margin": round(two_pct(gop, dem) - two_pct(dem, gop), 2),
            }

out = [
    "// Auto-generated by scripts/generate-county-senate-data.py",
    "// Source: data-entry/county_senate_results_{year}.csv, scraped from Wikipedia's per-state",
    "// \"By county\" tables (scripts/scrape-county-senate-{year}.py) and cross-validated against",
    "// data-entry/senate_past_results.csv's state-level totals. Margins are R-positive",
    "// (positive = R advantage). Key = 5-digit county FIPS. Only states with a Senate race",
    "// that year are present; states without one that cycle simply have no entry for it.",
    f"// Years covered: {', '.join(str(y) for y in YEARS)}.",
    "// Known gaps: NY 2024 undercounts the Democratic column by ~540k votes (fusion voting -",
    "// Wikipedia's table only shows the Democratic ballot line, not the combined total used",
    "// in senate_past_results.csv); MO 2024 is missing Dallas County (absent from the Wikipedia",
    "// source table itself); most other states run <1% (often <0.1%) under the certified state",
    "// total, likely uncounted absentee/overseas ballots reported only at the state level.",
    "// 2022 has no county-level source table at all for IA, KS, KY, LA, MO, NC, OK -",
    "// those states' Wikipedia Senate pages lack a \"By county\" section for that year (confirmed",
    "// by manual inspection, not a scraper bug). AK 2022 (and no other year yet) IS included -",
    "// Alaska has no by-county breakdown in ANY source's normal reporting since it has no",
    "// counties, but was reconstructed from the state's official Cast Vote Record instead;",
    "// see data-entry/README-ak-cvr-reconstructions.md. Uses ROUND-1 (first-choice) vote",
    "// shares for Chesbro (dem) / Murkowski (rep) specifically, matching how",
    "// senate_past_results.csv already stores this race (the true final RCV round was",
    "// Murkowski vs. Tshibaka - both Republicans - so a final-round number wouldn't be a",
    "// meaningful D-vs-R comparison). Because of that, this race's \"oth\" bucket is unusually",
    "// large in some counties (Tshibaka's own round-1 share), which distorts the two-party",
    "// demPct/repPct shown here more than a typical race - a real property of the underlying",
    "// contest, not a data error.",
    "",
    "export type CountyYearResult = {",
    "  demVotes: number; repVotes: number; othVotes: number; totalVotes: number;",
    "  demPct: number; repPct: number; // two-party",
    "  margin: number; // R-positive (repPct - demPct)",
    "};",
    "export type CountySenateResult = {",
    "  state: string;",
    "  countyName: string;",
    "  years: Partial<Record<number, CountyYearResult>>;",
    "};",
    "",
    "export const countySenateData: Record<string, CountySenateResult> = {",
]

for fips, c in sorted(counties.items()):
    year_entries = ", ".join(
        f'{y}: {{ demVotes: {v["dem"]}, repVotes: {v["gop"]}, othVotes: {v["oth"]}, totalVotes: {v["total"]}, '
        f'demPct: {v["demPct"]}, repPct: {v["repPct"]}, margin: {v["margin"]} }}'
        for y, v in sorted(c["years"].items())
    )
    name = c["countyName"].replace('"', '\\"')
    out.append(
        f'  "{fips}": {{ state: "{c["state"]}", countyName: "{name}", years: {{ {year_entries} }} }},'
    )

out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(counties)} counties across years {YEARS} -> {DST}")
