#!/usr/bin/env python3
"""
Generates data/electionCalendar.ts from senate_past_results.csv, governor_past_results.csv,
and house_past_results.csv. Each CSV has one row per state per year an election actually
happened, so presence of a (state_abbr, year) pair means that state held that race that year.
President is excluded — every state votes every presidential cycle, so it never greys out.
Run from project root: python3 scripts/generate-election-calendar.py
"""
import csv, os

DATA_ENTRY = os.path.join(os.path.dirname(__file__), "../data-entry")
DST = os.path.join(os.path.dirname(__file__), "../data/electionCalendar.ts")

SOURCES = {
    "senate": "senate_past_results.csv",
    "governor": "governor_past_results.csv",
    "house": "house_past_results.csv",
}

calendar = {}
for race_type, filename in SOURCES.items():
    years_by_state: dict[str, set[int]] = {}
    with open(os.path.join(DATA_ENTRY, filename), newline="") as f:
        for r in csv.DictReader(f):
            abbr = r["state_abbr"]
            year = int(r["year"])
            years_by_state.setdefault(abbr, set()).add(year)
    calendar[race_type] = {abbr: sorted(years) for abbr, years in sorted(years_by_state.items())}

out = [
    "// Auto-generated by scripts/generate-election-calendar.py",
    "// Source: data-entry/{senate,governor,house}_past_results.csv — presence of a",
    "// (state, year) row means that state held that race that year. President is excluded;",
    "// it never greys out since every state votes every presidential cycle.",
    "",
    'export type CountyRaceType = "senate" | "governor" | "house";',
    "",
    "export const electionCalendar: Record<CountyRaceType, Record<string, number[]>> = {",
]

for race_type, years_by_state in calendar.items():
    out.append(f"  {race_type}: {{")
    for abbr, years in years_by_state.items():
        out.append(f"    {abbr}: [{', '.join(str(y) for y in years)}],")
    out.append("  },")

out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written electionCalendar.ts -> {DST}")
for race_type, years_by_state in calendar.items():
    print(f"  {race_type}: {len(years_by_state)} states")
