#!/usr/bin/env python3
"""
Generates data/governorCandidatesByYear.ts from data-entry/governor_past_results.csv,
giving county detail pages the D/R candidate names to pair with countyGovernorData's
county-level vote counts. Where a state had both a regular and special election in
the same year, the regular race wins.
Run from project root: python3 scripts/generate-governor-candidates.py
"""
import csv, os

SRC = os.path.join(os.path.dirname(__file__), "../data-entry/governor_past_results.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/governorCandidatesByYear.ts")

by_state: dict[str, dict[int, dict]] = {}
with open(SRC, newline="") as f:
    for r in csv.DictReader(f):
        year = int(r["year"])
        state = r["state_abbr"]
        years = by_state.setdefault(state, {})
        if year in years and r["type"] == "Special":
            continue  # keep the regular race if both exist
        years[year] = {"dem": r["dem_candidate"], "rep": r["rep_candidate"]}

out = [
    "// Auto-generated by scripts/generate-governor-candidates.py",
    "// Source: data-entry/governor_past_results.csv",
    "",
    "export const governorCandidatesByYear: Record<string, Record<number, { dem: string; rep: string }>> = {",
]
for state, years in sorted(by_state.items()):
    entries = ", ".join(
        f'{y}: {{ dem: "{c["dem"]}", rep: "{c["rep"]}" }}'
        for y, c in sorted(years.items())
    )
    out.append(f'  {state}: {{ {entries} }},')
out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(by_state)} states -> {DST}")
