#!/usr/bin/env python3
"""
Generates data/districtPresidentialData.ts from the electindex_historical.csv.
Run from project root: python3 scripts/generate-district-presidential.py
"""

import csv, os, sys

STATE_FIPS = {
    "AL":"01","AK":"02","AZ":"04","AR":"05","CA":"06","CO":"08","CT":"09",
    "DE":"10","FL":"12","GA":"13","HI":"15","ID":"16","IL":"17","IN":"18",
    "IA":"19","KS":"20","KY":"21","LA":"22","ME":"23","MD":"24","MA":"25",
    "MI":"26","MN":"27","MS":"28","MO":"29","MT":"30","NE":"31","NV":"32",
    "NH":"33","NJ":"34","NM":"35","NY":"36","NC":"37","ND":"38","OH":"39",
    "OK":"40","OR":"41","PA":"42","RI":"44","SC":"45","SD":"46","TN":"47",
    "TX":"48","UT":"49","VT":"50","VA":"51","WA":"53","WV":"54","WI":"55",
    "WY":"56",
}

def to_id(code):
    state, dist = code.split("-")
    return STATE_FIPS[state] + dist.zfill(2)

def two_pct(dem, rep):
    total = dem + rep
    return round(dem / total * 100, 1) if total else 0.0

src = os.path.join(os.path.dirname(__file__), "../data-entry/electindex_historical.csv")
dst = os.path.join(os.path.dirname(__file__), "../data/districtPresidentialData.ts")

rows = []
with open(src, newline="") as f:
    for r in csv.DictReader(f):
        if r["level"] != "district":
            continue
        d16, r16 = int(r["pres16_dem"]), int(r["pres16_rep"])
        d20, r20 = int(r["pres20_dem"]), int(r["pres20_rep"])
        d24, r24 = int(r["pres24_dem"]), int(r["pres24_rep"])
        rows.append({
            "id":   to_id(r["code"]),
            "code": r["code"],
            "state": r["state"],
            "p16d": two_pct(d16,r16), "p16r": two_pct(r16,d16), "p16dv": d16, "p16rv": r16,
            "p20d": two_pct(d20,r20), "p20r": two_pct(r20,d20), "p20dv": d20, "p20rv": r20,
            "p24d": two_pct(d24,r24), "p24r": two_pct(r24,d24), "p24dv": d24, "p24rv": r24,
        })

lines = [
    "// Auto-generated by scripts/generate-district-presidential.py",
    "// Source: electindex.com — presidential results reaggregated to current district boundaries.",
    "// Key: 4-digit district ID (state_fips + district_num) matching houseStatewideResults.",
    "",
    "export type DistrictPresResult = {",
    "  code: string;",
    "  state: string;",
    "  pres16DemPct: number; pres16RepPct: number; pres16DemVotes: number; pres16RepVotes: number;",
    "  pres20DemPct: number; pres20RepPct: number; pres20DemVotes: number; pres20RepVotes: number;",
    "  pres24DemPct: number; pres24RepPct: number; pres24DemVotes: number; pres24RepVotes: number;",
    "};",
    "",
    "export const districtPresidentialData: Record<string, DistrictPresResult> = {",
]

for e in rows:
    lines.append(
        f'  "{e["id"]}": {{ code: "{e["code"]}", state: "{e["state"]}", '
        f'pres16DemPct: {e["p16d"]}, pres16RepPct: {e["p16r"]}, pres16DemVotes: {e["p16dv"]}, pres16RepVotes: {e["p16rv"]}, '
        f'pres20DemPct: {e["p20d"]}, pres20RepPct: {e["p20r"]}, pres20DemVotes: {e["p20dv"]}, pres20RepVotes: {e["p20rv"]}, '
        f'pres24DemPct: {e["p24d"]}, pres24RepPct: {e["p24r"]}, pres24DemVotes: {e["p24dv"]}, pres24RepVotes: {e["p24rv"]} }},'
    )

lines += ["};", ""]

with open(dst, "w") as f:
    f.write("\n".join(lines))

print(f"Written {len(rows)} districts → {dst}")
