#!/usr/bin/env python3
"""
Generates data/countyGovernorData.ts by merging every
data-entry/county_governor_results_{year}.csv found on disk (each scraped from
Wikipedia's per-state "By county" tables - see
scripts/scrape-county-governor-{year}.py). Margins are R-positive (positive =
R advantage), matching lib/colorScale.ts's convention.
Run from project root: python3 scripts/generate-county-governor-data.py
"""
import csv, glob, os, re

SRC_GLOB = os.path.join(os.path.dirname(__file__), "../data-entry/county_governor_results_*.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/countyGovernorData.ts")

SRC_FILES = sorted(glob.glob(SRC_GLOB))
YEARS = sorted(int(re.search(r"_(\d{4})\.csv$", f).group(1)) for f in SRC_FILES)

def two_pct(a, b):
    total = a + b
    return round(a / total * 100, 2) if total else 0.0

counties = {}
for path in SRC_FILES:
    year = int(re.search(r"_(\d{4})\.csv$", path).group(1))
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            fips = r["county_id"]
            entry = counties.setdefault(fips, {"state": r["state"], "countyName": r["county_name"], "years": {}})
            dem, gop, oth, total = int(r[f"dem_{year}"]), int(r[f"gop_{year}"]), int(r[f"oth_{year}"]), int(r[f"total_{year}"])
            entry["years"][year] = {
                "dem": dem, "gop": gop, "oth": oth, "total": total,
                "demPct": two_pct(dem, gop), "repPct": two_pct(gop, dem),
                "margin": round(two_pct(gop, dem) - two_pct(dem, gop), 2),
            }

out = [
    "// Auto-generated by scripts/generate-county-governor-data.py",
    "// Source: data-entry/county_governor_results_{year}.csv, scraped from Wikipedia's per-state",
    "// \"By county\" tables (scripts/scrape-county-governor-{year}.py) and cross-validated against",
    "// data-entry/governor_past_results.csv's state-level totals. Margins are R-positive",
    "// (positive = R advantage). Key = 5-digit county FIPS. Only states with a Governor race",
    "// that year are present; states without one that cycle simply have no entry for it.",
    f"// Years covered: {', '.join(str(y) for y in YEARS)}.",
    "// AK 2018 and 2022 ARE included despite Alaska having no by-county breakdown in any",
    "// source's normal reporting (it has no counties) - reconstructed from the state's own",
    "// official precinct-level election data instead. 2018 predates AK's RCV system (plain",
    "// plurality; matched certified exactly, to the vote). 2022 used a real Cast Vote",
    "// Record since Dunleavy won an outright majority in round 1 (no RCV redistribution",
    "// needed, so first-choice = final result). See",
    "// data-entry/README-ak-cvr-reconstructions.md for the full methodology.",
    "",
    "export type CountyYearResult = {",
    "  demVotes: number; repVotes: number; othVotes: number; totalVotes: number;",
    "  demPct: number; repPct: number; // two-party",
    "  margin: number; // R-positive (repPct - demPct)",
    "};",
    "export type CountyGovernorResult = {",
    "  state: string;",
    "  countyName: string;",
    "  years: Partial<Record<number, CountyYearResult>>;",
    "};",
    "",
    "export const countyGovernorData: Record<string, CountyGovernorResult> = {",
]

for fips, c in sorted(counties.items()):
    year_entries = ", ".join(
        f'{y}: {{ demVotes: {v["dem"]}, repVotes: {v["gop"]}, othVotes: {v["oth"]}, totalVotes: {v["total"]}, '
        f'demPct: {v["demPct"]}, repPct: {v["repPct"]}, margin: {v["margin"]} }}'
        for y, v in sorted(c["years"].items())
    )
    name = c["countyName"].replace('"', '\\"')
    out.append(
        f'  "{fips}": {{ state: "{c["state"]}", countyName: "{name}", years: {{ {year_entries} }} }},'
    )

out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(counties)} counties across years {YEARS} -> {DST}")
