#!/usr/bin/env python3
"""
Generates data/districtPresidentialData.ts from house_pres_2026_dist.csv.

Percentages and margins are PERCENT OF TOTAL VOTE, not two-party share - the same basis
as every other margin in the TPL model (presPastResults, the House/Senate/Governor
pastResults, and the county datasets all report share of the full total). The source
CSV's own margin_YYYY columns are two-party and are therefore IGNORED; margins are
recomputed here from the vote columns against pres{YY}_total, which includes third
parties. This matters most in 2016, where a ~6% national third-party vote compresses
pct-of-total margins by 1-2 points relative to two-party.

Run from project root: python3 scripts/generate-district-pres-data.py
"""
import csv, os

SRC = os.path.join(os.path.dirname(__file__), "../data-entry/house_pres_2026_dist.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/districtPresidentialData.ts")

def share_pct(votes, total):
    """Share of the FULL total (third parties included), matching the rest of the model."""
    return round(votes / total * 100, 2) if total else 0.0

rows = []
with open(SRC, newline="") as f:
    for r in csv.DictReader(f):
        d16, r16, t16 = int(r["pres16_dem"]), int(r["pres16_rep"]), int(r["pres16_total"])
        d20, r20, t20 = int(r["pres20_dem"]), int(r["pres20_rep"]), int(r["pres20_total"])
        d24, r24, t24 = int(r["pres24_dem"]), int(r["pres24_rep"]), int(r["pres24_total"])
        # The CSV's margin_YYYY columns are two-party and D-positive - unused. Margins are
        # recomputed R-positive as a share of the full total.
        rows.append({
            "id":        str(r["district_id"]),
            "code":      r["code"],
            "state":     r["state"],
            "stateName": r["state_name"],
            "d16": d16, "r16": r16,
            "d20": d20, "r20": r20,
            "d24": d24, "r24": r24,
            "t16": t16, "t20": t20, "t24": t24,
            "m16": round((r16 - d16) / t16 * 100, 4) if t16 else 0.0,  # R-positive, pct of total
            "m20": round((r20 - d20) / t20 * 100, 4) if t20 else 0.0,
            "m24": round((r24 - d24) / t24 * 100, 4) if t24 else 0.0,
            "dp16": share_pct(d16, t16), "rp16": share_pct(r16, t16),
            "dp20": share_pct(d20, t20), "rp20": share_pct(r20, t20),
            "dp24": share_pct(d24, t24), "rp24": share_pct(r24, t24),
        })

out = [
    "// Auto-generated by scripts/generate-district-pres-data.py",
    "// Source: house_pres_2026_dist.csv (electindex.com, reaggregated to 2026 boundaries)",
    "// Percentages and margins are PERCENT OF TOTAL VOTE (third parties included), matching every",
    "// other margin in the TPL model. Margins are R-positive (positive = R advantage).",
    "// Key = district_id (state FIPS + district, no leading zeros).",
    "// This data is used exclusively by the TPL model — not surfaced elsewhere on the site.",
    "",
    "export type DistrictPresResult = {",
    "  code: string;       // e.g. 'AL-01'",
    "  state: string;      // e.g. 'AL'",
    "  stateName: string;",
    "  // Vote percentages, as a share of the FULL total (not two-party)",
    "  pres16DemPct: number; pres16RepPct: number;",
    "  pres20DemPct: number; pres20RepPct: number;",
    "  pres24DemPct: number; pres24RepPct: number;",
    "  // Raw vote totals; pres{YY}Total is the full total, so third-party votes are",
    "  // total minus dem minus rep.",
    "  pres16DemVotes: number; pres16RepVotes: number; pres16Total: number;",
    "  pres20DemVotes: number; pres20RepVotes: number; pres20Total: number;",
    "  pres24DemVotes: number; pres24RepVotes: number; pres24Total: number;",
    "  // R-positive margins (positive = R wins)",
    "  pres16Margin: number;",
    "  pres20Margin: number;",
    "  pres24Margin: number;",
    "};",
    "",
    "export const districtPresidentialData: Record<string, DistrictPresResult> = {",
]

for e in rows:
    out.append(
        f'  "{e["id"]}": {{ '
        f'code: "{e["code"]}", state: "{e["state"]}", stateName: "{e["stateName"]}", '
        f'pres16DemPct: {e["dp16"]}, pres16RepPct: {e["rp16"]}, '
        f'pres20DemPct: {e["dp20"]}, pres20RepPct: {e["rp20"]}, '
        f'pres24DemPct: {e["dp24"]}, pres24RepPct: {e["rp24"]}, '
        f'pres16DemVotes: {e["d16"]}, pres16RepVotes: {e["r16"]}, pres16Total: {e["t16"]}, '
        f'pres20DemVotes: {e["d20"]}, pres20RepVotes: {e["r20"]}, pres20Total: {e["t20"]}, '
        f'pres24DemVotes: {e["d24"]}, pres24RepVotes: {e["r24"]}, pres24Total: {e["t24"]}, '
        f'pres16Margin: {e["m16"]}, pres20Margin: {e["m20"]}, pres24Margin: {e["m24"]} }},'
    )

out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(rows)} districts → {DST}")
