#!/usr/bin/env python3
"""
Generates data/countyPresidentialData.ts from county_presidential_results_2008_2024.csv.
Margins are R-positive (positive = R advantage), matching lib/colorScale.ts's convention.
Run from project root: python3 scripts/generate-county-pres-data.py
"""
import csv, os

SRC = os.path.join(os.path.dirname(__file__), "../data/county_presidential_results_2008_2024.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/countyPresidentialData.ts")

YEARS = [2008, 2012, 2016, 2020, 2024]

def two_pct(a, b):
    total = a + b
    return round(a / total * 100, 2) if total else 0.0

counties = []
with open(SRC, newline="") as f:
    for r in csv.DictReader(f):
        years = {}
        for y in YEARS:
            total = r[f"total_{y}"]
            if total == "":
                continue
            dem, gop, oth, total = int(r[f"dem_{y}"]), int(r[f"gop_{y}"]), int(r[f"oth_{y}"]), int(total)
            years[y] = {
                "dem": dem, "gop": gop, "oth": oth, "total": total,
                "demPct": two_pct(dem, gop), "repPct": two_pct(gop, dem),
                "margin": round(two_pct(gop, dem) - two_pct(dem, gop), 2),
            }
        counties.append({
            "fips": r["county_id"],
            "state": r["state"],
            "countyName": r["county_name"],
            "years": years,
        })

out = [
    "// Auto-generated by scripts/generate-county-pres-data.py",
    "// Source: county_presidential_results_2008_2024.csv (see data pipeline memory for provenance).",
    "// Margins are R-positive (positive = R advantage). Key = 5-digit county FIPS (matches",
    "// public/us-counties.json's geo.id). Kalawao County, HI has no entries for any year",
    "// (folded into Maui) — do not backfill with estimates. Alaska boroughs' numbers (every",
    "// year 2016-2024) were reconstructed from the state's own official precinct-level",
    "// election data (2024: ballot-level Cast Vote Record, since that race needed a real RCV",
    "// tabulation; 2016/2020: plain precinct vote totals, since AK didn't use RCV yet - 2018",
    "// N/A, not a presidential year) since AK reports no by-borough breakdown in any public",
    "// source — see data-entry/README-ak-cvr-reconstructions.md for the precinct→borough",
    "// crosswalk and methodology (real precincts attributed directly; the portion of the",
    "// vote that's only resolved to a state house district in AK's own reporting was",
    "// apportioned across that district's boroughs by real-precinct turnout share — a",
    "// disclosed estimate, not a gap).",
    "",
    "export type CountyYearResult = {",
    "  demVotes: number; repVotes: number; othVotes: number; totalVotes: number;",
    "  demPct: number; repPct: number; // two-party",
    "  margin: number; // R-positive (repPct - demPct)",
    "};",
    "export type CountyPresResult = {",
    "  state: string;",
    "  countyName: string;",
    "  years: Partial<Record<2008 | 2012 | 2016 | 2020 | 2024, CountyYearResult>>;",
    "};",
    "",
    "export const countyPresidentialData: Record<string, CountyPresResult> = {",
]

for c in counties:
    year_entries = ", ".join(
        f'{y}: {{ demVotes: {v["dem"]}, repVotes: {v["gop"]}, othVotes: {v["oth"]}, totalVotes: {v["total"]}, '
        f'demPct: {v["demPct"]}, repPct: {v["repPct"]}, margin: {v["margin"]} }}'
        for y, v in c["years"].items()
    )
    name = c["countyName"].replace('"', '\\"')
    out.append(
        f'  "{c["fips"]}": {{ state: "{c["state"]}", countyName: "{name}", years: {{ {year_entries} }} }},'
    )

out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(counties)} counties -> {DST}")
