#!/usr/bin/env python3
"""
Generates data/senateCandidatesByYear.ts from data-entry/senate_past_results.csv,
giving county detail pages the D/R candidate names to pair with countySenateData's
county-level vote counts. Where a state had both a regular and special election in
the same year (e.g. NE in 2024), the regular race's candidates go into
senateCandidatesByYear (paired with countySenateData's `years`) and the special race's
into the sibling specialSenateCandidatesByYear export (paired with `specialYears`) -
see scripts/scrape-county-senate-{year}-special.py.
Run from project root: python3 scripts/generate-senate-candidates.py
"""
import csv, os

SRC = os.path.join(os.path.dirname(__file__), "../data-entry/senate_past_results.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/senateCandidatesByYear.ts")

by_state: dict[str, dict[int, dict]] = {}
special_by_state: dict[str, dict[int, dict]] = {}
with open(SRC, newline="") as f:
    for r in csv.DictReader(f):
        year = int(r["year"])
        state = r["state_abbr"]
        candidates = {"dem": r["dem_candidate"], "rep": r["rep_candidate"]}
        if r["type"] == "Special":
            special_by_state.setdefault(state, {})[year] = candidates
        else:
            by_state.setdefault(state, {})[year] = candidates

def fmt_states(states: dict) -> list[str]:
    lines = []
    for state, years in sorted(states.items()):
        entries = ", ".join(
            f'{y}: {{ dem: "{c["dem"]}", rep: "{c["rep"]}" }}'
            for y, c in sorted(years.items())
        )
        lines.append(f'  {state}: {{ {entries} }},')
    return lines

out = [
    "// Auto-generated by scripts/generate-senate-candidates.py",
    "// Source: data-entry/senate_past_results.csv",
    "",
    "export const senateCandidatesByYear: Record<string, Record<number, { dem: string; rep: string }>> = {",
    *fmt_states(by_state),
    "};",
    "",
    "export const specialSenateCandidatesByYear: Record<string, Record<number, { dem: string; rep: string }>> = {",
    *fmt_states(special_by_state),
    "};",
    "",
]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(by_state)} states ({len(special_by_state)} with a special) -> {DST}")
