#!/usr/bin/env python3
"""
Generates data/fundraisingData.ts from data-entry/fundraising_2016_2026.csv.

House/Senate receipts come from FEC bulk candidate summaries (webl/weball,
2016-2026 cycles) matched to each race's general-election candidates by name
(see the CSV's notes column for match caveats; 'api-pending' sides are blank
until the FEC API backfill lands, '0' means no FEC filings were found anywhere
2016-2026 — i.e. the candidate stayed under the $5k filing threshold).
Governor rows are placeholders: gubernatorial money is filed with the states,
not the FEC, and is pending an OpenSecrets/TransparencyUSA/manual pass.

Keys: "H:{district}:{year}" · "S:{state}:{year}:{Regular|Special}" · "G:{state}:{year}"
Run from project root: python3 scripts/generate-fundraising-data.py
"""
import csv, os

SRC = os.path.join(os.path.dirname(__file__), "../data-entry/fundraising_2016_2026.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/fundraisingData.ts")

def num(v):
    v = (v or "").strip()
    if v == "": return None
    return int(round(float(v)))

entries = []
with open(SRC) as f:
    for r in csv.DictReader(f):
        dem, rep = num(r["dem_receipts"]), num(r["rep_receipts"])
        if dem is None and rep is None: continue
        if r["office"] == "H":
            key = f'H:{r["race"]}:{r["year"]}'
        elif r["office"] == "S":
            key = f'S:{r["state"]}:{r["year"]}:{"Special" if r["election_type"] == "Special" else "Regular"}'
        else:
            key = f'G:{r["state"]}:{r["year"]}'
        entries.append((key, dem, rep))

entries.sort()
with open(DST, "w") as f:
    f.write("// GENERATED by scripts/generate-fundraising-data.py from data-entry/fundraising_2016_2026.csv\n")
    f.write("// Candidate-committee total receipts (whole dollars) for each race's general-election\n")
    f.write("// candidates. null = unknown (api-pending or governor state filings); 0 = no FEC filings\n")
    f.write("// found (sub-$5k candidate). Do not edit by hand - edit the CSV and regenerate.\n\n")
    f.write("export interface RaceFundraising {\n  dem: number | null;\n  rep: number | null;\n}\n\n")
    f.write("export const fundraisingData: Record<string, RaceFundraising> = {\n")
    for key, dem, rep in entries:
        f.write(f'  "{key}": {{ dem: {"null" if dem is None else dem}, rep: {"null" if rep is None else rep} }},\n')
    f.write("};\n")
print(f"wrote {len(entries)} entries to {DST}")
