#!/usr/bin/env python3
"""
Generates data/officeholders.ts from data-entry/governor_seats.csv and
data-entry/senate_seats.csv — the sitting governor and both US senators for every state,
each with the year their seat is next up.

Both CSVs already carry `current_incumbent`, `inc_party` and `next_election`; what they did not
have was anywhere to go. data/forecastData.ts is generated from the same rows but keeps only the
seats being forecast this cycle (35 of 100 senate seats, 36 of 50 governorships), so nothing in the
app could answer "who represents this address" for the other two-thirds. That is what the district
finder needs, so this writes the whole roster out separately rather than widening forecastData.

Senate seats are emitted in `seat` order (1 then 2) so a state's two senators always render in a
stable order. The senior/junior distinction is not in the source data and is not inferred here.

Run from project root: python3 scripts/generate-officeholders.py
"""
import csv, os

ROOT = os.path.dirname(__file__)
GOV_SRC = os.path.join(ROOT, "../data-entry/governor_seats.csv")
SEN_SRC = os.path.join(ROOT, "../data-entry/senate_seats.csv")
SEN_PAST = os.path.join(ROOT, "../data-entry/senate_past_results.csv")
DST = os.path.join(ROOT, "../data/officeholders.ts")

PARTY = {"D": "D", "R": "R", "I": "I"}


def party(raw: str) -> str:
    """Anything that isn't one of the majors or an explicit independent is stored as "O"."""
    return PARTY.get(raw.strip().upper(), "O")


def js(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


governors: dict[str, dict] = {}
with open(GOV_SRC, newline="") as f:
    for r in csv.DictReader(f):
        governors[r["state_abbr"]] = {
            "name": r["current_incumbent"].strip(),
            "party": party(r["inc_party"]),
            "nextElection": int(r["next_election"]),
            "termYears": int(r["term_length"]),
        }

# Senators who sit as independents are written "(I)" after their name in the past-results file,
# which is the repo's own record of how they actually ran. senate_seats.csv instead files them under
# the party they caucus with, which is the right call for a forecast's seat math but wrong on a page
# that names the person — Angus King and Bernie Sanders are Independents, not Democrats. The
# suffix is the authority here; the seats file's caucus label is left alone for the forecast.
independents: set[tuple[str, str]] = set()
with open(SEN_PAST, newline="") as f:
    for r in csv.DictReader(f):
        for field in ("dem_candidate", "rep_candidate"):
            name = r[field].strip()
            if name.endswith("(I)"):
                independents.add((r["state_abbr"], name[:-3].strip()))

senators: dict[str, list[dict]] = {}
with open(SEN_SRC, newline="") as f:
    for r in csv.DictReader(f):
        senators.setdefault(r["state_abbr"], []).append({
            "seat": int(r["seat"]),
            "seatClass": int(r["class"]),
            "name": r["current_incumbent"].strip(),
            "party": "I" if (r["state_abbr"], r["current_incumbent"].strip()) in independents else party(r["inc_party"]),
            "nextElection": int(r["next_election"]),
        })
for rows in senators.values():
    rows.sort(key=lambda s: s["seat"])

problems = []
for abbr, rows in sorted(senators.items()):
    if len(rows) != 2:
        problems.append(f"{abbr}: {len(rows)} senate seats, expected 2")
    for s in rows:
        if not s["name"]:
            problems.append(f"{abbr} seat {s['seat']}: no incumbent")
for abbr, g in sorted(governors.items()):
    if not g["name"]:
        problems.append(f"{abbr}: no governor")
missing = set(governors) ^ set(senators)
if missing:
    problems.append(f"states in one file but not the other: {sorted(missing)}")
if problems:
    raise SystemExit("Refusing to write; source data is incomplete:\n  " + "\n  ".join(problems))

lines = [
    "// Sitting statewide officeholders and when each seat is next up. Auto-generated by",
    "// scripts/generate-officeholders.py from data-entry/governor_seats.csv and",
    "// data-entry/senate_seats.csv — do not edit by hand, rerun the script.",
    "//",
    "// data/forecastData.ts is built from the same rows but keeps only the seats on this cycle's",
    "// ballot; this is the full roster, for answering who represents a given address.",
    "",
    'export type OfficeholderParty = "D" | "R" | "I" | "O";',
    "",
    "export type Governor = {",
    "  name: string;",
    "  party: OfficeholderParty;",
    "  /** Year this seat is next on the ballot. */",
    "  nextElection: number;",
    "  termYears: number;",
    "};",
    "",
    "export type Senator = {",
    "  /** The state's seat 1 or 2 — an arbitrary but stable ordering, not seniority. */",
    "  seat: number;",
    "  /** US Senate class 1, 2 or 3, which is what sets the election year. */",
    "  seatClass: number;",
    "  name: string;",
    "  party: OfficeholderParty;",
    "  nextElection: number;",
    "};",
    "",
    "export type StateOfficeholders = { governor: Governor; senators: Senator[] };",
    "",
    "// Keyed by state abbreviation.",
    "export const officeholders: Record<string, StateOfficeholders> = {",
]

for abbr in sorted(governors):
    g = governors[abbr]
    lines.append(f"  {abbr}: {{")
    lines.append(
        f"    governor: {{ name: {js(g['name'])}, party: {js(g['party'])}, "
        f"nextElection: {g['nextElection']}, termYears: {g['termYears']} }},"
    )
    lines.append("    senators: [")
    for s in senators[abbr]:
        lines.append(
            f"      {{ seat: {s['seat']}, seatClass: {s['seatClass']}, name: {js(s['name'])}, "
            f"party: {js(s['party'])}, nextElection: {s['nextElection']} }},"
        )
    lines.append("    ],")
    lines.append("  },")

lines.append("};")

with open(DST, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {DST}: {len(governors)} governors, {sum(len(v) for v in senators.values())} senate seats")
