#!/usr/bin/env python3
"""
Generates data/districtPresidentialData.ts from house_pres_2026_dist.csv.
Source margins are D-positive; output converts to R-positive to match model convention.
Run from project root: python3 scripts/generate-district-pres-data.py
"""
import csv, os

SRC = os.path.join(os.path.dirname(__file__), "../data-entry/house_pres_2026_dist.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/districtPresidentialData.ts")

def two_pct(dem, rep):
    total = dem + rep
    return round(dem / total * 100, 1) if total else 0.0

rows = []
with open(SRC, newline="") as f:
    for r in csv.DictReader(f):
        d16, r16 = int(r["pres16_dem"]), int(r["pres16_rep"])
        d20, r20 = int(r["pres20_dem"]), int(r["pres20_rep"])
        d24, r24 = int(r["pres24_dem"]), int(r["pres24_rep"])
        # CSV margins are D-positive; negate to get R-positive for model
        rows.append({
            "id":        str(r["district_id"]),
            "code":      r["code"],
            "state":     r["state"],
            "stateName": r["state_name"],
            "d16": d16, "r16": r16,
            "d20": d20, "r20": r20,
            "d24": d24, "r24": r24,
            "m16": round(-float(r["margin_2016"]), 4),  # R-positive
            "m20": round(-float(r["margin_2020"]), 4),
            "m24": round(-float(r["margin_2024"]), 4),
            "dp16": two_pct(d16, r16), "rp16": two_pct(r16, d16),
            "dp20": two_pct(d20, r20), "rp20": two_pct(r20, d20),
            "dp24": two_pct(d24, r24), "rp24": two_pct(r24, d24),
        })

out = [
    "// Auto-generated by scripts/generate-district-pres-data.py",
    "// Source: house_pres_2026_dist.csv (electindex.com, reaggregated to 2026 boundaries)",
    "// Margins are R-positive (positive = R advantage). Key = district_id (state FIPS + district, no leading zeros).",
    "// This data is used exclusively by the TPL model — not surfaced elsewhere on the site.",
    "",
    "export type DistrictPresResult = {",
    "  code: string;       // e.g. 'AL-01'",
    "  state: string;      // e.g. 'AL'",
    "  stateName: string;",
    "  // Two-party vote percentages",
    "  pres16DemPct: number; pres16RepPct: number;",
    "  pres20DemPct: number; pres20RepPct: number;",
    "  pres24DemPct: number; pres24RepPct: number;",
    "  // Raw vote totals",
    "  pres16DemVotes: number; pres16RepVotes: number;",
    "  pres20DemVotes: number; pres20RepVotes: number;",
    "  pres24DemVotes: number; pres24RepVotes: number;",
    "  // R-positive margins (positive = R wins)",
    "  pres16Margin: number;",
    "  pres20Margin: number;",
    "  pres24Margin: number;",
    "};",
    "",
    "export const districtPresidentialData: Record<string, DistrictPresResult> = {",
]

for e in rows:
    out.append(
        f'  "{e["id"]}": {{ '
        f'code: "{e["code"]}", state: "{e["state"]}", stateName: "{e["stateName"]}", '
        f'pres16DemPct: {e["dp16"]}, pres16RepPct: {e["rp16"]}, '
        f'pres20DemPct: {e["dp20"]}, pres20RepPct: {e["rp20"]}, '
        f'pres24DemPct: {e["dp24"]}, pres24RepPct: {e["rp24"]}, '
        f'pres16DemVotes: {e["d16"]}, pres16RepVotes: {e["r16"]}, '
        f'pres20DemVotes: {e["d20"]}, pres20RepVotes: {e["r20"]}, '
        f'pres24DemVotes: {e["d24"]}, pres24RepVotes: {e["r24"]}, '
        f'pres16Margin: {e["m16"]}, pres20Margin: {e["m20"]}, pres24Margin: {e["m24"]} }},'
    )

out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written {len(rows)} districts → {DST}")
