#!/usr/bin/env python3
"""
Generates data/presByBoundaryVintage.ts from data-entry/pres_by_boundary_vintage.csv
(built by scripts/build-pres-by-boundary-vintage.py — see that script's docstring for the
sources and for why this table exists at all).

Run from project root: python3 scripts/generate-pres-by-boundary-vintage.py
"""
import csv, os
from collections import defaultdict

SRC = os.path.join(os.path.dirname(__file__), "../data-entry/pres_by_boundary_vintage.csv")
DST = os.path.join(os.path.dirname(__file__), "../data/presByBoundaryVintage.ts")

by = defaultdict(lambda: defaultdict(dict))
for r in csv.DictReader(open(SRC)):
    v, py = int(r["boundary_year"]), int(r["pres_year"])
    by[v][py][r["district_id"]] = (r["district_name"], float(r["dem_pct"]), float(r["rep_pct"]), float(r["margin"]))

vintages = sorted(by)

out = [
    "// Auto-generated by scripts/generate-pres-by-boundary-vintage.py — do not edit by hand.",
    "// Source: data-entry/pres_by_boundary_vintage.csv (see scripts/build-pres-by-boundary-vintage.py).",
    "//",
    "// Presidential results measured on each congressional map actually used from 2016 to 2024, so a",
    "// House race can be relocated onto today's lines by the presidential delta between the two maps.",
    "// A presidential-year map carries its own election; a MIDTERM map carries both neighbours, because",
    "// a 2018 race sits halfway between 2016 and 2020 and its shift is measured with both.",
    "//",
    "// The 2026-lines side of the subtraction is data/districtPresidentialData.ts.",
    "// Percentages and margins are PERCENT OF TOTAL VOTE (third parties included); margins R-positive.",
    "// Keys are district_id (state FIPS + district, no leading zeros) as in districtPresidentialData;",
    "// DC's delegate district is 1198. A district number that did not exist on a map is simply absent.",
    "",
    "export type BoundaryVintage = " + " | ".join(str(v) for v in vintages) + ";",
    "",
    "export type VintagePresResult = {",
    "  code: string;    // e.g. 'PA-07' AS NUMBERED ON THAT MAP",
    "  demPct: number;",
    "  repPct: number;",
    "  margin: number;  // R-positive, percent of total vote",
    "};",
    "",
    "/** Presidential elections measured on each map. */",
    "export const PRES_YEARS_FOR_VINTAGE: Record<BoundaryVintage, number[]> = {",
]
for v in vintages:
    out.append(f"  {v}: [{', '.join(str(p) for p in sorted(by[v]))}],")
out += [
    "};",
    "",
    "/** The congressional map a House election year was run on. Returns null outside the covered",
    " *  range; 2026 races need no relocation because 2026 IS the reference map. */",
    "export function boundaryVintageForHouseYear(year: number): BoundaryVintage | null {",
    "  " + " ".join(f"if (year === {v}) return {v};" for v in vintages),
    "  return null;",
    "}",
    "",
    "export const presByBoundaryVintage: Record<BoundaryVintage, Record<number, Record<string, VintagePresResult>>> = {",
]
for v in vintages:
    out.append(f"  {v}: {{")
    for py in sorted(by[v]):
        out.append(f"    {py}: {{")
        for did, (code, d, r, m) in sorted(by[v][py].items(), key=lambda kv: kv[1][0]):
            out.append(f'      "{did}": {{ code: "{code}", demPct: {d}, repPct: {r}, margin: {m} }},')
        out.append("    },")
    out.append("  },")
out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

total = sum(len(by[v][p]) for v in vintages for p in by[v])
print(f"Written {total} rows across {len(vintages)} maps → {DST}")
for v in vintages:
    print(f"  {v} lines: pres {sorted(by[v])}")
