#!/usr/bin/env python3
"""
Generates data/electionCalendar.ts from senate_past_results.csv, governor_past_results.csv,
and house_past_results.csv. Each CSV has one row per state per year an election actually
happened, so presence of a (state_abbr, year) pair means that state held that race that year.
President is excluded — every state votes every presidential cycle, so it never greys out.

Senate is split into two separate calendars: `electionCalendar.senate` (regular-class
races only, i.e. senate_past_results.csv rows NOT flagged type="Special") and
`senateSpecialCalendar` (Special-flagged rows only, e.g. AZ 2020, GA 2020, MN/MS 2018,
OK 2022/2014, NE 2024, HI/SC 2014). This matters for a state like AZ 2020 that had ONLY a
special race that year — under the old presence-only calendar it looked like AZ had "a"
regular Senate race in 2020, which isn't true and would make the map's regular-vs-special
toggle internally inconsistent. Governor/House have no specials in this dataset, so they
keep the simple presence-only shape.
Run from project root: python3 scripts/generate-election-calendar.py
"""
import csv, os

DATA_ENTRY = os.path.join(os.path.dirname(__file__), "../data-entry")
DST = os.path.join(os.path.dirname(__file__), "../data/electionCalendar.ts")

SOURCES = {
    "senate": "senate_past_results.csv",
    "governor": "governor_past_results.csv",
    "house": "house_past_results.csv",
}

calendar = {}
senate_special: dict[str, set[int]] = {}
for race_type, filename in SOURCES.items():
    years_by_state: dict[str, set[int]] = {}
    with open(os.path.join(DATA_ENTRY, filename), newline="") as f:
        for r in csv.DictReader(f):
            abbr = r["state_abbr"]
            year = int(r["year"])
            if race_type == "senate" and r.get("type") == "Special":
                senate_special.setdefault(abbr, set()).add(year)
                continue
            years_by_state.setdefault(abbr, set()).add(year)
    calendar[race_type] = {abbr: sorted(years) for abbr, years in sorted(years_by_state.items())}
senate_special = {abbr: sorted(years) for abbr, years in sorted(senate_special.items())}

out = [
    "// Auto-generated by scripts/generate-election-calendar.py",
    "// Source: data-entry/{senate,governor,house}_past_results.csv — presence of a",
    "// (state, year) row means that state held that race that year. President is excluded;",
    "// it never greys out since every state votes every presidential cycle.",
    "// electionCalendar.senate is REGULAR-class races only (excludes rows flagged",
    "// type=\"Special\") - see senateSpecialCalendar below for those.",
    "",
    'export type CountyRaceType = "senate" | "governor" | "house";',
    "",
    "export const electionCalendar: Record<CountyRaceType, Record<string, number[]>> = {",
]

for race_type, years_by_state in calendar.items():
    out.append(f"  {race_type}: {{")
    for abbr, years in years_by_state.items():
        out.append(f"    {abbr}: [{', '.join(str(y) for y in years)}],")
    out.append("  },")

out += ["};", ""]

out += [
    "// States/years with a Senate race flagged type=\"Special\" in senate_past_results.csv",
    "// (a state can appear here AND in electionCalendar.senate for the same year if it had",
    "// both, e.g. GA 2020 - or ONLY here if it had a special with no regular race that same",
    "// year, e.g. AZ 2020).",
    "export const senateSpecialCalendar: Record<string, number[]> = {",
]
for abbr, years in senate_special.items():
    out.append(f"  {abbr}: [{', '.join(str(y) for y in years)}],")
out += ["};", ""]

with open(DST, "w") as f:
    f.write("\n".join(out))

print(f"Written electionCalendar.ts -> {DST}")
for race_type, years_by_state in calendar.items():
    print(f"  {race_type}: {len(years_by_state)} states")
print(f"  senateSpecialCalendar: {len(senate_special)} states")
